### ISSUE TITLE
Splash screen text may overlap on certain environments

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#100]
On some machines all text messages on the splash screen are overlapping.

![Splash screen](https://f.cloud.github.com/assets/277531/1365958/e5dfb1c0-38a0-11e3-976b-4d41775e6fd3.jpg)

We tested with three machines so far. All of them are running Unity on Ubuntu 11.10.

Intermediate results:

```
* No difference between Unity 2D or 3D
* No difference between themes (Radiance or other ones)
* No difference in the monitor dpi values (96 for all machines)
```

We first suspected the screen resolution, but:

```
* Machine 1 uses a resolution of 1280 x 1024 pixels and has the problem.
* Machine 2, a small 9" eeePC, has a width of 1024 pixels, and has the problem, too.
* Machine 3 has a width of 1680 pixels and does not have the problem.
```

We couldn't reproduce it on machine 3, trying almost 10 different screen resolutions (including 4:3, 16:9 and 16:10 proportions).

If somebody has a pointer how to further isolate this issue please comment.

**Comment by Guite** [comment]
If we need to fix this urgently we could use a workaround by calculating the pixels a label requires before rendering it.
The class `org.eclipse.xtext.ui.util.PixelConverter` allows for doing this calculation based on the given font. If the result is too large we choose a smaller font size.

**Comment by Guite** [comment]
@gfr @portugao @rallek @ThiloWitt do you experience this problem on your machine?

**Comment by Portugao** [comment]
No.

**Comment by ThiloWitt** [comment]
On vacations, will check in about 10 days.

**Comment by rallek** [comment]
![grafik](https://user-images.githubusercontent.com/935250/32700350-f99a3b48-c7c3-11e7-93af-13c236de03e6.png)
That is the current snap shot on a windows 10 machine
It is allways the bold words what makes it ugly. If you spent just another line break after ``All Rights Reserved`` and before ``Version ...`` it should look better.
And the first line is to long. Another line break before ``(Guckelsberger Informations Tec`` might help also.

**Comment by rallek** [comment]
Via remote desktop on a Win7 machine I do get it like this:
![grafik](https://user-images.githubusercontent.com/935250/32700442-d48221a2-c7c5-11e7-837e-390de50b0f77.png)
That looks pretty nice. Something with the font size in different situations is creating the troubble.

**Comment by Guite** [comment]
Reduced the font size in order to fix this.
