### ISSUE TITLE
[1.4.6] geographical feature - default setting for latitude and longitude and handling of map

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1000]
The fields latitude and langitude get the defaut value '0.0000000', if we don't enter another value.
In the template we find:
```
        {% if location.latitude is not empty %}
            <dt>{{ __('Latitude') }}</dt>
            <dd>{{ location.latitude|muyourcitymodule_geoData }}</dd>
        {% endif %}
        {% if location.longitude is not empty %}
            <dt>{{ __('Longitude') }}</dt>
            <dd>{{ location.longitude|muyourcitymodule_geoData }}</dd>
        {% endif %} 
```
So the fields get shown with no relevant value. Also the map shows only placeholder.

So the 'if phrase' should look for this default value and that also for the map.
Also in the edit template it would be nice, if the map would not be called when creating a new item?!

**Comment by Guite** [comment]
I don't understand the issue yet.

> So the fields get shown with no relevant value.

So the condition is `true` also for `0.0000`?

> Also in the edit template it would be nice, if the map would not be called when creating a new item?!

But the idea is that you can click on the map for setting a marker and therewith choosing the coordinates instead of having to enter them manually.

**Comment by Guite** [comment]
issue 1000 :tada:

**Comment by Portugao** [comment]
Oh; I check.

**Comment by gfr** [comment]
Also 0,0/0,0 are valid coordinates!

**Comment by Portugao** [comment]
I see, then the problem is, that the does not losad correctly.

**Comment by Portugao** [comment]
The map does not load in the edit template.

**Comment by Portugao** [comment]
I changed the title.

**Comment by Portugao** [comment]
Now I changed the title:
It is, that the coordinates 0.0000000,0.0000000 are valid. We get no images, because of these the map is on the ocean and there is a high zoom factor for the map.
I think it would be fine to have 2 mod vars for that with default datas maybe in Berlin, a smaller zoom and map instead satellite.

**Comment by Guite** [comment]
interesting suggestion. there are some geographical modvars already there anyway, so it won't hurt if we introduce things like default coordinates, default zoom level and default map type

@gfr ?

**Comment by gfr** [comment]
@Portugao why you don't set the default values to null instead of 0,0?

**Comment by Portugao** [comment]
The edit template does. Maybe because I have english active.

**Comment by rallek** [comment]
Why not using 49.902343, 7.899549 as default? 😉

**Comment by Portugao** [comment]
With german language active they are 0,0000000,0,0000000.

**Comment by gfr** [comment]
@Portugao why you don't set the default values to null instead of 0,0?

**Comment by Portugao** [comment]
@gfr 
I've done nothing. If I call the edit form, the 2 fields get the named values.
If I wish to set the values in Germany it is not comfortable to have the start on 0,0.
Also a too high zoom level makes it difficcult to find the relevant part of a map.
