### ISSUE TITLE
cannot update preferences

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#1001]
upon suggestion, I am trying to enable staging updates.

I opened preferences
changed to 'Module Studio' pane
check the box next to 'Use staging updates'

but now cannot apply/click OK

![screen shot 2017-04-25 at 3 43 07 pm](https://cloud.githubusercontent.com/assets/350048/25404424/e5427870-29cd-11e7-9129-3fa308957be7.png)

turns out the first three fields (Vendor, Author, email address) are required.

If they are required, why did it function before they were set?

**Comment by rallek** [comment]
uncheck Ignore updates. I did have the same issue

**Comment by Guite** [comment]
This issue is about that the three text input fields are required. They maybe should not be.

**Comment by Guite** [comment]
```
Craig Heydenburg
[21:55] 
my point there is that *IF* they are required, then how can they start as empty? (edited)

[21:55] 
so either - they should be required and be required of hte user on startup

Axel Guckelsberger [21:55] 
actually they aren't required... but if they are set you won't need to have to fill in these fields each time you use the "new-app" wizard again

Craig Heydenburg [21:55] 
or they should not be required

[21:55] 
then they should NOT be required in that form

Axel Guckelsberger [21:56] 
okay, ty

Craig Heydenburg
[21:56] 
a doc note explaining the advantage would be a good idea

Craig Heydenburg
[21:56] 
I mean on the actual form
```

**Comment by rallek** [comment]
Ups. I did not read carefully enough

**Comment by Guite** [comment]
The fields are optional in the latest builds now.
