### ISSUE TITLE
[1.5] No object in display helper

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1013]
```
FatalErrorException in AbstractEntityDisplayHelper.php line 55:
Error: Call to a member function getLocale() on null
```

**Comment by Portugao** [comment]
Have to recheck.

**Comment by Guite** [comment]
In your `helpers.yml` file the `xxx.entity_display_helper` should have `- "@request_stack"` as second argument.

**Comment by Portugao** [comment]
Is there.
Want to delete the cache....

**Comment by Portugao** [comment]
This is gone, but other message:
```
ContextErrorException in AbstractEntityDisplayHelper.php line 56:
Warning: IntlDateFormatter::__construct() expects at least 3 parameters, 1 given
```

**Comment by Guite** [comment]
fixed in https://github.com/Guite/MostGenerator/commit/6a1598e1142a1b3fc8777323df9e205b1174951a

**Comment by Portugao** [comment]
Hmmhmm...now the first message is back:
```
FatalErrorException in AbstractEntityDisplayHelper.php line 55:
Error: Call to a member function getLocale() on null
```

**Comment by Portugao** [comment]
And the module is installed...

**Comment by Guite** [comment]
Please try changing
`$locale = $requestStack->getCurrentRequest()->getLocale();`
to
`$locale = null !== $requestStack->getCurrentRequest() ? $requestStack->getCurrentRequest()->getLocale() : null;`
and check if it works then.

**Comment by Portugao** [comment]
Bingo.
