### ISSUE TITLE
[1.5] Calling view in frontend gives error when first entry is in the DB

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1017]
```
Catchable Fatal Error: Argument 1 passed to Zikula\CategoriesModule\Api\CategoryPermissionApi::hasCategoryAccess() must be of the type array, object given, called in /www/htdocs/w00b922d/Zikula/Zik15/modules/MU/BloggingModule/Helper/Base/AbstractCategoryHelper.php on line 338 and defined
```

**Comment by Portugao** [comment]
Sorry, change the title, because entry is saved.

**Comment by Portugao** [comment]
```
    /**
     * {@inheritdoc}
     */
    public function hasCategoryAccess(array $categoryAssignments, $permLevel = ACCESS_OVERVIEW, $requireAccessForAll = false)
    {
        // Always allow access to content with no categories associated
        if (count($categoryAssignments) == 0) {
```

**Comment by Guite** [comment]
Can you please post the output of `die($entity['categories']);` at the beginning of `AbstractCategoryHelper#hasPermission($entity)`?

**Comment by Portugao** [comment]
No output.

**Comment by Portugao** [comment]
env: dev
    debug: true

**Comment by Portugao** [comment]
Sorry:    
prod: dev
debug: true

**Comment by Portugao** [comment]
With 
env: dev
debug: true
also none.

**Comment by Guite** [comment]
sorry, I meant `die(get_class($entity['categories']));`

**Comment by Portugao** [comment]
Doctrine\ORM\PersistentCollection

**Comment by Guite** [comment]
@craigh is the array type hint a core bug?

Does this work with Pages (see https://github.com/zikula-modules/Pages/blob/master/Helper/SearchHelper.php#L113 )?

**Comment by craigh** [comment]
I have that fixed somewhere, maybe I didn't push it.

`$page->getCategoryAssignments()` doesn't produce an array. It produces an `ArrayCollection` so it needs to be changed to `$page->getCategoryAssignments()->toArray()` then it works.

don't change Pages, I'll push my fix eventually.
