### ISSUE TITLE
Remove support for inter-module joins?

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#1034]
While this is not actively supported by the current tooling yet, it is possible to refer to other applications which initially has been added to express dependencies to other modules. See http://modulestudio.de/documentation/c/87-GeneratorReference#referred-application

Additionally the DSL allows for joining entities of other models: it is possible to add relationships from/to entities of referred applications. An example is shown in this video: http://modulestudio.de/downloads/someFeaturesTextualEditor.flv

I think that this could cause problems and side-effects though, for example when a referred application is not active or is deactivated later on. Thus I propose to remove this feature.

Opinions? @gfr @rallek @robbrandt @craigh @portugao

**Comment by robbrandt** [comment]
You are talking about support for this in MOST specifically, not in Zikula in general?  I already have some custom code that uses relationships to entities in other extensions.

Seems like a really nice feature though, is there an alternative way of doing it?  If it stays in, is there a way to use dependencies to prevent module deactivation?

**Comment by Guite** [comment]
> You are talking about support for this in MOST specifically, not in Zikula in general?
Yes, MOST.

> Seems like a really nice feature though, is there an alternative way of doing it?
> If it stays in, is there a way to use dependencies to prevent module deactivation?
Sure, but it does not fit to the "modular" philosophy. Modules should encapsulate concerns instead of mixing responsibilities across different modules. Thus I dislike encouraging users to do such things. Instead I see these as edge cases which can be done as part of customisation, but shouldn't be "officially" supported.

**Comment by Guite** [comment]
What I did is having an integer field for storing an ID and extending the generated entity class in order to add a selection of the "foreign" entity joined by this ID. This can be more explicitly controlled instead of letting Doctrine create object graphs across multiple modules by itself.

**Comment by Portugao** [comment]
Hmm...I sometimes thought about connect a module to another, but didn't use it in a MOST module.

**Comment by Guite** [comment]
My point is: if modules want to work with each other's data they should do it using a well defined api, not by direct joins.

This issue is not about removing the overall support for referred applications. MOST is even going to extend this support in future. But I think allowing to define joins to "foreign" entities promotes bad practice...

**Comment by Portugao** [comment]
Ok. Then I agree to delete the support for joins.

**Comment by craigh** [comment]
agree that direct joins should not be supported between entities from different modules (except core modules)

**Comment by Kaik** [comment]
I'm not using MOST but I have investigated some time ago how Symofny deals with bundle to bundle connections/integrations basically it is good to have "low-level objects connection - Doctrine layer" but hard coded connections are bad so this is what I have found. Maybe it will be useful http://symfony.com/doc/current/doctrine/resolve_target_entity.html
