### ISSUE TITLE
one2many Relation, editType ACTIVE_NONE_PASSIVE_EDIT, Unable to find template

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1040]
System: Zikula 1.4.6 (aktueller Release) und MOST 0.7.4 (stets aktuell dank Staging Updates!)
Problem: Modul mit zwei Entitäten, one2many Relation, editType ACTIVE_NONE_PASSIVE_EDIT, useAutoCompletion ONLY_SOURCE_SIDE, bidirectional true, führt zur Fehlermeldung:

Unable to find template "@...Module/AuthorChoice/includeSelectOne.html.twig" (looked into: ...httpdocs/modules/...Module/Resources/views)

Die eigentlich benötigte Datei "includeSelectEditOne.html.twig" existiert im Ordner, wird aber an dieser Stelle des Workflows nicht aufgerufen. Ich habe eine Kopie der vorhandenen Datei zur fehlenden includeSelectOne.html.twig umbenannt, und die Fehlermeldung blieb aus, jedoch war das Modul damit nicht funktionsfähig.

Ich habe außerdem getestet: eins-zu-viele und viele-zu-viele Relationen, bidirectional true und false (letzteres brauche ich eigentlich), allen vorhandenen Edit Types:
1) Ohne "Unable to find template" Fehlermeldung funktioniert es für mich nur mit editType ACTIVE_EDIT_PASSIVE_EDIT
2) Bidirectional "false" führt bei mir zu einer Fehlermeldung beim Speichern und Generieren (bidirektional ist für meine Anwendung leider nicht sinnvoll)
3) Das Selektieren von Werten der Quell-Entität aus der Ziel-Entität heraus funktioniert für mich auch mit ACTIVE_EDIT_PASSIVE_EDIT nicht ohne Tücken: Der selektierte Wert wird nach der Selektion nicht mehr angezeigt, dann aber doch gespeichert = Kontrollverlust beim Anwender  :-) 
4) Selektieren mit Auto Completion erfordert die Eingabe von 2 oder mehr Buchstaben, vorher sieht man nichts. Für mich wäre es sinnvoll, wenn schon vor einer Eingabe Werte der Quell-Entität angezeigt würden: Wenn ein Anwender sich bei Auto Completion vertippt, findet er einen bereits vorhandenen Wert nicht und kreiert ihn dann wohl ein zweites Mal.

Hier das funktionierende Modul:

application "Library" {
    vendor "Muster"
    author "muster"
    email "muster@mann.de"
    url "http://www.mann.de"
    prefix "must"
    entities {
        entity "entity" leading {
            nameMultiple "entities"
            displayPattern "#entityTitle#"
            fields {
                string "entityTitle"
            }
            actions {
                mainAction "Index",
                viewAction "View",
                displayAction "Display",
                editAction "Edit"
            }
        },
        entity "author" {
            nameMultiple "authors"
            displayPattern "#author#"
            fields {
                string "author"
            }
            actions {
                mainAction "Index",
                viewAction "View",
                displayAction "Display",
                editAction "Edit"
            }
        }
    }
    relations {
        one2many {
            source "author"
            sourceAlias "author"
            target "entity"
            targetAlias "entity"
            useAutoCompletion ONLY_SOURCE_SIDE
            editType ACTIVE_EDIT_PASSIVE_EDIT
        }
    }
}

Hier das ursprüngliche Modul:

application "LibraryOld" {
    vendor "Muster"
    author "muster"
    email "muster@mann.de"
    url "http://www.mann.de"
    prefix "must"
    entities {
        entity "author" leading {
            nameMultiple "authors"
            displayPattern "#lastName#"
            fields {
                string "lastName"
            }
            actions {
                mainAction "Index",
                viewAction "View",
                displayAction "Display",
                editAction "Edit"
            }
        },
        entity "authorChoice" {
            nameMultiple "authorChoices"
            displayPattern "#lastName#"
            fields {
                string "lastName"
            }
            actions {
                mainAction "Index",
                viewAction "View",
                displayAction "Display",
                editAction "Edit"
            }
        }
    }
    relations {
        one2many {
            source 
            "authorChoice"
            sourceAlias "authorChoice"
            sourceField "lastName"
            target "author"
            targetAlias "author"
            targetField "lastName"
            useAutoCompletion ONLY_SOURCE_SIDE
        editType ACTIVE_NONE_PASSIVE_EDIT
        }
    }
}

**Comment by Guite** [comment]
Hallo Thilo,

> Unable to find template "@...Module/AuthorChoice/includeSelectOne.html.twig" (looked into: ...httpdocs/modules/...Module/Resources/views)

An welcher Stelle tritt der Fehler auf? Wenn man einen bestehenden Author bearbeitet?

> bidirektional ist für meine Anwendung leider nicht sinnvoll

Wenn Du die Quelle auf Seite des Ziels wählen möchtest, brauchst Du bidirektional. Sonst kennt das Ziel die Quelle schlicht nicht. Wenn also z. B. 1 Person mehrere Adressen hat und diese Relation unidirektional ist, dann ist einer Adresse die Person, welcher sie zugeordnet ist, nicht bekannt. Bei unidirektionalen Relationen ist eine Bearbeitung also nur auf Quellseite möglich. Vielleicht wäre es daher überlegenswert, aus OneToMany eine ManyToOne-Beziehung in umgekehrter Richtung zu machen.

> Für mich wäre es sinnvoll, wenn schon vor einer Eingabe Werte der Quell-Entität angezeigt würden

Das klingt für mich so, als wäre für Dich #982 interessant: da geht es darum, die Funktion des "inline editings" vom AutoCompletion zu entkoppeln und auch für normale Relationen (Dropdown-Listen) nutzbar zu machen.

**Comment by ThiloWitt** [comment]
Hallo Axel,

das Template-Problem tritt jetzt nicht mehr auf, hast du etwas bei MOST 
geändert? Darüber hinaus habe ich bemerkt, dass andere Fehlermeldungen, 
die nach Neuinstallation geänderter MOST Modulen weiterhin auftreten, 
mit einen Theme-Wechsel verschwinden (in meiner Test-Instanz ist kein 
Caching eingestellt). Ich habe derweil das Modul weiterentwickelt und 
bin auf einige andere Probleme gestoßen, an denen ich erst einmal weiter 
ausprobiere, bevor ich dich um Hilfe bitte.

Danke für deinen Hinweis bezüglich bidirektional.

Ja, #982 <https://github.com/Guite/MostGenerator/issues/982> ist für 
mich interessant. Es wäre zudem schön, wenn Editieren von related items 
ohne modal-window innerhalb des Editors der Hauptidentität ginge.

Danke,
Thilo


Am 08.05.2017 um 12:44 schrieb Axel Guckelsberger:

**Comment by Portugao** [comment]
Hallo Thilo,
ich habe die Erfahrung gemacht, dass bei Neuinstallation neuer Modulversionen oft ein Löschen des Cache (Ordner 'app/cache/dev' und 'app/chache/prod') notwendig ist.

**Comment by Guite** [comment]
Hallo Thilo,

> Es wäre zudem schön, wenn Editieren von related items ohne modal-window innerhalb des Editors der Hauptidentität ginge.

Das ist wohl das, was in #3 gemeint ist :-)

Ich schließe dieses Ticket. Bitte erstelle zukünftig für jedes einzelne Problem ein separates Ticket. Das erleichtert die Bearbeitung. Danke!
