### ISSUE TITLE
[1.5] Editing of item not possible

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1043]
The entity 'location' is not editable. 
I get the edit template to create a new entry, if I call the edit function.

The reason is, that there is no entry in the translation table

**Comment by Guite** [comment]
I don't think translations are related to this. I rather guess this is related to the unique slug. Probably the form handler expects the id instead. Please post the URL of the edit page.

**Comment by Portugao** [comment]
And this entity seems the only one with no entry in the translation table after saving.

**Comment by Portugao** [comment]
Have to clean up my installation; then I provide the URL. 😉

**Comment by Portugao** [comment]
Indeed, if I change the URL:
```
http://official15.homepages-mit-zikula.de/yourcity/admin/location/edit?slug=meine-location
```
to`
```
http://official15.homepages-mit-zikula.de/yourcity/admin/location/edit?id=2
```
it works.

And the entry in the translation table is only there, if I enter something into a translatalbe field; logical.
