### ISSUE TITLE
[1.5] Cannot create item for entity with sluggable field

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1044]
I have no helpful error message.
I get only the remark, that my site is not able to work with the query.

**Comment by Portugao** [comment]
Have to check the clean MOST code.

**Comment by Portugao** [comment]
Made a check with clean MOST code and I have the same. No other remark.

**Comment by Guite** [comment]
Please post the exact message you receive.

**Comment by Portugao** [comment]
Diese Seite funktioniert nicht

official15.homepages-mit-zikula.de kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500

**Comment by Guite** [comment]
Fixed. The was only caused by a core which was not up2date.
