### ISSUE TITLE
[1.5] User field - user not deletable

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1047]
I do not know, if this is an issue or a missing feature.
If I delete the name in the field, the user does not get deleted.

The field is set to not mandatory and nullable.

**Comment by Guite** [comment]
I think you mean unsetting the user reference, not really deleting the user ;-)

**Comment by Portugao** [comment]
Yes. You're right.

**Comment by Portugao** [comment]
Nice. 😄
