### ISSUE TITLE
Viele-zu-Viele-Beziehung UndefinedMethodException beim Editieren

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1048]
Eiditieren der Hauptentität funktioniert nur, solange in der Viele-zu-Viele-Beziehung keine Daten stehen. Daten für diese Beziehung lassen sich von der Hauptentität aus auch nicht verbinden. Sobald dies von der Nebenentität aus geschehen ist, gibt es beim Editieren der Hauptentität diesen Fehler:

1/1 UndefinedMethodException in AbstractAutoCompletionRelationTransformer.php line 81: Attempted to call an undefined method named "getKey" of class "Doctrine\ORM\PersistentCollection".
Did you mean to call "getKeys"?

Die Beziehung ist so definiert:

        many2many {
            source "text"
            sourceAlias "texts"
            target "entity"
            targetAlias "entities"
            useAutoCompletion ONLY_SOURCE_SIDE
            editType ACTIVE_EDIT_PASSIVE_EDIT
            refClass "TextEntity"
        }

**Comment by Guite** [comment]
> lassen sich von der Hauptentität aus auch nicht verbinden

Was heißt das? Taucht im Formular zum Bearbeiten der Quellentität keine Auswahlliste mit den Zielentitäten auf?

**Comment by ThiloWitt** [comment]
das Feld hat die Bezeichnung "Add ..." (anstelle von "Select ..." bei Eins-zu-Viele-Beziehungen) und ermöglicht das Erstellen und Selektieren von Quellentitäten, die Selektion wird jedoch nicht gespeichert.
