### ISSUE TITLE
[1.5] Uninstall get not completed

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1049]
The tables get completly deleted.
After uninstall I get this message:
```
Diese Seite funktioniert nicht

official15.homepages-mit-zikula.de kann diese Anfrage momentan nicht verarbeiten.
HTTP ERROR 500
```
and the state of the module is 2.
This issue is not new; I thought it was caused by cache and now I'm not sure.

**Comment by Guite** [comment]
In general uninstallation works. Maybe this is caused by an extension like categories integration. You might try to work out the actual error including the stack trace. Try disabling the developer toolbar by changing `env` to `prod`, but keeping `debug` set to `true`.

**Comment by Portugao** [comment]
I will do, when I uninstall again.

**Comment by Portugao** [comment]
Just uninstalled successfully, so I close this.
