### ISSUE TITLE
[1.5] Search plugin - enabling of entities

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1050]
When I'm right, there was the possibility to disable entities separatly.
At the moment one can only deactivate the complete module.

**Comment by Guite** [comment]
There never was a possibility to deactivate single entities in the Search administration or the block administration. There should be such options in the user search form though.

**Comment by Portugao** [comment]
You're right. Maybe my wish was the reason for my idea. Does it make much work to provide this?

**Comment by Guite** [comment]
It is not possible to hook into that unfortunately. Won't fix.

**Comment by Guite** [comment]
You can override the `getSearchTypes()` method of your `SearchHelper` class. It returns an array containing the supported entity types. So if you want to exclude for example "persons" you can do:

```
    /**
     * @inheritDoc
     */
    protected function getSearchTypes()
    {
        $searchTypes = parent::getSearchTypes();

        foreach ($searchTypes as $key => $searchType) {
            if ($searchType['value'] == 'person') {
                unset($searchTypes[$key]);
            }
        }

        return $searchTypes;
    }
```

**Comment by Portugao** [comment]
Sounds good. Will give it a try.
