### ISSUE TITLE
"EntityManager is closed" error when editing and trying to save an entity with populated AutoCompletion relations

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1056]
The error comes up when editing an entity with populated AutoCompletion relations. When deleting a releation, saving is possible but the deletion itself is not saved.

Symfony
Exception detected!
The EntityManager is closed.
500 Internal Server Error - ORMException 

Stack Trace

    in vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php at line 144  -
             */
            public static function entityManagerClosed()
            {
                return new self("The EntityManager is closed.");
            }
            /**

**Comment by Guite** [comment]
This happens when an exception happened during data selection (which causes the entity manager becoming closed).
Do you target Zikula 1.4 or 1.5?

**Comment by ThiloWitt** [comment]
Target is Zikula 1.4. I did not notice exceptions during data selection, but yes, it happened when trying to change related data.

**Comment by ThiloWitt** [comment]
I reinstalled the module and created and entity with all 7 related fields populated. There was nor exeception and no issue while creating the entity. The "EntityManager is closed" error came again when trying to save the entity after editing.

**Comment by Guite** [comment]
Could you mail me your model for easier reproduction?

**Comment by Guite** [comment]
Still can not reproduced, neither with ZK15 nor ZK14 targets.

Which entity type are you trying to edit when the error occurs?

**Comment by ThiloWitt** [comment]
The title entity


Am 22.05.2017 um 11:21 schrieb Axel Guckelsberger:

**Comment by ThiloWitt** [comment]
I will run a series of tests, starting with an entity with no related 
data, then adding one by one until the error occurs.


Am 22.05.2017 um 11:21 schrieb Axel Guckelsberger:

**Comment by ThiloWitt** [comment]
the error seems to come from the many2many relation. After adding keyword from below relation, the error occurs when editing. After deleting the keyword from keyword entity side, the main entity item can again be edited and saved.

        many2many bidirectional {
            source "title"
            sourceAlias "genericTitle"
            target "keyword"
            targetAlias "keywords"
            useAutoCompletion BOTH_SIDES
            editType ACTIVE_EDIT_PASSIVE_EDIT
            refClass "titleKeyword"
		},

**Comment by Portugao** [comment]
I thought, the issue with the closed entity manager was caused by my own code.
Now I'm not sure anymore.

That means , that I make the same experiences with saving an entry within a many to many relation.
If I do not select a releated item, I can save.

**Comment by Portugao** [comment]
Thx a lot, Axel. It works.
