### ISSUE TITLE
Inheritance relation issue during module installation II

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1058]
now getting:

Doctrine Exception: Catchable Fatal Error: Argument 1 passed to Doctrine\ORM\Mapping\ClassMetadataInfo::setDiscriminatorMap() must be of the type array, null given, called in /var/www/vhosts/.../httpdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php on line 249 and defined
Initialization of ...Module failed!

**Comment by Guite** [comment]
Did you clear the app cache after regeneration? How does the `@ORM\DiscriminatorMap` annotation look like? (found in the top class of the inheritance hierarchy)

**Comment by ThiloWitt** [comment]
The site runs in debug mode. Also after celearing the app cache, the issue persists. Please give me the full path to the @ORM\DiscriminatorMap annotation

**Comment by Guite** [comment]
`Vendor/YourModule/Entity/FooEntity.php` whereby `Foo` is the name of the parent entity (super class).

**Comment by ThiloWitt** [comment]
@ORM\DiscriminatorMap[{"title" = "Byblos\ByblosModule\Entity\TitleEntity", "person" = "Byblos\ByblosModule\Entity\PersonEntity"

TitleEntity is lead entity but target in the inheritance relation. Is it an issue that PersonEntity is the source but not the lead entity?

**Comment by ThiloWitt** [comment]
Now getting same error also when trying to install a module without inheritance relation:

Doctrine Exception: Catchable Fatal Error: Argument 1 passed to Doctrine\ORM\Mapping\ClassMetadataInfo::setDiscriminatorMap() must be of the type array, null given, called in /var/www/vhosts/.../httpdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php on line 249 and defined
