### ISSUE TITLE
When adding data in relations with auto completion, added related data are not automatically selected in target entity

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1060]
It would be nice if the selection could happen automatically for user conveniance. Also, without an automated selection, it is difficult to select between similar related datasets (e.g. library signatures in my project).

**Comment by Guite** [comment]
I don't understand it yet. Can you please elaborate and/or post an example?

**Comment by ThiloWitt** [comment]
1. Go to create new related content

![grafik](https://cloud.githubusercontent.com/assets/1067830/26500015/c37cabaa-4234-11e7-82cc-c2ce3c4d2063.png)

2. Save new related content

![grafik](https://cloud.githubusercontent.com/assets/1067830/26500059/ea0695d8-4234-11e7-9eaf-5890227ea885.png)

3. After saving it, the new related content does not show as selected in target entity, in this case replace the existing selection

![grafik](https://cloud.githubusercontent.com/assets/1067830/26500102/111b0848-4235-11e7-9bd7-e30a35f669b2.png)

4. There is the need to find it again

![grafik](https://cloud.githubusercontent.com/assets/1067830/26500164/3b30a64c-4235-11e7-8169-e238a6e79377.png)

5. Only now it is showing as selected, and in this case relacing the previously selected item

![grafik](https://cloud.githubusercontent.com/assets/1067830/26500206/5e64be32-4235-11e7-9b4f-65a30ed80962.png)

**Comment by Guite** [comment]
Thanks for the detailed explanation. Will check this after my holiday.

**Comment by Guite** [comment]
I think to avoid any potential confusion the automatic selection should only be done if only one result is found. For example if `autobus` already exists and `auto` is newly created then after the search process both results should just be shown. But if `something new` is newly created it could also be selected automatically.

**Comment by ThiloWitt** [comment]
Right, I think we have the same view: when creating a new related item and the related item editor closes, this newly created item should automatically show selected in the main entity's editor.

**Comment by Guite** [comment]
Changelog entry explaining how the feature works: https://github.com/Guite/MostHelp/commit/2a116314f1d43d5deeb76778c1ff002de9c2d33c
