### ISSUE TITLE
Inheritance relation issue during module installation III

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1061]
Now getting same error as in #1058 also when trying to install a module without inheritance relation:

Doctrine Exception: Catchable Fatal Error: Argument 1 passed to Doctrine\ORM\Mapping\ClassMetadataInfo::setDiscriminatorMap() must be of the type array, null given, called in /var/www/vhosts/.../httpdocs/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php on line 249 and defined

**Comment by Guite** [comment]
I did another fix 10 minutes ago https://github.com/Guite/MostGenerator/commit/cfde8179589b018c78925d241aa5a7db6b275ae3

**Comment by Guite** [comment]
staging update will be available in about 7 minutes

**Comment by ThiloWitt** [comment]
thanks, great support and progress!
