### ISSUE TITLE
Inheritance relation issue during module installation IV

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1062]
now getting:

ClassNotFoundException in PersonEntity.php line 39: Attempted to load class "Title" from namespace "Byblos\ByblosModule\Entity".
Did you forget a "use" statement for another namespace?
in PersonEntity.php line 39

**Comment by Guite** [comment]
Please post line 39 of both `modules/Byblos/ByblosModule/Entity/PersonEntity.php` and `modules/Byblos/ByblosModule/Entity/Base/PersonEntity.php`.

**Comment by ThiloWitt** [comment]
line 38 ... of modules/Byblos/ByblosModule/Entity/PersonEntity.php:

class PersonEntity extends BaseEntity
{
    // feel free to add your own methods here
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @Assert\Type(type="integer")
     * @Assert\NotNull()
     * @Assert\LessThan(value=1000000000)
     * @var integer $id
     */
    protected $id = 0;

modules/Byblos/ByblosModule/Entity/Base/PersonEntity.php  does not exist:

![grafik](https://cloud.githubusercontent.com/assets/1067830/26521468/47a21a46-42e9-11e7-8cec-b8031cfa4694.png)

 line 13 ... of modules/Byblos/ByblosModule/Entity/TitleEntity.php:

namespace Byblos\ByblosModule\Entity;

use Byblos\ByblosModule\Entity\Base\AbstractTitleEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for title entities.
 * @Gedmo\TranslationEntity(class="Byblos\ByblosModule\Entity\TitleTranslationEntity")
 * @ORM\Entity(repositoryClass="Byblos\ByblosModule\Entity\Repository\TitleRepository")
 * @ORM\Table(name="byblos_bybl_title",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discr")
 * @ORM\DiscriminatorMap({"title" = "Byblos\ByblosModule\Entity\TitleEntity", "person" = "Byblos\ByblosModule\Entity\PersonEntity"
})
 */
class TitleEntity extends BaseEntity
{
    // feel free to add your own methods here
}
