### ISSUE TITLE
Inheritance relation issue during module installation V

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1064]
Doctrine Exception: There is no column with name 'workflowState' on table 'byblos_bybl_person'.

 inheritance {
            source "person"
            target "title"
            strategy JOINED
        }

**Comment by Guite** [comment]
Is `title` a normal entity or a mapped super class?
Do you target Zikula 1.4 or 1.5?

**Comment by ThiloWitt** [comment]
Title is a normal entity and target is Zikula 1.4
