### ISSUE TITLE
[1.5] Plugin formatted title does not work on multilanguage sites

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1066]
Does not work with multilanguage enabled.
It returns the default. Maybe it depends on the translation is not complete?!

**Comment by Guite** [comment]
Can you provide an example?

**Comment by Guite** [comment]
ping @Portugao

**Comment by Portugao** [comment]
I will do as soon as possible.

**Comment by Portugao** [comment]
http://official15.homepages-mit-zikula.de/yourcity/branch/1

**Comment by Portugao** [comment]
Hope to be able to do coming week.....

**Comment by Guite** [comment]
Can you please post an example so that I can check this before the 0.7.5 release?

**Comment by Portugao** [comment]
Hmmhm....not so easy.....

**Comment by Guite** [comment]
I need:

- display pattern from the model
- pointer what is wrong (e.g. example expected vs. example actually displayed)

**Comment by Portugao** [comment]
Hi Axel,

I checked with the new generated Blogging Module.
You can close this, because the issue is gone.
Thx.

**Comment by Guite** [comment]
cool
