### ISSUE TITLE
Workflow editing broken

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#1071]
Using 0.7.4 on Mac targeting 15dev.

In a generated extension, in Settings, trying to look at the workflow editing is broken.

* The link "http://localhost/modulename/editor/index?workflow=modulename_enterprise" link opens up a new browser tab in Firefox, which seems like a very odd UI choice.  I suspect this isn't intended

* More importantly the rendered page is only text, no wrapper or styles, html source begins with '<div class="container-fluid">".  Nothing therein is functional.

So I think this is supposed to be a popup that's not getting any Zikula wrapped around it.

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/commit/9fd66db3b44d4e89905644dde2de23adb2da3ccf
