### ISSUE TITLE
Support FormAwareHook and non-persisted hooks

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#1072]
See https://github.com/zikula/core/tree/1.5/src/docs/Hooks

**Comment by craigh** [comment]
you'll also want to support non-persisted hooks.

**Comment by Guite** [comment]
https://github.com/zikula-modules/Pages/compare/3218ad6f01...098379c6c4
https://github.com/zikula-modules/FooHookModule/compare/0d4872fd68...c3e5157ced

**Comment by craigh** [comment]
the pages changes are incomplete. they do not include migration to non persisted hooks yet

**Comment by Guite** [comment]
https://github.com/zikula/core/compare/1dee9e2142...c34860cf29
https://github.com/zikula/core/compare/c34860cf29...79d4448a93

**Comment by Guite** [comment]
https://github.com/zikula/core/compare/1dee9e2142...459c9868df4694c8775f3a47ab83b965252a9a47
