### ISSUE TITLE
Install leads into error message

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1077]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version |  latest git
| Operating System       | Windows
| Zikula Target in Model | ZK14
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
Successful install and redirect to extensions module.

### Actual behavior
I get this error after install:
```
Attempted to call an undefined method named "setCategory_Id" of class "Zikula\CategoriesModule\Entity\CategoryRegistryEntity". Did you mean to call e.g. "getCategory", "getCategory_Id" or "setCategory"?
```

### Steps to reproduce
Take a fresh with MOSTgenerated module, in this case Image (https://github.com/Portugao/Image).

The tables of the module are created, the state of the module is uninstalled.

**Comment by craigh** [comment]
maybe try to target 1.5?

**Comment by Portugao** [comment]
Would like this module is for 1.4.x.

**Comment by craigh** [comment]
Then I don't think it will run on 1.5 ;-)

**Comment by Guite** [comment]
Either use `ZK14` with Zikula 1.4.x or `ZK15` for Zikula 1.5.
There is no guarantee that `ZK14` will run flawlessly with 1.5.

**Comment by Guite** [comment]
I can do something about it. One moment...

**Comment by craigh** [comment]
@Guite if this is a BC break in the Core, then you didn't note this. If it **is**, I'd prefer to add those methods back to 1.5 and deprecate them (e.g. `setCategory_Id`, etc)

**Comment by Guite** [comment]
@Portugao I added a change in https://github.com/Guite/MostGenerator/commit/fed244e8d29f6b9d6aa703652d0f10666e010546 so installing a `ZK14` target app should work with 1.4.x and 1.5 now. But there may other differences with regards to categories.

@craigh The change was introduced by your PR here: https://github.com/zikula/core/pull/3494/files#diff-b699a1c19a6f474123820abfd9b94827

**Comment by craigh** [comment]
> The change was introduced by your PR here

hmmm 🤔 so it is...

**Comment by Guite** [comment]
Added an issue about it https://github.com/zikula/core/issues/3661

**Comment by Portugao** [comment]
Thx for the fix, @Guite .
In the past there was the information that the only difference between 1.4. and 1.5. would be the handling of workflows and a 1.4 module would run under 1.5.
I think it's relevant for module developers, that a module does not work only in one series.

**Comment by Guite** [comment]
As said we already added a core issue about it.

**Comment by Portugao** [comment]
Yes, I noticed, Thx for that.
