### ISSUE TITLE
Filtering for not standard language does not find the relevant items

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1083]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK15
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
To get the entries for the not standard language, in my case english.

### Actual behavior
The view is empty, although I have one entry with 'locale' field = 'en'

### Steps to reproduce
Take the repository of Blogging module and create an entry with locale = en.

**Comment by Guite** [comment]
Just investigated: the function is working as expected.
