### ISSUE TITLE
Protected translator in base filter hook causes error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1089]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK15
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
Seeing the page for hooks of a module after calling the link hooks in a module

### Actual behavior
get an error 'call on non-object'

### Steps to reproduce
Take the repository of Video and try to hook a module to another

**Comment by Guite** [comment]
Stack trace?

**Comment by Portugao** [comment]
Only this:
```
FatalErrorException in AbstractFilterHooksProvider.php line 64:
Error: Call to a member function __() on null
```

**Comment by Portugao** [comment]
Sorry, I had a typo in my issue.
