### ISSUE TITLE
Last build cannot get started

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1090]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | [Windows 8.1

### Expected behavior
Complete start of MOST

### Actual behavior
MOST opens and after 5 seconds the window of MOST get closed, the modulestudio.exe is still running

### Steps to reproduce
Try to start MOST under win 8.1 with the actual build.

**Comment by Guite** [comment]
Your description is not clear: is this about starting MOST or starting the generator inside MOST?

**Comment by Portugao** [comment]
MOST. Changed my description, sorry.

**Comment by Guite** [comment]
Can you try renaming the `MostWorkspace` folder, e.g. to `MostWorkspace_backup`? Does this change anything?

**Comment by Portugao** [comment]
No, strange.

**Comment by Guite** [comment]
Will try to reproduce later.

**Comment by Portugao** [comment]
Ok.

**Comment by Guite** [comment]
This is fixed in the latest product build.

**Comment by Portugao** [comment]
Thx a lot.
