### ISSUE TITLE
sirius diagram editing error

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#1092]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [0.7.5 staging
| Operating System       | Windows
| Zikula Target in Model | ZK14

### Expected behavior
the normal view should be available

### Actual behavior
![grafik](https://user-images.githubusercontent.com/935250/28747091-4bc999c0-7497-11e7-9672-24e428670f82.png)

````
null
org.eclipse.e4.ui.workbench
Error
Sat Jul 29 19:48:40 CEST 2017
Problems occurred when invoking code from plug-in: "org.eclipse.e4.ui.workbench".

java.lang.NullPointerException
	at de.guite.modulestudio.ui.sirius.SiriusTabBarCustomiser.customiseTabbar(SiriusTabBarCustomiser.xtend:24)
	at de.guite.modulestudio.ui.sirius.SiriusSelectionListener.selectionChanged(SiriusSelectionListener.xtend:33)
        ...
````

**Comment by Guite** [comment]
Fixed in latest build (Jenkins is working on it).

**Comment by rallek** [comment]
not fixed for me :-(

**Comment by Guite** [comment]
please provide the latest stack trace, thanks

**Comment by rallek** [comment]
Yesterday I made a new MostWorkspace. And today after a restart everything is fine. So something went wrong yesterday. Bug has gone today.
