### ISSUE TITLE
Background of rows in tables - sesond row has not

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1093]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK15
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
The table in the view template has alternating rows concerning the background

### Actual behavior
First row has a background, the second one not.
I'm not sure if this is intended?

### Steps to reproduce
Have a look with another background of relevant containers

**Comment by Guite** [comment]
The table has the `table-striped` class which cares for the alternating backgrounds. See [here](http://getbootstrap.com/css/#tables-striped).

What exactly is wrong about that?

**Comment by Portugao** [comment]
I didn't know if there is something wrong. Now I have seen, that it is intended, every second row has no background.
So I close this.
