### ISSUE TITLE
Problems with translatable slug field, only german part (active language) get saved

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1094]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | 1.0.1
| Operating System       | Windows
| Zikula Target in Model ZK15
| Zikula Version         | [1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
Creating an item with translatable slug field results in 2 filled slug fields with the enterd strings.

### Actual behavior
Only the german part of the relevant slug fields results in an entry in the database.

### Steps to reproduce
Take the actual repository of Blogging and try to create an item. Enter strings into the permalink field in the german and english part and save.

**Comment by Portugao** [comment]
Slug is editable and unique.
The slug field is not the pattern field.

**Comment by Guite** [comment]
Isn't this the same as https://github.com/Guite/MostGenerator/issues/771 ?

**Comment by Portugao** [comment]
Indeed, is the same.
I'm very confused about that.
