### ISSUE TITLE
Typo in AbstractControllerHelper

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1096]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK15
| Zikula Version         | [1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
No such issue

### Actual behavior

```
FatalErrorException in AbstractControllerHelper.php line 327:
Parse Error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)
```
### Steps to reproduce
Not needed I think.

**Comment by Guite** [comment]
Can you please post the affected code part. thank you…
