### ISSUE TITLE
Symfony error, concerning hooks?

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1097]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | 1.0.1
| Operating System       | Windows
| Zikula Target in Model | ZK15
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
Lodaing of the display view.

### Actual behavior
```
[Semantical Error] The annotation "@ORM\Table" in class MU\FilesModule\Entity\HookAssignmentEntity was never imported. Did you maybe forget to add a "use" statement for this annotation?
```
### Steps to reproduce
Take the lastest repository of Files, create a collection and call the display in backend or frontend.

**Comment by Portugao** [comment]
If I add the use statement from fix, I get:
```
Class "MU\FilesModule\Entity\HookAssignmentEntity" sub class of "MU\FilesModule\Entity\Base\AbstractHookAssignmentEntity" is not a valid entity or mapped super class.
```

**Comment by Portugao** [comment]
New issue?

**Comment by Guite** [comment]
See https://github.com/Guite/MostGenerator/commit/7e4c960e147ae08af0e1bb894e1ab3b023011538

**Comment by Portugao** [comment]
👍
