### ISSUE TITLE
Missing template

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1099]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK15
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Expected behavior
No such error message

### Actual behavior
```
Unable to find template "@MUSoundModule/Album/Admin/includeSelectEditMany.html.twig" (looked into: F:\Arbeit\XAMPP\htdocs\zik15\modules\MU\SoundModule/Resources/views).
 ```

### Steps to reproduce
Not needed, I think. The template is not there.
1:n relation, bidirectional

**Comment by Portugao** [comment]
Wrong path, sorry:
The files are in a Admin folder. This folder is in MU\SoundModule\

**Comment by Portugao** [comment]
Or the calling is wrong?!
I get the same error message.

**Comment by Guite** [comment]
How does the include statement looks like (paste entirely)?
How does the actual path look like where the file is placed?

**Comment by Portugao** [comment]
```
        {{ include(
            '@MUSoundModule/Album/includeSelectEditMany.html.twig',
            {group: 'collection', alias: 'album', aliasReverse: 'collection', mandatory: false, idPrefix: 'soundCollection_Album', linkingItem: collection, displayMode: 'choices'}
        ) }}
```

**Comment by Portugao** [comment]
/modules/MU/SoundModule/Admin/Resources/views/Album

**Comment by Guite** [comment]
fixed in https://github.com/Guite/MostGenerator/commit/ea385b4441ee4da21caadb2f10b42d612d5d7e86
