### ISSUE TITLE
News cannot install

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#1103]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | unknown
| Operating System       | MacOS
| Zikula Target in Model | ZK15 I think
| Zikula Version         | 2.0.x
| PHP Version            | 5.6.30

### Expected behavior
module installation

### Actual behavior

> Doctrine Exception: No identifier/primary key specified for Entity "Zikula\NewsModule\Entity\ArticleAttributeEntity" sub class of "Zikula\NewsModule\Entity\Base\AbstractArticleAttributeEntity". Every Entity must have an identifier/primary key.
Initialization of ZikulaNewsModule failed!

### Steps to reproduce
- clone News module
- switch to 5.0-prototype branch
- refresh extensions module
- click install News

**Comment by Guite** [comment]
Looks like a regression in the core.

`AbstractArticleAttributeEntity extends AbstractEntityAttribute`

https://github.com/zikula-modules/News/blob/5.0-prototype/Entity/ArticleAttributeEntity.php
https://github.com/zikula-modules/News/blob/5.0-prototype/Entity/Base/AbstractArticleAttributeEntity.php
https://github.com/zikula/core/blob/2.0/src/lib/Zikula/Core/Doctrine/Entity/AbstractEntityAttribute.php

`AbstractEntityAttribute` has a primary key:
```php
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     * @var integer
     */
    private $id;
```

I do not see a wrong implementation here. It follows this:
https://github.com/zikula/core/blob/2.0/src/docs/Doctrine/AbstractEntityAttribute.md

Also I remember attributes were always working in 1.x. Can you tree if installation succeeds in 1.5?

Side note: does News really need attributes?

**Comment by craigh** [comment]
> Side note: does News really need attributes?

unknown, but seems unlikely. Why did you add it to the model?

**Comment by Guite** [comment]
> Why did you add it to the model?

can't remember :older_man:

**Comment by craigh** [comment]
This is a core problem
