### ISSUE TITLE
'Assigned' items does not get assigned

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1110]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
Entry in the hook assignment table

### Actual behavior
The item get saved without related entry in the hook table

### Steps to reproduce
Take actual repository of Comments and hook it to Pages. Call the standard page of Pages and create in item in Comments.

**Comment by Guite** [comment]
> The item get saved without related entry in the hook table

> create in item in Comments.

Please elaborate. Which are the concrete steps you executed? Did you create a new comment using a modal window? For saving a hook assignment you need to select an entry in the auto completion field result list. You might keep the JS console opened to see whether an error occurs during attaching the comment using ajax.

**Comment by Portugao** [comment]
Hmmhmm...there is an auto complete error:
```
Uncaught TypeError: jQuery(...).autocomplete is not a function
    at Object.<anonymous> (MUCommentsModule.AutoCompletion.js:233)
    at Function.each (jquery.min.js:2)
    at mUCommentsInitRelationItemsForm (MUCommentsModule.AutoCompletion.js:226)
    at welcome-to-pages-content-manager:808
```

**Comment by Portugao** [comment]
The autocomplete error is gone.
Where I should get the autocomplete field? I get a modal window clicking create and no autocomplete field.

**Comment by Guite** [comment]
There should be a link `Attach comment`. After clicking this an auto completion field should appear. If comments have an edit action, a button `Create new comment` should be next to this field.

Can you post a screenshot?

**Comment by Portugao** [comment]
Atach comment is there.
![comments_in_pages_1](https://user-images.githubusercontent.com/493707/29240624-1aab6b8e-7f69-11e7-9486-b20180830cd2.jpg)

After click on this:
![comments_in_pages_2](https://user-images.githubusercontent.com/493707/29240627-2aabd406-7f69-11e7-9811-55b5b20b4235.jpg)

**Comment by Guite** [comment]
Please inspect the create button and check why the auto completion field next to it is not shown.

**Comment by Portugao** [comment]
The autocomplete field is unvisible by class 'hidden'.

And I'm confused about the functionality of the ui hook. I would like to have a form to enter a new item?!
Maybe there is something wrong because of my module containing a self-relation?!

**Comment by Guite** [comment]
> And I'm confused about the functionality of the ui hook.

As described in Slack: the generator provides a generic "attach everything to everything" functionality using auto completion and modal inline creation. Any other functionality is part of the specific module.
