### ISSUE TITLE
MOST Modules don't install under Zikula 2.0.0.

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1113]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.0.1]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20 and ZK15]
| Zikula Version         | [2.0.0]
| PHP Version            | [7.x]

### Expected behavior
Module installs

### Actual behavior
Module installation fails:
https://.../extensions/module/list returns a blank page
in database table "modules", the modul shows state "7"

### Steps to reproduce
Export MOST module for target core version ZK20 (same issue with ZK15), upload it into the Zikula 2.0.0 modules folder, go to Extensions, find the module in the list and click on Install. The issue is happens with any module, I have also tried with below MOST sample module (module name: "MeinProjektModule")

application "MeinProjekt" {
    vendor "..."
    author "..."
    email "..."
    url "..."
    prefix "meinpr"
    generatorSettings {
        settingsContainer "Settings"
        targetCoreVersion ZK15             // this line does not exist when target ZK20 is selected
    }
    entities {
        entity "person" leading {
            nameMultiple "persons"
            displayPattern "#lastName#, #firstName#"
            fields {
                string "lastName",
                string "firstName" {
                    mandatory false
                }
            }
            actions {
                mainAction "Index",
                viewAction "View",
                displayAction "Display",
                editAction "Edit"
            }
        },
        entity "address" {
            nameMultiple "addresses"
            displayPattern "#zipCode# #city#"
            fields {
                string "zipCode",
                string "city"
            }
            actions {
                mainAction "Index",
                viewAction "View",
                displayAction "Display",
                editAction "Edit"
            }
        }
    }
    relations {
        one2many {
            source "person"
            sourceAlias "person"
            target "address"
            targetAlias "addresses"
        }
    }
}

**Comment by Portugao** [comment]
Same for me under 1.5, seems to depend on invalid forms.yml file:
```
FileLoaderLoadException in FileLoader.php line 133:
The file "F:\Arbeit\WAMPP\wamp64\www\zik15\modules\MU\TestAppModule\DependencyInjection\Base/../../Resources/config\forms.yml" does not contain valid YAML in F:\Arbeit\WAMPP\wamp64\www\zik15\modules\MU\TestAppModule\DependencyInjection\Base/../../Resources/config\forms.yml (which is being imported from "F:\Arbeit\WAMPP\wamp64\www\zik15\modules\MU\TestAppModule\DependencyInjection\Base/../../Resources/config\services.yml").
```

**Comment by Portugao** [comment]
```
Unable to parse at line 12 (near "mu_testapp_module.form.handler.common").
```
There is a : missing.

**Comment by Portugao** [comment]
I have another typo in the abstract installer class.

**Comment by Portugao** [comment]
```
       $conn->update('hook_area', ['owner' => 'MUTestAppModule'], ['owner' => 'TestApp'];
```
If I'm right, there is a ) missing before the ; Line 198 and 218.

**Comment by Guite** [comment]
Thanks, fixed in db16701583d42200918f33d52bfa366395f61f1b

**Comment by Portugao** [comment]
👍 With this fixes the install works. 😄

**Comment by ThiloWitt** [comment]
Thanks!
