### ISSUE TITLE
Error when trying to create an item in a ZK20 module

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1115]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.0.1]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.0]
| PHP Version            | [7.x]

### Expected behavior
Input form opens

### Actual behavior
Input form does not open and error message is displayed:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 

### Steps to reproduce
Any MOST ZK20 module installed in Zikula 2.0.0

**Comment by Guite** [comment]
Please ensure that `debug` is set to `true` in `/app/config/custom_parameters.yml`. You should see an error message and a stack trace then.

**Comment by ThiloWitt** [comment]
When `debug` is set to `true` I immediately get this error:

![grafik](https://user-images.githubusercontent.com/1067830/29316814-9a1cc11c-81c9-11e7-8e78-5ba793fc4015.png)

**Comment by Guite** [comment]
This is unrelated to the generator, but an error from the Symfony kernel, see https://github.com/symfony/symfony/blob/3.3/src/Symfony/Component/HttpKernel/Kernel.php#L321

@craigh any idea?

**Comment by craigh** [comment]
the error is unrelated to the core afaics. It looks like a misconfiguration of the server.

**Comment by ThiloWitt** [comment]
Is composer.json part of the 2.0.0 distribution? If yes, what is the path to it?

**Comment by craigh** [comment]
no. in the actual distribution there is no composer file

**Comment by ThiloWitt** [comment]
I am puzzeled about this error as it about a file that should not be there. Can you tell me what below message means?:
Warning: file_exists(): open_basedir restriction in effect. File(/var/www/vhosts/.../subdomains/composer.json) is not within the allowed path(s): (/var/www/vhosts/.../subdomains/com/httpdocs/:/tmp/:/var/www/vhosts/.../subdomains/com/)

**Comment by craigh** [comment]
OK - this is a symfony error. The kernel is trying to locate its own "ProjectDir" and uses a path relative to the `composer.json` file to do it. Since Zikula doesn't ship with one, this is not possible and so it fails.

**Comment by craigh** [comment]
try this:

edit `\ZikulaKernel` (in the app dir)

add this method:

    public function getProjectDir()
    {
        return dirname(__DIR__ . '/../');
    }

**Comment by craigh** [comment]
just modified that...

**Comment by ThiloWitt** [comment]
Thanks, afer adding the method I get:


(2/2)                                         ContextErrorException                                                                          Notice: Undefined index:
--
in IntlDateFormatter.php (line 618)
at IntlDateFormatter->getDefaultPattern()in IntlDateFormatter.php (line 511)
at IntlDateFormatter->setPattern(null)in IntlDateFormatter.php (line 161)

... many lines follow and the same again:


(1/2)                                         ContextErrorException                                                                          Notice: Undefined index:
--
in IntlDateFormatter.php (line 618)
at IntlDateFormatter->getDefaultPattern()in IntlDateFormatter.php (line 511)
at IntlDateFormatter->setPattern(null)in IntlDateFormatter.php (line 161)

.... again many lines follow

**Comment by craigh** [comment]
you must install the Intl php  component

**Comment by craigh** [comment]
so this won't work...

> add this method:

    public function getProjectDir()
    {
        return dirname(__DIR__);
    }

it causes other problems.

I don't know what the real problem is I guess.

**Comment by Guite** [comment]
> OK - this is a symfony error. The kernel is trying to locate its own "ProjectDir" and uses a path relative to the `composer.json` file to do it. Since Zikula doesn't ship with one, this is not possible and so it fails.

I do not understand why we never ran into that error yet though.

**Comment by craigh** [comment]
> I do not understand why we never ran into that error yet though.

me either. I also don't understand why overriding the method (as I suggested above) causes the core to break.

**Comment by ThiloWitt** [comment]
what is next?

**Comment by Guite** [comment]
Try putting https://github.com/zikula/core/blob/2.0/composer.json into your Zikula root folder.

**Comment by ThiloWitt** [comment]
This seems to help, the composer.json issue does not come up anymore. But the initial error when trying to open an input form is still there and in debug mode shows:

Unable to find a workflow for class "Byblos\ByblosModule\Entity\TitleEntity".

    Exception Logs 1 Stack Trace 

Symfony\Component\Workflow\Exception\ InvalidArgumentException
in vendor/symfony/symfony/src/Symfony/Component/Workflow/Registry.php (line 61)
Registry->get(object(TitleEntity)) in modules/ByblosModule/Helper/Base/AbstractWorkflowHelper.php (line 153)

         *
         * @return array List of available workflow actions
         */
        public function getActionsForObject(EntityAccess $entity)
        {
            $workflow = $this->workflowRegistry->get($entity);
            $wfActions = $workflow->getEnabledTransitions($entity);
            $currentState = $entity->getWorkflowState();
        
            $actions = [];
            foreach ($wfActions as $action) {

**Comment by Guite** [comment]
Usually you should put a module into `modules/<vendor>/<moduleName>` and not into `modules/<moduleName>`.

But you can also fix this by applying this patch: https://github.com/zikula/core/pull/3768/files

**Comment by ThiloWitt** [comment]
Thanks, with the patch applied I can open forms normally.
