### ISSUE TITLE
No search result

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1117]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
A result

### Actual behavior
No result

### Steps to reproduce
Take a fresh generated module, enter one item and search for a string in the title or in another string or text field.

**Comment by Guite** [comment]
Which module?

**Comment by Guite** [comment]
[TestApp.zip](https://github.com/Guite/MostGenerator/files/1234250/TestApp.zip)

**Comment by Portugao** [comment]
Sorry?!

**Comment by Portugao** [comment]
I have still this problem.
I searched in users module for a user, that works.
I searched in my test app for a page, no result.

**Comment by Portugao** [comment]
@Guite , for me this issue is still there.

**Comment by Guite** [comment]
Please mail me the model with further instructions what you did in order to reproduce the problem.
