### ISSUE TITLE
No index controller in the model results in route error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1118]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
no error

### Actual behavior
```
Unable to generate a URL for the named route "mutransportmodule_field_adminindex" as such route does not exist.
```

### Steps to reproduce
After handle selected entries, I get this error. The field entity has no index controller in the model, so also in the controller file.

**Comment by Portugao** [comment]
If the index controller is required, the generator should show an error.

**Comment by Guite** [comment]
Can you please post a stack trace?

**Comment by Portugao** [comment]
👍

**Comment by Portugao** [comment]
Thx.
