### ISSUE TITLE
Workflow class not found

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1120]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.0]
| PHP Version            | [5.6.x]

### Expected behavior
Input form opens

### Actual behavior
Error message:
Unable to find a workflow for class "Byblos\ByblosModule\Entity\TitleEntity".

Exception Logs Stack Trace 

Symfony\Component\Workflow\Exception\ InvalidArgumentException
in vendor/symfony/symfony/src/Symfony/Component/Workflow/Registry.php (line 61)
Registry->get(object(TitleEntity)) in modules/Byblos/ByblosModule/Helper/Base/AbstractWorkflowHelper.php (line 153)

     *
     * @return array List of available workflow actions
     */
    public function getActionsForObject(EntityAccess $entity)
    {
        $workflow = $this->workflowRegistry->get($entity);
        $wfActions = $workflow->getEnabledTransitions($entity);
        $currentState = $entity->getWorkflowState();
    
        $actions = [];
        foreach ($wfActions as $action) {

**Comment by Guite** [comment]
> But you can also fix this by applying this patch: https://github.com/zikula/core/pull/3768/files

Do you have that?
Did you clear the cache?

> Steps to reproduce

??

**Comment by Guite** [comment]
Did you uninstall the module from `modules/ByblosModule` and install it again after moving it to `modules/Byblos/ByblosModule`? Otherwise your database may contain obsolete values in the `bundles` and/or `modules` table. Please verify that the rows in these tables contain the updated pathes. Afterwards clear `/var/cache/` and try again.

**Comment by ThiloWitt** [comment]
I have done a complete reinstall of Zikula 2.00 from Jenkins (#16), which has the patch, loaded the module into modules / Byblos / ByblosModule, and also loaded composer.json into the root folder (without it, even the optional system modules (profle etc.) do not install). The site runs in debug mode, and I deleted the cache before installing the module. The issue should be reproducable with any MOST module.

**Comment by Guite** [comment]
I just installed 2.0.1 from Git (core 2.0 branch) and a MOST module. I can click on the "create xy" button and the input form shows without problems.

Can you please check `Resources/workflows/*.yml` in your generated module? There should be one which contains `Byblos\ByblosModule\Entity\TitleEntity` in the `supports` section.

Can you also send me the model (mostapp file) by mail?

**Comment by ThiloWitt** [comment]
I have regenerated the module with the newst MOST update and installed it again, now it works, thanks!
