### ISSUE TITLE
Detailed view of entity with existing one-to-many relations throws Twig Error

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1121]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.x-git]
| PHP Version            | [5.6.x]

### Expected behavior
Clicking on "Details" of an entity item with existing one-to-many relation(s) opens the detailed view of that item.

### Actual behavior
Below error message is thrown in debug mode. The issue does not occur when there are no related items created, yet.

Symfony Exception
Twig_Error_Runtime
HTTP 500 Internal Server Error
Variable "context" does not exist.

    Exception Logs Stack Trace 

Twig_Error_Runtime
in modules/Byblos/ByblosModule/Resources/views/Title/includeDisplayItemListMany.html.twig (line 11)

            - 'hookDisplayEdit': list of titles assigned using an UI hook (edit template)
            - 'hookDisplayDelete': list of titles assigned using an UI hook (delete template)
    #}
    {% set hasAdminPermission = hasPermission('ByblosByblosModule:Title:', '::', 'ACCESS_EDIT') %}
    {% set hasEditPermission = hasPermission('ByblosByblosModule:Title:', '::', 'ACCESS_EDIT') %}
    {% if context != 'display' %}
        <h3>{{ __('Assigned titles') }}</h3>
        {% if context == 'hookDisplayView' and hasEditPermission %}
            {% set entityNameTranslated = __('title') %}
            {{ pageAddAsset('stylesheet', asset('jquery-ui/themes/base/jquery-ui.min.css')) }}
            {{ pageAddAsset('stylesheet', asset('bootstrap-jqueryui/bootstrap-jqueryui.min.css')) }} 

### Steps to reproduce
Module with one-to-many relation and existing related item

**Comment by Guite** [comment]
Does the title entity has `uiHooksProvider` set to `true`?
How does the `include()` statement looks like in the `display.html.twig` template for the detail view?

**Comment by ThiloWitt** [comment]
Yes, the title entity has uiHooksProvider set to true.

Title entity:
    {{ include('@ByblosByblosModule/Helper/includeStandardFieldsDisplay.html.twig', {obj: title}) }}

Author entity:
    {{ include('@ByblosByblosModule/Helper/includeStandardFieldsDisplay.html.twig', {obj: author}) }}

**Comment by craigh** [comment]
odd syntax for `{{ include() }}`

typical: `{{ include('@ZikulaFooModule/Bar/includeStandardFieldsDisplay.html.twig', {obj: author}) }}`

**Comment by Guite** [comment]
He actually posted it correctly (`{{ include('@ByblosByblosModule/Helper/includeStandardFieldsDisplay.html.twig', {obj: title}) }}`), but without code tags GitHub does not display it correctly.

Also I meant another template, but doesn't matter, since I found the typo already.

**Comment by ThiloWitt** [comment]
thanks, working now
