### ISSUE TITLE
UI Hook - Unclear, what happens

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1122]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
Feedback when I enter something into the autocomplete field and when I click on the found item

### Actual behavior
If I enter something, I get no feedback, what happens. Also I get no feedback, when I click on a found item.

### Steps to reproduce
Not needed. I think.

By the wway, it works fine. Thx a lot.

**Comment by Guite** [comment]
What do you mean with that? What kind of feedback to you expect? Please elaborate.

**Comment by Portugao** [comment]
For the autocomplete a rotating icon.
Does the fix do that?

**Comment by Guite** [comment]
Yes.

**Comment by Portugao** [comment]
👍
