### ISSUE TITLE
Po extract does not work because of invalid rss template

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1124]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
no error
### Actual behavior
The extractor stops with an error:
unexpected character ',' in line 51

### Steps to reproduce
Try to extract a po files from a generated 1.5. module.

**Comment by Guite** [comment]
Please post line 51 and/or a link to the template file and/or the _full_ error message.

**Comment by Portugao** [comment]
```
        <pubDate>{{ page.createdDate|date('a, d b Y T +0100') }}</pubDate>
```

**Comment by Portugao** [comment]
Not fixed:
```unexpected character '´'```
in line 52:
```        <pubDate>{{ post.createdDate|date('r') }}</pubDate>```

**Comment by Guite** [comment]
Please check if it works now (staging update arrives in about 30 minutes). If not try to open the RSS page in your browser to get a more helpful error message and create a new issue.
