### ISSUE TITLE
Options for relationship-based permissions inheritance

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#1125]
It would be nice if there were DSL properties to define whether permissions for related parent(s) should be checked for accessing a certain object.

Example 1: if one person has many addresses then an address is only visible if the user has permissions for the person this address belongs to.

Example 2: if many groups have many products then a product is only visible if the user has permissions for at least one assigned group.

Example 3: if many groups have many products then a product is only visible if the user has permissions for all assigned groups.

**Comment by Guite** [comment]
Benefit: similarly as category-based permissions this allows a more convenient specification of permissions for many objects instead of having to define many single permissions or rather complex permission rules with regular expressions.

**Comment by rallek** [comment]
I would have a use case in ShowRoomModule.
