### ISSUE TITLE
Unclear permission environment in standard workflow

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1129]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
A permission that enables to submit items as unregistered user without success to existing items.

### Actual behavior
If I give a unregistered user edit permissions for an entity he can also edit it. Permissions below he cannot submit an item.

### Steps to reproduce
For clearing. Maybe I'm wrong......

**Comment by Guite** [comment]
Look at https://modulestudio.de/documentation/c/87-GeneratorReference#entity-workflow-type

There is an image showing the possible interactions including the required permission levels. For submitting content (from _initial_ to _waiting_) only comment permissions are required.

**Comment by Portugao** [comment]
Hmmhmm...I had to ask to ensure myself.
Comment is the permission to submit an item into the state 'waiting'.
So there is a problem, because this right does not work for me. That means a unregistered user cannot enter the edit form of my entity with the permission 'comment'.
Not sure where the issue is caused?!

**Comment by Guite** [comment]
> unregistered user cannot enter the edit form

Does he see the link and get's an access denied error? Or is the link not visible? Or both?

**Comment by Portugao** [comment]
I have another site with the link to the edit form:
If the user (me as guest) with comment permission click this, he gets the login form with 'Access denied'.
As guest I need edit permission to enter the edit form.
