### ISSUE TITLE
Fehler bei Aufruf eines Moduls nach Ergänzung einer Entität mit "Geographisch"

### ISSUE THREAD

**Issue by MisterFau** [Guite/MostGenerator#1131]
![image](https://user-images.githubusercontent.com/31589951/30003087-cbd983d6-90b8-11e7-8784-8f9f18bd251e.png)

Modusestudio 1.0.2 und Zikula 1.5.1 - nach Installation des Moduls, bei dem diese Entität ergänzt wurde kommt bei Modulaufruf folgender Fehler:

Warning: require_once(/www/htdocs/webseite/modules/Fauman/DunkwardsModule/Base/../vendor/autoload.php): failed to open stream: No such file or directory in /www/htdocs/webseite/modules/Fauman/DunkwardsModule/Base/bootstrap.php on line 20

Fatal error: require_once(): Failed opening required '/www/htdocs/webseite/modules/Fauman/DunkwardsModule/Base/../vendor/autoload.php' (include_path='.:/usr/share/php:..') in /www/htdocs/webseite/modules/Fauman/DunkwardsModule/Base/bootstrap.php on line 20
   Seitenname

Fatal error: Class 'Fauman\DunkwardsModule\Container\LinkContainer' not found in /www/htdocs/webseite/app/cache/prod/appProdProjectContainer.php on line 1396

**Comment by Portugao** [comment]
This is caused by not running composer.

**Comment by Guite** [comment]
Yes, this is not a bug. If you enable geographical and/or pdf support you need to install dependencies (required libraries) using composer. The generated `INSTALL.md` also explains how to do this.
https://getcomposer.org/
