### ISSUE TITLE
Keine Einträge auffindbar bei einer über autocompletion verknüpften Entität

### ISSUE THREAD

**Issue by MisterFau** [Guite/MostGenerator#1139]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK15]
| Zikula Version         | [1.5.1]
| PHP Version            | [?]

### Expected behavior
Keine Einträge auffindbar bei einer über autocompletion verknüpften Entität

### Steps to reproduce
Bei einem neu generierten Modul funktioniert das verknüpfen von per relation verbundener Entitäten per auto completion nicht. Es werden keine Einträge gefunden / angezeigt. Nur der Ladekreis.
![image](https://user-images.githubusercontent.com/31589951/30398688-95eedd90-98d1-11e7-8eb0-87d135009e70.png)

**Comment by Guite** [comment]
Das sieht nach einem JavaScript-Fehler aus. Siehst Du, wenn Du die Konsole im Browser aktivierst. Und ich tippe stark darauf, dass das selbe ist wie #1136 bzw. https://github.com/zikula/core/issues/3807

**Comment by MisterFau** [comment]
Stimmt. Ist das selbe. Danke.
