### ISSUE TITLE
Autocomplete not working for related entities

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1142]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.x-git]
| PHP Version            | [5.6.x]

### Expected behavior
When creating new entries for an entity, autocomplete shows results for related entities

### Actual behavior
When creating new entries, autocomplete does not show results for related entities (hour glass keeps turning). After clicking the Create button of the related entity, it is possible to successfully create a new related item, but the pop-up window does not close and autocomplete continues to not show results.

### Steps to reproduce
Module with releated entities

**Comment by Guite** [comment]
Please check your browser console. Probably the same as https://github.com/zikula/core/issues/3807

**Comment by Guite** [comment]
Also the same as https://github.com/Guite/MostGenerator/issues/1139

**Comment by Guite** [comment]
Closing as core issue. For a workaround see https://github.com/zikula/core/issues/3807

**Comment by ThiloWitt** [comment]
Thanks, it is the same, working now
