### ISSUE TITLE
ItemBlockType does not exist

### ISSUE THREAD

**Issue by KratorD** [Guite/MostGenerator#1146]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.0.2]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.2]
| PHP Version            | [5.6.x]

### Expected behavior
The module is installed succesfully in Zikula

### Actual behavior
Error: "InvalidServiceDefinitionsException

Service definition validation errors (1):
- vendor_mymodule_module.form.type.block.item: Class "vendor\MyModule\Block\Form\Type\ItemBlockType" does not exist"

### Steps to reproduce
Create an application in ModuleStudio 1.0.2 and try install in Zikula 2.0.2.

Note: File forms.yml. Delete service "vendor_mymodule_module.form.type.block.item"

**Comment by Guite** [comment]
Did you have any custom generator settings in your model? If yes, which value is set for `generateDetailBlock`?

**Comment by KratorD** [comment]
Marked

**Comment by Guite** [comment]
@KratorD I think both issues are solved in the latest staging update. If you like feel free to join our Slack channels so that we can also directly communicate in future. See the links at https://zikula.de/en/ for that.
