### ISSUE TITLE
Add a label for each category registry entry point

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#1147]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK15
| Zikula Version         | 1.5.x-git
| PHP Version            | 5.6.x

### Feature request
see:
https://stackoverflow.com/questions/47103739/use-the-category-node-name-as-a-label-in-zikula/47110823#47110823

**Comment by Guite** [comment]
I do not understand yet what you want to achieve. Could you post a screenshot and explain what should be changed specifically?

**Comment by rallek** [comment]
The filter view of the second category:
![grafik](https://user-images.githubusercontent.com/935250/32406831-b0a42e7a-c17f-11e7-88a1-8a78b469e1fa.png)


This is a part of my category tree:
![grafik](https://user-images.githubusercontent.com/935250/32406867-28a527b2-c180-11e7-9265-c71911161d2b.png) (German)

And this is a part of my category registry:
![grafik](https://user-images.githubusercontent.com/935250/32406883-63a8311a-c180-11e7-837f-587d2b64b06a.png) (German)
![grafik](https://user-images.githubusercontent.com/935250/32406927-f466f4fc-c180-11e7-88b1-0a30136115e6.png) (English)


In my case I want to have the label ``vehicle age`` (or ``Altersklasse`` in case of German) in front of the first category selection field and ``vehicle type`` / ``Fahrzeugtyp`` in front of my second category selection field.

**Comment by Guite** [comment]
I think this would make also sense at other places (edit form, display page, content types editing, blocks editing, etc.)...

**Comment by rallek** [comment]
You are right

**Comment by Guite** [comment]
Fixed in https://github.com/zikula/core/pull/3846
