### ISSUE TITLE
Variable "isCategorisable" does not exist.

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1151]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.2
| PHP Version | 5.6.x

### Expected behavior
no error when creating a block

### Actual behavior
```
in modules/MU/BloggingModule/Resources/views/Block/itemlist_modify.html.twig at line 3   -
{# Purpose of this template: Edit block for generic item list view #} 
{{ form_row(form.objectType) }} 
{% if isCategorisable %} 
    {{ form_row(form.categories) }} 
{% endif %} 
{{ form_row(form.sorting) }} 
```
An old issue is back:
https://github.com/Guite/MostGenerator/issues/1065
### Steps to reproduce
Try to create a block with entity that is categorisable.

**Comment by Guite** [comment]
Fixed in 606f3f2484fb93e8d3f234f42284f2a9951a60cb

By the way: in `MU/BloggingModule/Block/Form/Type/ItemListBlockType.php` you can replace:
```
		$this->addObjectTypeField($builder, $options);
		if ($options['feature_activation_helper']->isEnabled(FeatureActivationHelper::CATEGORIES, $options['object_type'])) {
			$this->addCategoriesField($builder, $options);
		}
		$this->addSortingField($builder, $options);
		$this->addAmountField($builder, $options);
		$this->addTemplateFields($builder, $options);
		$this->addFilterField($builder, $options);
```
by
```
                parent::buildForm($builder, $options);
```
