### ISSUE TITLE
Typo in forms.yml

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1157]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
no error

### Actual behavior
invalid forms.yml

### Steps to reproduce
In the part for the config service there is a line not on the correct place...

**Comment by Guite** [comment]
Already fixed in 1e53edfa7d7bc2bbdb7f8149dcb6dd54e9564ed4
