### ISSUE TITLE
AbstractItemBlockType.php - missing statements

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1158]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
no error

### Actual behavior
2 missing this->.... = $..... statements in constructor line 55

### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

**Comment by Portugao** [comment]
The error essage is: 
```
FatalErrorException in AbstractItemBlockType.php line 103:
Error: Call to a member function getRepository() on null
```

**Comment by Portugao** [comment]
After fix:
```
Notice: Undefined variable: choiceLabelClosure
```

**Comment by Portugao** [comment]
```
in modules\MU\TestAppModule\Block\Form\Type\Base\AbstractItemBlockType.php at line 117   -
        ksort($choices); 
     
        $builder->add('id', ChoiceType::class, [ 
            'choice_label' => $choiceLabelClosure, 
            'multiple' => false, 
            'expanded' => false, 
            'choices' => $choices,
```

**Comment by Guite** [comment]
Thanks, both fixed.
