### ISSUE TITLE
Missing class

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1161]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.3
| PHP Version | 5.6.x

### Expected behavior
no error

### Actual behavior
```
InvalidServiceDefinitionsException in ValidateServiceDefinitionsPass.php line 44:
Service definition validation errors (1):
- mu_comments_module.form.type.field.multilist: Class "MU\CommentsModule\Form\Type\Field\MultiListType" does not exist
```

### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

**Comment by Portugao** [comment]
The folder form/type/field is not there....

**Comment by Portugao** [comment]
Does not work again....no class

**Comment by Portugao** [comment]
@Guite Hope you read this above.

**Comment by rallek** [comment]
I would open a new ticket with refference to this one
