### ISSUE TITLE
https://github.com/Guite/MostGenerator/issues/1161 not fixed

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1162]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.x-git
| PHP Version | 5.6.x

### Expected behavior
no error

### Actual behavior

same error like in #1161 
### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

**Comment by Guite** [comment]
Fixed by 28a301c925293cba430736c726db5fe9f5872c95
