### ISSUE TITLE
Missing possible options for list field (mod var)

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1165]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.3
| PHP Version | 5.6.x

### Expected behavior

no options for list var
### Actual behavior
The possible options, set in MOST, are not there in the form.

### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

**Comment by Guite** [comment]
What do you mean with "options"? The list items?

**Comment by Portugao** [comment]
Yes, the list items, sorry. Sellms to be solved. 😄
