### ISSUE TITLE
Seems saving config does not work

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1167]
| Q | A
| -------------------- | ---
| ModuleStudio Version | latest git
| Operating System | Windows
| Zikula Target in Model | ZK15
| Zikula Version | 1.5.3
| PHP Version | 5.6.x

### Expected behavior
saving changes

### Actual behavior

no saving of changes made in the config form
### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

**Comment by Guite** [comment]
Works fine here. Please verify again and create a new issue pointing to a specific use case / setting which fails.
