### ISSUE TITLE
Option to get action links with icons

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1169]
It would be fine to have the possibilty to activate another kind of links for an entity in the view and display templates
At the moment there is a button called 'actions', so I cannot see, which actions are possible with this entity.
Also I have one more click to get the relevant template for the wished action.
In an earlier version of MOST there were several icons for each action like edit, delete, overview and so on.
If I remember correctly, the icons in the view tempate were on the right side of the table, which is better for the most users...
It would be fine for me to have this back as option or by default or whatever....

Nice to have: the option to set different apperances of links ( standard links, bootstrap buttons and so on).

**Comment by Guite** [comment]
How about two new properties for view action elements:

- actions position (LEFT, RIGHT, default right)
- actions style (DROPDOWN, ICONS, BUTTONS, default DROPDOWN)

**Comment by Portugao** [comment]
Hi Axel,
you're suggesting exactly what would make me happy.

**Comment by Guite** [comment]
We should better name the positions START and END instead of LEFT and RIGHT, so it fits to all view types proposed in #1148.

**Comment by robbrandt** [comment]
Great suggestions on both counts.
BTW, I requested the move of the controls to the left, because when they are on the right, and your entities have a lot of columns, you have to be constantly horizontal scrolling to get anything done.
There were also times when I added icons myself because it was just simpler for the users.  I don't think the dropdown is a good UI for new users.

**Comment by Guite** [comment]
> have a lot of columns

in the meantime you can specify in the model which fields should appear on view pages and which not (displayType property)

Any input regarding the required options for the _actions style_ property?

**Comment by robbrandt** [comment]
My preference is icons.  Dropdowns become attractive only when there's too many to fit in a small space.

**Comment by Guite** [comment]
My point was not which one is preferred but which alternatives/options we should provide in total.

**Comment by Portugao** [comment]
Good question, Axel.
This feature is for me relevant in view and display templates; also the header menu in the frontend could be flexible.
Would be fine, if classes for the color and size would be choosable for corresponding kinds of links.

**Comment by Guite** [comment]
> classes for the color and size

Isn't this task of the theme?
If a module sets stuff like this it breaks consistency across multiple modules on a page.

**Comment by Portugao** [comment]
Only to choose if btn-default or btn-danger and btn-xs oder btn-sm for example. Not to set the color or size directly.

**Comment by Guite** [comment]
I disagree to making such things configurable for each single link. First these links are dynamically derived, for example _Add child entity xy_ if the current user has the required permissions. Second convention over configuration (e.g. use `btn-danger` for _delete_ actions). Third this is simply too detailed for being worth becoming part of an application model.
If one needs special classes for specific links this is better done by customising the `ItemActionsMenu` class adding these classes to the corresponding menu item that has already been added by the parent class.

**Comment by robbrandt** [comment]
> My point was not which one is preferred but which alternatives/options we should provide in total.

I think you could make a case for all three.  The dropdown option IS better when there are a lot of options and limited space.  You might start a war over icons vs buttons; buttons in UI design (Ithink) are supposed to take actions rather than links (icons) that are just supposed to take you somewhere. But those guidelines have been muddied so much no one really cares anymore.

**Comment by Guite** [comment]
> icons vs buttons

My question was whether it makes sense to also offer a combined thing.

Something like:
```<a href="..." title="..."><i class="fa fa-myicon"></i> <span class="hidden-xs">My label which is not shown in XS</span> </i></a>```

**Comment by Portugao** [comment]
> I disagree to making such things configurable for each single link

So I missunderstood this
> Any input regarding the required options for the actions style property?

What does it mean?

**Comment by Guite** [comment]
> actions style (DROPDOWN, ICONS, BUTTONS)

> As for the styles I am not sure yet whether the mentioned options are enough. Do we also need something like ICON_BUTTONS to have buttons containing an icon in addition to the label?

> My question was whether it makes sense to also offer a combined thing.

> Something like:
<a href="..." title="..."><i class="fa fa-myicon"></i><span class="hidden-xs"> My label which is not shown in XS</span> </i></a>

**Comment by craigh** [comment]
Screenshot mockups would be nice here. I’m not sure I am thinking about the same UI items that you are.

**Comment by craigh** [comment]
This is to replace something like this then, yes?

![screen shot 2017-11-21 at 3 11 17 pm](https://user-images.githubusercontent.com/350048/33094459-4434ab28-cece-11e7-958e-b25abdaea6f9.png)

I would like to add the option of [button groups](https://getbootstrap.com/docs/3.3/components/#btn-groups)

![screen shot 2017-11-21 at 3 13 32 pm](https://user-images.githubusercontent.com/350048/33094551-8db2c8e8-cece-11e7-8f64-210cbb479c27.png)

**Comment by Portugao** [comment]
Yes, button groups also would be helpful.

**Comment by Guite** [comment]
DSL tasks:
- [ ] introduce new properties
  - [ ] `actionsPositionView` (enumeration: NONE, START, END) and `actionsPositionDisplay` (enumeration: NONE, START, END, BOTH), both default = START
  - [ ] `actionsStyleView` and `actionsStyleDisplay` (enumeration: LINK, ICON, BUTTON, BUTTON_GROUP, DROPDOWN), both default `DROPDOWN`
  - [ ] `actionsIncludeIconsView` and `actionsIncludeIconsDisplay` (flags, default `true`)
- [ ] update grammar
- [ ] add validation constraint (icons flag must not be disabled if style is set to `ICONS`)
- [ ] add quick fixes for new validation constraint
- [ ] update docs (validation reference, generator reference)

Tooling tasks:
- [ ] extend property mappings

Generator tasks:
- [ ] extend implementation
- [ ] switch / provide menu templates (see also [this doc page](https://github.com/zikula/core/blob/master/src/docs/Menu/CustomTemplates.md))

**Comment by Guite** [comment]
Done :tada: 

Button groups are aligned horizontally on display pages and vertically on view pages (to save horizontal space).
