### ISSUE TITLE
Auto-correct wrong image orientation

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#1176]
The generated code should care for incorrectly oriented images.
Based on the gathered EXIF data this can be detected and corrected.

@gfr is going to investigate this.
cc @rallek

**Comment by rallek** [comment]
If I upload a portrait image- It is shown correctly (one try).
How can I help testing?

**Comment by Guite** [comment]
It heavily depends on the used smartphone device. I guess Gabriel has some test images from some of his users.

**Comment by rallek** [comment]
Today I have the same issue. I uploaded an image what was taken by a smart phone. The exif tag ``format: landscape`` but on windows the image is shown correctly. There I did not find the orientation tag but ``Orientation - Right top``.
No idea if this is helping:
https://stackoverflow.com/questions/28251338/jquery-image-preview-exif-rotation-issue
As long as there is no auto correction I would like to have an image manipulation where the user can turn the image in edit form afterwards.

**Comment by Guite** [comment]
http://php.net/manual/en/function.exif-read-data.php#110894
http://php.net/manual/en/function.exif-read-data.php#76964
http://php.net/manual/en/function.exif-read-data.php#115987
https://stackoverflow.com/questions/7489742/php-read-exif-data-and-adjust-orientation
https://github.com/merty/image-rotation-fixer

**Comment by rallek** [comment]
Great job!
