### ISSUE TITLE
Form validation is executed when clicking 'Cancel' button

### ISSUE THREAD

**Issue by lisa-dancecloud** [Guite/MostGenerator#1180]
In my generated form I have a few 'required' fields. When the cancel button is clicked and these fields are still empty, the form validation is executed ('Value should not be empty!') and the form isn't cancelled.

I guess this happens because the cancel button is of type 'submit'. Any ways to fix this? :)

**Comment by Guite** [comment]
To debug this please follow these steps:

1. Usually the reset and cancel buttons have a `formnovalidate` attribute set in the form type to prevent validation:
```
        $builder->add('cancel', SubmitType::class, [
            'label' => $this->__('Cancel'),
            'icon' => 'fa-times',
            'attr' => [
                'class' => 'btn btn-default',
                'formnovalidate' => 'formnovalidate'
            ]
        ]);
```
See also the description here: https://www.w3schools.com/tags/att_input_formnovalidate.asp
So first please verify that your cancel button contains this attribute in the edit page's final markup.

2. In `modules/YourVendor/YourModule/Resources/public/js/YourModule.EditFunctions.js` there is a `triggerValidation` variable which is used to decide whether validation should be executed or not. This variable is set depending on the `formnovalidate` attribute like this:
```
            editForm.find('button[type=submit]').bind('click keypress', function (event) {
                triggerValidation = !jQuery(this).prop('formnovalidate');
            });
```
The `fooHandleFormSubmit` function then checks this variable and calls validation if needed:
```
        function «vendorAndName»HandleFormSubmit (event) {
            if (triggerValidation) {
                «vendorAndName»TriggerFormValidation();
                if (!editForm.get(0).checkValidity()) {
                    event.preventDefault();
                    return false;
                }
            }
            // ...
        }
```
So in a second step you might hook into this logic and output the `triggerValidation` value, e.g. by doing something like `console.log(triggerValidation ? 'Do validation' : 'No validation');`

**Comment by lisa-dancecloud** [comment]
1. The cancel button contains the 'formnovalidate' attribute: 

`<button type="submit" id="«vendorAndName»_track_cancel" name="«vendorAndName»_track[cancel]" class="btn btn-default btn" formnovalidate="formnovalidate"><i class="fa fa-times"></i> Cancel</button>`

2. I added a console output like this:
```
function «vendorAndName»HandleFormSubmit (event) {
    console.log(triggerValidation ? 'Do validation' : 'No validation'); //new line
    if (triggerValidation) {
        //...
        }
    }
 //...
}
```

and also here just to make sure:
```
  editForm.find('button[type=submit]').bind('click keypress', function (event) {
        triggerValidation = !jQuery(this).prop('formnovalidate');
        console.log(triggerValidation ? 'Do validation' : 'No validation'); //new line
    });
```

It always outputs 'Do validation' when the cancel button is clicked.
