### ISSUE TITLE
plugin issue

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1183]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK20
| Zikula Version         | 2.0.6
| PHP Version            | 5.6.x

### Expected behavior

No issue
### Actual behavior

Variable "pluginOptions" does not exist.
```
    {{ form_row(form.modules) }}    {{ form_row(form.search) }}</div><div class="hidden">    {# @deprecated remove at Core-2.0 #}    {% for plugin, pluginOption in pluginOptions %}        {{ pluginOption|raw }}    {% endfor %}</div>{% set moduleVariables = zikulasearchmodule_searchVarToFieldNames() %}{% for name, value in moduleVariables %}
```
### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.
Take a new generated module

**Comment by Portugao** [comment]
Sorry. Now I see it is not an MOST issue..

**Comment by Guite** [comment]
Sure it's no generator problem?

**Comment by Portugao** [comment]
Yes...some templates in 2.0 are different from those in 1.5.
