### ISSUE TITLE
processViewActionParameters method must still be overwritten

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1186]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK20
| Zikula Version         | 2.0.7
| PHP Version            | 7.x

### Expected behavior
overriding should work better

### Actual behavior
https://github.com/Portugao/News/issues/33
This issue contains the problem that the overriding of the method has no effect because of the processViewActionParameters

### Steps to reproduce
Try the actual repository to reproduce. defautsortings field set in the settings has no effect.

**Comment by Guite** [comment]
Fixed in https://github.com/Portugao/News/commit/223fc7a6ad50f4a7ae784d59b1bda4f4f599b320
