### ISSUE TITLE
Class not loaded

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1190]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK20
| Zikula Version         | 2.0.7
| PHP Version            | 7.x

### Expected behavior

no error

### Actual behavior
```
Attempted to load class "AbstractHookAssignmentEntity" from namespace "MU\PollsModule\Entity\Base".
Did you forget a "use" statement for another namespace?
```
```
Symfony\Component\Debug\Exception\ClassNotFoundException:
Attempted to load class "AbstractHookAssignmentEntity" from namespace "MU\PollsModule\Entity\Base".
Did you forget a "use" statement for another namespace?

  at modules/MU/PollsModule/Entity/HookAssignmentEntity.php:24
```

### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

**Comment by Guite** [comment]
I can not reproduce. The `1.2.0` branch seems to work fine here (Core 2.0.8-git, PHP 7.2.7)

**Comment by Portugao** [comment]
I will look again...

**Comment by Portugao** [comment]
I close it...missing update of helper.yml in other modules caused this. Sorry.
