### ISSUE TITLE
Field type: datetime, Component: TIME is being displayed wrong

### ISSUE THREAD

**Issue by DirkThiele** [Guite/MostGenerator#1194]
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.7]
| PHP Version            | [5.6.32-nmm1]

### Expected behavior
Time only being displayed if datetime field is set to component: 'TIME'

### Actual behavior
displayPattern = `#marktStart# Uhr - #marktEnde# Uhr`
result in the `title` of the element = `05.08.18, 06:00 Uhr - 19700101 05:00 nachm. Uhr`
It is only the title that is affected.
The value in the display view is formatted correctly to: 17:00 (in this case)

### Steps to reproduce
Input field of type 'datetime', component: 'TIME'
Add input field to displayPattern

**Comment by Guite** [comment]
Please try this:

1. Open `Helper/Base/AbstractEntityDisplayHelper.php`
2. For `[IntlDateFormatter::NONE, IntlDateFormatter::NONE]`
3. Replace by `[IntlDateFormatter::NONE, IntlDateFormatter::SHORT]` **two times**
4. Test again

Does this make a difference?

**Comment by DirkThiele** [comment]
Yes, now it works fine!
Perfect!

**Comment by DirkThiele** [comment]
whups, sorry
