### ISSUE TITLE
Related items: standard fields vs upload fields

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#1196]
If related objects are loaded in edit forms their upload fields are changed because a _postLoad_ listener transforms file names to File objects. This causes that _updatedDate_ is updated which marks the corresponding items as dirty.

**Comment by Guite** [comment]
@gfr this should not be solved, right? Because the file object is not related to the fields managed by Doctrine anymore. Are you able to test that?

**Comment by gfr** [comment]
+1 for close
