### ISSUE TITLE
Cannot create entity normally

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#1199]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows 10
| Zikula Target in Model | ZK20
| Zikula Version         | 2.0.x
| PHP Version            | 7.1

### Expected behavior
no problem

### Actual behavior
If I create a new entity, there is no container for the fields and for the actions.
So I cannot create fields or actions.
The example entites are there.

### Steps to reproduce
If this involves a rather complex scenario maybe attach the `.mostapp` model file.

**Comment by Guite** [comment]
Ehm... you probably just need to activate the corresponding layers?
https://modulestudio.de/documentation/c/32-DiagramEditor#layers

**Comment by Portugao** [comment]
They are.

**Comment by Guite** [comment]
Nothing changed during the last weeks though. Please close all projects, close MOST and rename your `MostWorkspace` directory to a temporary name to see if it works again afterwards.

**Comment by Portugao** [comment]
Strange. If I create a new entity, the layers are not there. If I disable one and enable then, all is fine.

**Comment by Guite** [comment]
Will see if I can reproduce this next week.

**Comment by Portugao** [comment]
👍

**Comment by Guite** [comment]
I've just fixed this problem. The corresponding staging update will be available in about 10 to 15 minutes.

**Comment by Portugao** [comment]
Thx a lot. 👍
