### ISSUE TITLE
Create Button does not disappear while 1:1 relation exists

### ISSUE THREAD

**Issue by DirkThiele** [Guite/MostGenerator#1200]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest git
| Operating System       | Windows
| Zikula Target in Model | ZK20
| Zikula Version         | 2.0.11
| PHP Version            | 7.2

### Expected behavior
In display mode the `Create Button` for a new 1:1 relation should be removed if there is related content already. It is the `Create Button` from the knp menu bar that does not disappear. The `Create Button` inside the `related_items` Block is being replaced by the item related, which is correct.

The `Create Button` from the knp menu bar still provides the edit form but it won't let you store a further entry, which is also correct as it is a 1:1 relation.

### Actual behavior
`Create Button` from the knp menu does not disappear.

### Steps to reproduce
Two entities (Customer & Customer data) connected via 1:1 (One Customer has one Customer data) relation.

First create a "Customer" and then from the display view create the "Customer data" relation.
After returning to the "Customer" display view you will still find the `Create Button` for new "Customer data" inside the knp menu.

**Comment by Guite** [comment]
Please mail the model to info [at] modulestudio [dot] de
