### ISSUE TITLE
W10 Open project not working

### ISSUE THREAD

**Issue by KratorD** [Guite/MostGenerator#1209]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.4.0]
| Operating System       | [Windows10]
| Zikula Target in Model | [Any]
| Zikula Version         | [Any]
| PHP Version            | [Any]

Using Windows 10 and ModuleStudio 1.4.0. If you have an open project and you wish change to another project with "Open project", the process never ends. When in the popup of "Open external project", you select a project of the list, the app not respond. Look that is loading, but dont never ends.

### Expected behavior
The selected project is open

### Actual behavior
The application ModuleStudio is not responding.

### Steps to reproduce
App/Project open. 
Open another project.
App is not responding.

**Comment by Guite** [comment]
See Slack for some testing instructions.

**Comment by Guite** [comment]
Steps:
1. Create a new project (test1)
2. Create a new project (test2) (Work)
3. Go to "Dashboard", Press "Open project". Select "project1".
Result: The project is not opened and ModuleStudio. The window remains open without ever ending (Open external project)

**Comment by Guite** [comment]
[metadata.zip](https://github.com/Guite/MostGenerator/files/2875037/metadata.zip)

**Comment by Guite** [comment]
Need to check first if this is still an issue.

**Comment by Guite** [comment]
fixed in latest dev build!

**Comment by KratorD** [comment]
I'm testing again and It's working. Thanks
