### ISSUE TITLE
Filter in "one to many" and "many to many" relations for values on the "many" side

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1217]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.4.0]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.12]
| PHP Version            | [PHP 7.0.33-0ubuntu0.16.04.2]

## Summary
Filter in "one to many" and "many to many" relations for values on the "many" side

## Desired Behavior
In "one to many" relations like "one customer has many addresses", I need to filter on "addresses" in the customer entity (filtering on "customers" in the addresses entity is already possible).

In a "many to many" relation like "many customers have many products", I need to filter on "products" in the customer entity and on "customers" in the products entity.

**Comment by Guite** [comment]
> filtering on "customers" in the addresses entity is already possible

So you are refering to quick navigation?



How do you imagine this filtering to work in the UI? Dropdown boxes or checkboxes in the quick navigation? Or avoid new controls but extend where the quick navigation's search input searches?

**Comment by ThiloWitt** [comment]
> So you are refering to quick navigation?

Yes, this is about quick navigation
> How do you imagine this filtering to work in the UI? Dropdown boxes or checkboxes in the quick navigation? Or avoid new controls but extend where the quick navigation's search input searches?

I was thinking about Dropdown boxes. Please explain what you mean by "extending where the quick navigation's search input searches"?

**Comment by Guite** [comment]
> I was thinking about Dropdown boxes.

But single dropdowns (no multi selection), right? Otherwise the quick navigation bar would become quite huge.

> Please explain what you mean by "extending where the quick navigation's search input searches"?

That when you enter "example" into the search input field at customer-view, it also searches for customers which have an address with "example street". Meaning, that address fields are added into the fields which are covered by the search process. This is not done for "single-valued" relations yet though, too. Possibly also too expensive with regards to performance. So I'd also rather tend to a dropdown or something.

**Comment by ThiloWitt** [comment]
> But single dropdowns (no multi selection), right? Otherwise the quick navigation bar would become quite huge.

Yes, I confirm that single dropdowns would meet my requirement. I have a question though: would multi selection make sense for related entities with a TreeForm? I am currently wondering how by selecting a knode of an EntityTreeForm, the query would return the lower level entries that belong to the  knode.
> That when you enter "example" into the search input field at customer-view, it also searches for customers which have an address with "example street". Meaning, that address fields are added into the fields which are covered by the search process. This is not done for "single-valued" relations yet though, too. Possibly also too expensive with regards to performance. So I'd also rather tend to a dropdown or something.

Interessting. If this could be implemented with autocompletion functionality it would definitely help! Maybe autocompletion in a dedicated search box instead of with a dropdown list would be the most comfortable solution.

**Comment by Guite** [comment]
> would multi selection make sense

> autocompletion in a dedicated search box

I think such things are too complex for a _quick_ navigation.

**Comment by ThiloWitt** [comment]
ok

**Comment by Guite** [comment]
This feature has been implemented in 52a9b49

I've not only added new dropdown fields for many-valued relationship sides, but also for target sides of one2one and many2one relationships.
