### ISSUE TITLE
"Show only own entries" also comes for users with Read Only Access

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1220]
Q | A
-- | --
ModuleStudio Version | [1.4.0]
Operating System | [Windows]
Zikula Target in Model | [ZK20]
Zikula Version | [2.0.12]
PHP Version | [PHP 7.0.33-0ubuntu0.16.04.2]

Summary

when module "view" is displayed, the option "Show only own entries" comes also for users with Read Only Access.

Desired Behavior

"Show only own entries" shall not come for users with Read Only Access.

**Comment by Guite** [comment]
refs #1213
