### ISSUE TITLE
Relation Inherited Permissions not respected by Search Module

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1223]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )

| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.4.0]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.x-git]
| PHP Version            | [7.2.x]

## Expected Behavior
SEARCH should only show titles permitted for the logged in user

## Current Behavior
SEARCH shows all titles including the ones not permitted for the logged in user. When clicking on the Title an error is issued: You do not have permission for that action.

**Comment by Guite** [comment]
Moved permission inheritance functionality and category permission checks into permission helper to apply them for search and other integration areas. Staging update will be available in about 15 minutes after all build jobs finished.
