### ISSUE TITLE
Inherit Permissions for one2one and many2one Relations

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1228]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [latest git]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.x]
| PHP Version            | [7.3.x]

## Summary
Inheriting permissions via relations allows for a simple permissions setup in complex modules. It works well for one2many relations even for only indirectly related entities.

## Desired Behavior
Still missing are inherit permissions for one2one and many2one relations and should be added.

**Comment by Guite** [comment]
> Still missing are inherit permissions for one2one and many2one relations and should be added.

The `inheritPermissions` property exists for one2one relationships already.
For many2one this is not possible, because many2one is never bidirectional.
