### ISSUE TITLE
Inherit Permissions for many2one Relations in QuickNavigationForm

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1230]
Q | A
-- | --
ModuleStudio Version | [latest git]
Operating System | [Windows]
Zikula Target in Model | [ZK20]
Zikula Version | [2.0.x]
PHP Version | [7.3.x]

## Expected Behavior

The Target Entity QuickNavigationForm should only show permitted Source Entity entries

## Current Behavior

The Target Entity QuickNavigationForm shows all Source Entity entries including those with no permission

**Comment by Guite** [comment]
I think you mean one2many, right?
