### ISSUE TITLE
Sorting target entity entries by parent entity - add related sort fields in QuickNavForm

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1231]
Q | A
-- | --
ModuleStudio Version | [latest git]
Operating System | [Windows]
Zikula Target in Model | [ZK20]
Zikula Version | [2.0.x]
PHP Version | [7.3.x]

**Expected Behavior**
The fields of the Partent Entity that are sortable in the Target Entity should be visible in the "Sort by" Dropdown box of the Target Entity's QuickNavigationForm

**Current Behavior**
The Target Entity's "Sort by" Dropdown box does not show these fields

**Comment by Guite** [comment]
This is already done. The parent entity appears with it's source alias in the sortBy dropdown field; exactly like the corresponding table column is named, too.
