### ISSUE TITLE
Filtering in translatable fields fails

### ISSUE THREAD

**Issue by ThiloWitt** [Guite/MostGenerator#1234]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.4]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK20]
| Zikula Version         | [2.0.x]
| PHP Version            | [7.3.x]

## Expected Behavior
Translable fields should be filterable with translated text

## Current Behavior
Full translations filtering results in "not found", only partial sequences of a translation deliver results

[Directory.mostapp.txt](https://github.com/Guite/MostGenerator/files/4594119/Directory.mostapp.txt)

**Comment by Guite** [comment]
Example: a professional area "English (original): Acupressure" and "Spanish: Acupresión" can be found by searching for "Acupressure", but not for "Acupresi".
