### ISSUE TITLE
Provide start page setting instructions

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#1236]
If the current user has permissions for the Settings module, an additional item action should appear, named "_How to use as start page"_ or similar.

When clicking on this action, a modal window appears showing instructions about how to configure the start page in order to display this item. For example:

> Select the controller 'zikulapagesmodule_pages_display' and add 'slug=my-cool-page' to requested attributes if you want to make this page the start page.

**Comment by Guite** [comment]
@rallek updated proposal above

**Comment by rallek** [comment]
great! That is helpfull for admins a lot!

How this can be implemented in a help system at all??

**Comment by Guite** [comment]
Don't understand the question - please clarify.
As described above, I suggest to show a modal window with the required instructions on demand.

**Comment by rallek** [comment]
it is a question of style :-) 
This modal window is a kind of help documentation. There is already a help page. Might be this can be included there.
![image](https://user-images.githubusercontent.com/935250/85835751-e0568c80-b795-11ea-8238-916570fda1f8.png)

**Comment by Guite** [comment]
good point! would be even better to include it there, because a new item action only for some instructions would "pollute" the UI

**Comment by rallek** [comment]
If there is a style guide for good extensions it would be great to see this instruction there as well ;-)

**Comment by Guite** [comment]
The idea has become obsolete.
