### ISSUE TITLE
ZK 3 Modules do not install

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#1239]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )

| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [1.3.2/latest git/etc]
| Operating System       | [Windows/Linux/MacOS]
| Zikula Target in Model | [ZK30/]
| Zikula Version         | [3.0.x]
| PHP Version            | [7.4.x]

## Expected Behavior

fresh released ZK 3 modules shall install

## Current Behavior

News and Pages do not install see the stack trace of Pages and the issue at News: https://github.com/zikula-modules/News/issues/139
 
--
Symfony\Component\ErrorHandler\Error\ClassNotFoundError: Attempted to load class "ZikulaPagesModule" from namespace "Zikula\PagesModule". Did you forget a "use" statement for another namespace?    at vendor/zikula/extensions-module/Helper/BundleSyncHelper.php:144   at Zikula\ExtensionsModule\Helper\BundleSyncHelper->scanForBundles()      (vendor/zikula/extensions-module/Controller/ExtensionController.php:84)   at Zikula\ExtensionsModule\Controller\ExtensionController->listAction(object(Request), object(TraceableEventDispatcher), object(ExtensionRepository), object(BundleSyncHelper), object(I18nRouter), 1)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:157)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:79)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:196)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (public/index.php:35)

## Possible Solution

[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

## Steps to Reproduce

[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )

1.
2.
3.

## Context

[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
[TIP]: # ( If this involves a rather complex scenario maybe attach your `.mostapp` model file )

**Comment by Guite** [comment]
Closing, since this is not a generator issue (as you also experience the same problem with Scribite which is not generated).
Keeping the News issue open for further investigation.
