### ISSUE TITLE
Suche mittels auto-completion wirft einen Fehler auf der Console (404 für indicator_arrows.gif)

### ISSUE THREAD

**Issue by MisterFau** [Guite/MostGenerator#1248]
| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | latest
| Operating System       | Windows
| Zikula Target in Model ZK30
| Zikula Version         | 3.0.3
| PHP Version            | 7.4.x

## Expected Behavior

Die Suche mittels auto-completion sollte keinenjFehler werfen

## Current Behavior

Bei der Suche mittels auto-completion wird ein Bild "indicator_arrows.gif" nicht gefunden. 

style.css:1 GET http://www.webseitenonline.de/public/modules/zikulausers/images/ajax/indicator_arrows.gif 404 (Not Found)

![image](https://user-images.githubusercontent.com/31589951/94361958-4108a480-00b8-11eb-873d-6ff39def0ee9.png)

**Comment by Guite** [comment]
Lösche mal die Datei `public/modules/faumandunkwards/css/style.css`, damit sie neu vom Modul dahin kopiert wird. Danach sollte das Problem gelöst sein. Denn der Fix dafür ist bereits in 4b7efaa60d26cb5e9470727abcc64cc3b88a6b35 mit drin gewesen.

**Comment by MisterFau** [comment]
Passt. Danke.
