### ISSUE TITLE
DateTimeInterface, when add/edit, null returned

### ISSUE THREAD

**Issue by KratorD** [Guite/MostGenerator#1258]
I have created a new extension in MOST (staging version).
[LaTorre.zip](https://github.com/Guite/MostGenerator/files/6154614/LaTorre.zip)

For the entity "gratitudes", when I try create a new record (press button + Create gratitude /latorre/admin/gratitude/edit), immediately I got the error Return value of TdM\LaTorreModule\Entity\Base\AbstractGratitudeEntity::getTheDate() must implement interface DateTimeInterface, null returned
File: TdM\LaTorreModule\Entity\Base\AbstractGratitudeEntity.php (line 183)
public function getTheDate(): \DateTimeInterface { return $this->theDate; }

| Q                      | A
| --------------------   | ---
| ModuleStudio Version   | [Staging version]
| Operating System       | [Windows]
| Zikula Target in Model | [ZK30]
| Zikula Version         | [3.0.x]
| PHP Version            | [7.3.14]

## Expected Behavior
I hope create a gratitude entity.

## Current Behavior
Error is returned

## Steps to Reproduce

1. Admin
2. Create a gratitude
3.

**Comment by Guite** [comment]
Closed as explained in #1257
