### ISSUE TITLE
Generate MultiHook needles

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#13]
## Description of the new feature
All generated modules should offer MultiHook needles.

## Feature Benefits
Easy and consistent way to link stuff in content.

## Supported types

  1. view link
`<MODNAME>-<OTPLURAL>`
  2. display link
`<MODNAME>-<OT><ID>`

## See also
  * [MediaAttach](http://code.zikula.org/mediaattach/browser/trunk/MediaAttach/pnneedleapi)

**Comment by robbrandt** [comment]
👍

**Comment by rallek** [comment]
Multihook is still alive?

**Comment by Guite** [comment]
We'll see...
