### ISSUE TITLE
Add support for hook providers

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#15]
It should be possible to model and generate hook provider implementations.
Implement only for 1.5 and 2.0.

- [x] Extend DSL and textual grammar
- [x] Documentation
- [x] implement filter hooks provider
- [x] implement form aware hook provider
- [ ] Finish implementation of UI hooks provider
    - [x] Add hook assignments entity
    - [x] Implement `module.remove` event subscriber
    - [x] Use templates for all display hook methods
    - [x] Link assignment owners in display pages (store `subscriberUrl` using `RouteUrl#serialize()`)
    - [x] means for removing assignments on demand
    - [ ] means for adding new assignments (auto completion and inline creation; exclude already assigned entities)

**Comment by robbrandt** [comment]
@craigh your links above are broken.  I think these are what you referenced:

https://github.com/zikula-modules/DizkusModule/tree/master/AbstractHookedTopicMeta.php
https://github.com/zikula-modules/DizkusModule/tree/master/HookedTopicMeta

**Comment by rallek** [comment]
I would love this feature ;-)
