### ISSUE TITLE
Add fieldtype "regularly date"

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#229]
I'd love to have a field which works like this:
http://de.wikipedia.org/wiki/Cron#Beispiele

 I wanted to program a worship module with MOST. There are worships which are every Sunday at 10 o'clock. It would be great to have such a field, storing these information.

**Comment by Guite** [comment]
http://symfony.com/blog/new-in-symfony-3-2-dateinterval-form-type

**Comment by craigh** [comment]
PC has some "repeating" event functionality which sounds similar. Storage would be wise to copy iCal
