### ISSUE TITLE
Consider association objects in sub forms

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#3]
The generator can integrate forms with relation objects. For example we could create a form with customer data including address data.

For 1-to-1 relationships this seems even more interesting than inline editing using modal windows.

DSL tasks:
- [x] Introduce `sourceEditing` and `targetEditing` properties for join relationships
- [x] deprecate `editType` property
- [x] update grammar
- [x] update formatter
- [x] update validation constraints to prevent undesired settings (e.g. embedded for multi-valued sides)
- [x] update docs (validation reference)
- [x] update docs (generator reference)

Tooling tasks:
- [x] update property mappings

Generator tasks:
- [x] update existing occurences of old `editType` property
- [ ] implement `EMBEDDED` enum value (see [Symfony docs](http://symfony.com/doc/current/form/embedded.html))

**Comment by rallek** [comment]
Would be pretty cool
