### ISSUE TITLE
Provide ui for version management

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#30]
- [x] Exclude version fields from editing
- [x] Show link to `version history` together with current version
- [x] Add change history page
- [x] Mark current version
- [x] Allow viewing previous versions (revert without flush + detach)
- [x] Allow reverting to a previous version
- [x] Avoid deleting old upload files for loggable entities
- [x] Add a trash section for deleted entities
- [x] Allow viewing deleted entities
- [x] Allow undeletion of deleted entities
- [x] Diff views for comparing versions
- [x] Update documentation including screenshots of history page and diff view

**Comment by Guite** [comment]
@robbrandt you might watch this issue since it is probably also very interesting for you, isn't it?

**Comment by robbrandt** [comment]
Thanks

**Comment by Guite** [comment]
Note this feature is generously sponsored by @gfr . Thanks for that!
