### ISSUE TITLE
Make it possible to set only the default language to required

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#338]
Let's say I have a text field `description` and set it to `translatable = true` and `required = true`. On the example website, I then have two languages, German (secondary) and English (primary). Now everyone creating an object has to insert the German and the English description. It would be a nice feature if there is an option that you **have to** insert the website's default / primary language and the secondary language is **not required**.
Everywhere where this `description` is displayed, it then checks if it was translated to the not-required secondary language and if not, displays it's primary-language text.

**Comment by Guite** [comment]
Closed as merged into #177.
