### ISSUE TITLE
Strange phenomenon with geographical field

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#347]
If I wish to create an new issue, I get this.

![geo](https://f.cloud.github.com/assets/493707/855591/c43c513c-f529-11e2-928f-82586cbe76f6.jpg)

The map does not show any pictures and does not have the navigation to zoom in and out.
![geo2](https://f.cloud.github.com/assets/493707/855614/b8c65fe0-f52a-11e2-95d7-d45491317eab.jpg)

ZIK135

**Comment by Guite** [comment]
@Portugao could you check if this problem is still present?

**Comment by Guite** [comment]
Closed, as geolocation isn't active by default anymore.
