### ISSUE TITLE
pagesetvar doesn´t work in the view.tpl

### ISSUE THREAD

**Issue by trichers** [Guite/MostGenerator#355]
I have this tag in the view.tpl
{gt text='Sections' assign='templateTitle'}
{pagesetvar name='title' value=$templateTitle|@html_entity_decode}

but it doesn´t change the title-tag

In the display.tpl it works fine

How can I fix it?

**Comment by Guite** [comment]
Closed as invalid. It should work also if you delete the cache after you did the change.
