### ISSUE TITLE
Add support for authentication interfaces

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#361]
Please make it possible to add the Authentication controller to a module with the authentication-functions skeleton in it.

**Comment by Guite** [comment]
This is probably going to be done for 1.4/2.0 only using the new interfaces contributed by @craigh

**Comment by Guite** [comment]
https://github.com/zikula/core/tree/1.4/src/docs/Core-2.0/UsersAndAuthentication
