### ISSUE TITLE
[ZK-136][WebGen] Translatable bugs

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#386]
- Create an object with translatable files
- While creating, do something that the form is not valid
- Click onto submit
- Page will reload because your form is not valid
- All translatable fields are empty now

The same if you edit an object with translatable fields _for the first time_. The translatable files are empty. If you than insert something, save, and click edit again, all works fine.

**Comment by rallek** [comment]
has this to do with #771?

**Comment by Guite** [comment]
This is probably fixed for the 1.4.x implementation. I nevertheless merged this problem into #177 to review/test it explicitly. Closing in favour of #177.
