### ISSUE TITLE
Improve var-container

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#390]
Add an option to each var-container to set the "namespace".
Example:
I have a var container called "loginProvider" and a var container called "registrationProvider". In "loginProvider", there are the variables "loginProviderTwitter" and "loginProviderFacebook". In "registrationProvider", there are the variables "registrationProviderTwitter" and "registrationProviderFacebook". This generates the following db entries:
- `loginProviderFacebook` = `''`
- `loginProviderTwitter` = `''`
- `registrationProviderFacebook` = `''`
- `registrationProviderTwitter` = `''`

These are not easy to fetch if I want to get all registration provider settings.

Solution: Allow "namespaces". In this example, I would set the "namespace" of the "loginProvider" container to "loginProvider", the "namespace" of the "registrationProvider" container to "registrationProvider". The variables in both containers would be called "facebook" and "twitter". This should result in the following db entries:
- `loginProvider` = `array(facebook => '', twitter => '')`
- `registrationProvider` = `array(facebook => '', twitter => '')`

**Comment by Guite** [comment]
@craigh any idea about to achieve this?

**Comment by craigh** [comment]
that is what `\Zikula\ThemeModule\Engine\ParameterBag` does. but that needs to be recoded.

**Comment by craigh** [comment]
refs https://github.com/zikula/core/issues/3298

**Comment by Guite** [comment]
I think I'll add a flag like `composite`. If this is set to `true` a modvar named like the var container's name is used containing the single variables as array elements like shown by @cmfcmf above. By reusing the container name no additional text is required, as it would be equal anyway.
