### ISSUE TITLE
Adopt Symfony forms

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#416]
This is a blocker, because the old forms can not be used with new controllers.

To do:
- [x] config
- [x] delete
- [x] block editing
- [x] external finder
- [x] content type editing and external selector (reverted to Smarty; not ready for Twig yet)
- [x] view mass handling (skipped)
- [x] quick navigation
- [x] edit types and form handlers
- [x] inheritance for edit types
- [x] relation handling in edit types

**Comment by Guite** [comment]
https://github.com/zikula/core/pull/2447

**Comment by Guite** [comment]
Maybe interesting: https://github.com/jeanlucc/sf-form-collection-js

**Comment by Guite** [comment]
This has become a blocker now, because the old forms can not be used with new controllers.

**Comment by rallek** [comment]
if it is a blocker the label should be readded ;-)

Have to wait now until this is fixed.

**Comment by Guite** [comment]
There is no `blocker` label in this repository.
There is only `blocked` which is used for issues where something in the core needs to be done first.
