### ISSUE TITLE
create an module specific admin.png and editor.png

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#458]
isn't it possible to create an specific icon for admin and editor plugins automatically?

e.g. for admin.png
![admin](https://f.cloud.github.com/assets/935250/1819375/08f62a5c-7089-11e3-9509-c29da9a33742.png)
just use the current admin.png, make it smaller and add a kind if initials. There should be a possibility in java to create this png file

and here an icon for the editor:
![editor](https://f.cloud.github.com/assets/935250/1819378/4ebfcd22-7089-11e3-8063-19abf863c7fb.png)

**Comment by Guite** [comment]
The question here is how to derive the initials.
If you have for example vendor `MyCompany` and application `VerySimpleApp` then we have many possibilities:

* MV
* VSA
* MCV
* MVSA
* MCVSA

I'd keep it simple and use the first letter of both vendor and application (MV for the example above).

Opinions?

**Comment by Guite** [comment]
Another question is how to determine the background colour.

* always use the same colour (which one?)
* configurable in the model
* random
* ...

**Comment by rallek** [comment]
Two capitals are great. My proposal would be always use the last capital of vendor and application. In your example it would be CA. This would help Michael a lot because all of his apps are starting with MU e.g. ``MUExample``

Background always transparent and text in black. And if this is a problem make it always white and store another one with white letter and black background so it can easily be changed manually by changing file names. Or create all three and choose the transparent as default.

**Comment by Guite** [comment]
> My proposal would be always use the last capital of vendor and application. In your example it would be CA. This would help Michael a lot because all of his apps are starting with MU e.g. MUExample

I disagree with this point. The MU prefix in the application name is legacy. Correct would be having only the vendor MU and the application name Image.

How about this:

* If the application name contains more than one capital use the first and the last one of it. Example: VD for VerySimpleDownloads.
* Otherwise use the first capital of the vendor and the capital of the application name. Example: GN for Guite / News.

**Comment by rallek** [comment]
VD sounds good!

**Comment by Guite** [comment]
Nice side effect: For `MU/MUImage` this results in `MU`(rule 1). If Michael removes the MU prefix from the application name somewhen it is still `MU` (ruie 2) :smile:

**Comment by Portugao** [comment]
What about the upgrade path?

**Comment by Guite** [comment]
Similar like the methods which are generated for upgrading a module from 1.3.x to 1.4.x. Because this includes a rename, too (for example from `MUImage` to `MUMUImageModule`).

**Comment by Guite** [comment]
Example for `Zikula\Multisites`:

![admin](https://cloud.githubusercontent.com/assets/277531/18610096/1628e73e-7d13-11e6-96fc-3a7ac478e807.png)
![admin_b](https://cloud.githubusercontent.com/assets/277531/18610098/1ad359c2-7d13-11e6-98ff-601895411ead.png)
![admin_w](https://cloud.githubusercontent.com/assets/277531/18610099/1ecb5bd8-7d13-11e6-9e23-c82b3062eabd.png)

**Comment by Guite** [comment]
And the Scribite editor plugin images:

![multisites_b](https://cloud.githubusercontent.com/assets/277531/18610170/7732c9d0-7d15-11e6-86d7-752def2943c6.png)
![multisites_w](https://cloud.githubusercontent.com/assets/277531/18610171/773d01a2-7d15-11e6-9ee6-b72cb7dfbabb.png)
![multisites](https://cloud.githubusercontent.com/assets/277531/18610172/774b28ae-7d15-11e6-827c-dd2e39e66350.png)

**Comment by Guite** [comment]
Other examples from WebGen (MV is MUVideo btw):

![admin](https://cloud.githubusercontent.com/assets/277531/18610222/b3201ce4-7d16-11e6-8d79-7426e352f3e5.png)
![admin](https://cloud.githubusercontent.com/assets/277531/18610224/b529267a-7d16-11e6-8d09-b5cec7e0d4c5.png)
![admin](https://cloud.githubusercontent.com/assets/277531/18610225/b780b118-7d16-11e6-8f15-a67205325f41.png)

**Comment by Guite** [comment]
@rallek @Portugao @cmfcmf @craigh @robbrandt Wouldn't it look even better if the MOST icon was centered?

**Comment by Portugao** [comment]
Would be nice if the letters had the same width like the icon.

**Comment by rallek** [comment]
Centered or not doesn't matter for me. First it is important to have a different icon if you have two modules in development. Later everybody can create his own icon if he do not like this ones.

I am happy to see this implemented right now! Thanks Axel!

**Comment by Guite** [comment]
> Would be nice if the letters had the same width like the icon.

This would require using a font like Courier where all letters have the same width. At the moment Arial is used which looks a bit nicer imho.

**Comment by Guite** [comment]
Here is an example how it would look like if we'd center the icon:

![admin_b](https://cloud.githubusercontent.com/assets/277531/18624191/e7c5dd1e-7e45-11e6-90cf-383dce30e536.png)
![admin_w](https://cloud.githubusercontent.com/assets/277531/18624192/e7cdffb2-7e45-11e6-831d-9a73f8f8614d.png)
![admin](https://cloud.githubusercontent.com/assets/277531/18624193/e7d8ea12-7e45-11e6-8eb8-3b880bf06011.png)

**Comment by Guite** [comment]
Changed in d2a6f0f24e155da2c6aa1cb909360d1abe801118

**Comment by Guite** [comment]
Scribite editor plugins now reuse the admin icon. So if you customise the admin icons this is reflected inside Scribite editors automatically, too.
