### ISSUE TITLE
TinyMCE plugin (most probably) needs an update going from tinymce 3.x to 4.x

### ISSUE THREAD

**Issue by espaan** [Guite/MostGenerator#500]
Hi,

in SimpleMedia and current Scribite github having tinymce 4.0.x there need to be updates done to the plugin to make sure that it runs. Some calls have to be changed. 
In progress in SM2.

**Comment by Guite** [comment]
@espaan any idea about this one? My guess is that this is done already. Could you please check and report back?

**Comment by Guite** [comment]
Closed as probably done. Feel free to reopen or create a new issue if you encounter any problems.

**Comment by espaan** [comment]
good !
