### ISSUE TITLE
Re-work entity callbacks

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#624]
POSTLOAD
---------------
https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Entity/Base/AbstractRouteEntity.php#L889-L926

Currently, all the entity data is formatted for display, changed and altered *on every entity load!*. And it's based on *url arguments*. This causes lot's of problems as soon as entities of MOST modules are used by other modules or in different places. Example:
The routes module is loading it's entities in a RouteLoader to forward them to Symfony. This might happen on every page imaginable (so the page might have $func = null, $func = 'edit', $func = 'ashd', $func = ANYTHING). However, based on url arguments, the entity attributes are formatted for display (if GET $func != 'edit'). That's why I have basically disabled the callback: https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Entity/RouteEntity.php#L107-L116

PREPAREITEMACTIONS
--------------------------------
https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Entity/Base/AbstractRouteEntity.php#L1370-L1377

Same thing here: It relys on url arguments as well. In my case, it might happen that the routeentity is loaded *way before the MOST module is called*. This causes the item actions to be prepared (as the method is called in the postloadcallback). Later, when the MOST module is actually displaying the items, it does not recalculate them (but it should!) and doesn't display the correct actions.

PREREMOVE
-------------------
https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Entity/Base/AbstractRouteEntity.php#L1080

It might add flashmessages if the workflow is not available. It should rather throw an exception (which is caught when it's used inside the MOST module itself). At least I think so, but I'm not sure what's the best solution for the preremove callback.

**Comment by cmfcmf** [comment]
Additionally, the postLoadCallback->formatTextualFields has a huge performance impact on the Routes module, because it's done everytime route entities are loaded, although it isn't necessary in 99% of the cases.

**Comment by Guite** [comment]
refs #545

**Comment by Guite** [comment]
note to myself: refactor https://github.com/zikula/core/blob/1.4/src/lib/util/DataUtil.php#L201 to a Twig filter

**Comment by Guite** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ylUXUkgn&#x2F;7-624"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #624</a>

**Comment by Guite** [comment]
Done except item actions which are treated in #727
