### ISSUE TITLE
Remove lct support

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#633]
Follow-up from #628 @cmfcmf 

Support for view/edit/delete/display actions in user and admin controllers has already been forbidden in the validation layer.

Now $lct can be removed and replaced by appropriate permission checks.

**Comment by craigh** [comment]
recommend removal of `blocked` here and proceed with implementation of Controller Method annotations.

**Comment by Guite** [comment]
https://github.com/zikula/core/issues/2112

**Comment by Guite** [comment]
Questions about introducing the theme annotation like it is done here: https://github.com/zikula-modules/Pages/blob/master/Controller/AdminController.php#L45

1. Given a structure like this:
```
class PersonController extends AbstractController
{
    /** @Theme("admin") */
    public function adminView()

    public function view()

    /** for sharing common code parts */
    protected function viewInternal()
}
```
we need to have two different routes. If `persons/` (and `persons.xml`, `persons.csv`, `persons.rss` and so on) point to the `view` method, how should we name the `adminView` route? Would `admin/persons/` be appropriate?

2. The default admin route (linked in the Extensions list) can now be specified by the `admin` capability route which is linked here: https://github.com/zikula/core/blob/1.4/src/system/ExtensionsModule/Resources/views/Admin/view.tpl#L53
Do you think that we should point nevertheless keep an `module_admin_index` page for an easier customisability of the admin overview page? Otherwise we could also point to the index or view function of the leading entity of course and maybe get rid of admin and user controllers completely.

3. If the admin controller is still required (see 2.) then it makes not really sense to introduce a dedicated ConfigController for the settings page, does it? Also this would cause that `config` is no valid name for an entity or a custom controller anymore. Not sure here about the ideal approach yet.

**Comment by craigh** [comment]
1. Remember that the routes are usually prefixed by the module prefix, i.e. /pages/person and /pages/admin/person - and yes I think the route you proposed is appropriate.

2. The point of the capability routes is to eliminate the silly redirecting we do. So yes please eliminate the index method and name the method appropriately and indicate the new method in the capabilities array. There is no requirement for "Admin" or "User" controllers at all. Please see the SpecModule where neither is present.

3. I think this question is  moot in light of question 2 above

**Comment by Guite** [comment]
@cmfcmf do you have anything to add here?

**Comment by craigh** [comment]
Another point about SpecModule - those methods are named "index" which should be changed as a proper demo. I only meant SpecModule as an example of non user/admin controller names (currently)

**Comment by cmfcmf** [comment]
Nothing to add here, Craig summed it up pretty good.

**Comment by Guite** [comment]
Theme annotation feature has been implemented.
78f3018bad4b83a7015e1bcd74057bc16ffeb643
https://github.com/Guite/MostHelp/commit/45ffaf2aa37540244863f7b9fe416b3ddcbaf159
https://github.com/Guite/MostLocales/commit/e9f0caa058f9c7d67146b61e4b704b34588d27c9
