### ISSUE TITLE
[1.4.x] After install there are no routes created in the routes module

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#671]
So if i call the module i get redirected to the routes module.

**Comment by Guite** [comment]
For reference: this was tested with MUPolls.

**Comment by Portugao** [comment]
Yes. Model is on 'http://webgen.modulestudio.de'

**Comment by Guite** [comment]
Could you please retest using the latest 1.4 core revision?

**Comment by Guite** [comment]
Works.
