### ISSUE TITLE
Add support for Webshim and Polyfill

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#673]
The Zikula core 1.4.0 supports Webshim, which is a polyfill library that enables you to reliably use HTML5 features across browsers, even if native support is lacking.

1.4 target applications should be updated to take advantage of its features.

Refs. https://github.com/zikula/core/pull/2377

cc @shefik

**Comment by Guite** [comment]
Added loading of polyfill form features in aee407e33124661ca75ab959c41fab9aca7ddcc9

**Comment by shefik** [comment]
:+1:
