### ISSUE TITLE
Create 2.0.0 target

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#678]
MOST 0.7.0 should support a dedicated 2.0.0 target version.

See also:

* https://github.com/zikula/core/pull/2447
* https://github.com/zikula-modules/Pages
 * https://github.com/zikula-modules/Pages/pull/49/files
* #674

**Comment by craigh** [comment]
:+1:

**Comment by craigh** [comment]
also see implementation in ZikulaPagesModule

**Comment by Guite** [comment]
Target added without any further changes here:
https://github.com/Guite/MostGenerator/commit/29e84f289e03281e06afe64e3f29af5e4bcecc63
https://github.com/Guite/MostHelp/commit/4f75260acbbca932837443637a572239ad1d6ad4

**Comment by craigh** [comment]
The 2.0.0 Spec isn't finalized yet

**Comment by Guite** [comment]
This can be closed. Twig and Forms migration is done in #571 and #416
