### ISSUE TITLE
Deletion of several entries in view template does not work correctly with relations

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#679]
If i try to delete several entries in the backend, i get an workflow error message:

```
 Call to a member function initWorkflow() on a non-object in /domain/modules/MUFiles/lib/MUFiles/Controller/Collection.php on line 318

```

The reason seems to be that collections have a self-relation, so some of the entries are not there anymore, if the foreach loop is calling them....

Also the datas for the related items (here related collections) in the workflow table do not get deleted.

I don't know, if this issue is relevant anymore. I think so, if i look into the actual generated code.

**Comment by Guite** [comment]
It may be interesting if you could retest this using 1.4 :-)

**Comment by Portugao** [comment]
I would do, but depends on #906 .

**Comment by Guite** [comment]
Okay!
