### ISSUE TITLE
make the images responsive

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#681]
For a website project I am learning the new possibilities (e.g. html5) at least a little :-) by reading two books about modern layouts/webdesign.

I found the following for images:
https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset

With this you can specify which sizes picture is delivered in relation to the screen size. Might be good feature in future.

The usage of the browsers is not that big at the moment but increasing: http://caniuse.com/#search=srcset

For MOST this means it should deliver three sizes of pictures (small for handhelds like smartphones, middle for tablets/netbooks and large for bigger screens). In templates you than have to use the new possibilities of the img tag.

**Comment by Guite** [comment]
Sounds like a bit too specific for a generic support in the DSL. MOST allows you to create three upload fields and use them like you want. You could also use the `hidden-*` and `visible-*-block` classes from bootstrap: http://getbootstrap.com/css/#responsive-utilities So at the moment I doubt such a feature will make it into the generator.

**Comment by Guite** [comment]
cc @espaan @cmfcmf

**Comment by rallek** [comment]
It is not an boostrap issue ;-)

Mobile devices should not get the big images. smaller ones would save kb in transfer and make sites faster!

And yes, this is an issue for the future

**Comment by rallek** [comment]
As Zikula is doing manly a very good job in caching different file sizes per image, this feature request si not important anymore

**Comment by rallek** [comment]
mmh, closing was not my proposal, because that are two different things. Depending on the "screen" we have to deliver different image sizes. It was just my feedback that tis is even in future not the first to do ;-)

**Comment by Guite** [comment]
Closing as "won't fix". You can do this in your template if you like by generating multiple thumbnail images with different sizes. But I won't add this to the generator for general purpose.
