### ISSUE TITLE
Filtering the categories

### ISSUE THREAD

**Issue by FRWo** [Guite/MostGenerator#682]
It comes from MUFiles, made with ModuleStudio:

There seems to be a problem with the categories, because I cannot do a filter with subcategories.

The categories are shown, but I get only “Keine Kollektionen gefunden”, so the only way to see any collections is filter with “all”

**Comment by Portugao** [comment]
@FRWo 
I think we can close this issue?!

**Comment by FRWo** [comment]
Yes, so do I – thank you

 

Von: Michael Ueberschaer [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. Juni 2015 10:46
An: Guite/MostGenerator
Cc: Frank
Betreff: Re: [MostGenerator] Filtering the categories (#682)

 

@FRWo <https://github.com/FRWo>  
I think we can close this issue?!
