### ISSUE TITLE
[1.4.x] 1:n relation - dropdown in target edit form gives error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#683]
```
Notice: Array to string conversion in domain/lib/legacy/Zikula/Form/AbstractStyledPlugin.php on line 75
```
I cannot send the form.

**Comment by Guite** [comment]
Can you tell me how to reproduce this? Which entity did you edit from which model?

**Comment by Portugao** [comment]
Should be the model of MUPolls saved in the webgen.

**Comment by Guite** [comment]
Blocked by #416

**Comment by craigh** [comment]
![screen shot 2015-12-10 at 9 09 11 am](https://cloud.githubusercontent.com/assets/350048/11717308/b766fffc-9f1d-11e5-90ab-2e3cdd2ee808.png)

![250px-flag_of_germany svg](https://cloud.githubusercontent.com/assets/350048/11717321/d5c38f42-9f1d-11e5-90d0-7b915e866cc5.png)

tell me you didn't do that on purpose :stuck_out_tongue_winking_eye:

**Comment by Guite** [comment]
LOL at least we now know how this flag was created :-)

**Comment by craigh** [comment]
yes, it was a bug report! :laughing:

**Comment by cmfcmf** [comment]
:de:

**Comment by Guite** [comment]
Closing this one, because editing is completely changed for 1.4 apps in #416 anyway.
