### ISSUE TITLE
[1.4.x] datetime field not possible to edit

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#684]
Edit:
If i delete the datetime, the actual datetime get saved.
The field is not mandatory.

**Comment by Guite** [comment]
Please confirm again: is this a `datetime` or a `date` field?
For `datetime` fields there is no custom form plugin used, so maybe it is a core issue?

**Comment by Portugao** [comment]
Hmmhmm..if i'm right, it is a datetime field.
I should test with actual core; not sure if i get time this year.....

**Comment by Guite** [comment]
Closing this one, because editing is completely changed for 1.4 apps in #416 anyway.
