### ISSUE TITLE
Option for generating separate user templates

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#685]
Perhaps there could be an entity setting that lets the developer decide whether to use the current format of having one entity for both admin and user areas, or to use:

```
{if $lct ne 'admin'}
    {include file='myEntity/myUserTemplate.tpl'}
{else}
    default stuff
{/if}
```

where myEntity/myUserTemplate.tpl is the same template as default, as a starting point.  It's not a big change to do manually but it's one less customization to manage.

cc @robbrandt

**Comment by rallek** [comment]
the current version of webgen seems not to create User-Templates anymore

**Comment by Guite** [comment]
Reasonable when you did not add a user controller to your model.

**Comment by rallek** [comment]
ups

**Comment by rallek** [comment]
Ok, now I have the user templates :-)

Thinking about this discussion issue: I will very often have two different layouts for user and for admin. The user will become some reduced boostrap layouts while the admin should have the current full table version. I think I will not use this option very often (with my current thinking).

**Comment by Guite** [comment]
By default templates are generated into `Resources/views/MyEntity/myAction.html.twig`.
If we now add a generator setting like `generateSeparateTemplatesForFrontendAndBackend` (need to find a more precise name), how should this look like? Maybe `MyEntity/myAction.html.twig` and `MyEntity/Admin/myAction.html.twig`?

@robbrandt @rallek @gfr @portugao @craigh

**Comment by rallek** [comment]
Why not name it ``generateExtraAdminTemplates`` or ``separateAdminTemplates`` or even more simple ``adminTemplates``. Than ``MyEntity/Admin/...`` would be logical.

or do it in oposite: ``userTemplate``?

Do you plan this setting for each entity separate or general for the generated module?

**Comment by Portugao** [comment]
```
seperateAdminTemplates
```
would be fine.

**Comment by Guite** [comment]
One general setting.

**Comment by Guite** [comment]
- [ ] Introduce new generator setting named `separateAdminTemplates` in the DSL (default value `false`)
- [ ] Add new setting to documentation
- [ ] Update template paths in controllers and view helper
- [ ] Update template generation logic
- [ ] Update affected include statements
- [ ] Update base layout templates
