### ISSUE TITLE
Replace all system module paths

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#686]
1. All paths referencing system modules, like refs https://github.com/zikula/core/issues/2578
2. All js / css paths of generated modules with the systemModule flag set.

example from inlineRedirectHandler.tpl: 
`<script type="text/javascript" src="{$baseurl}system/ZikulaRoutesModule/Resources/public/js/ZikulaRoutesModule.EditFunctions.js"></script>`
-->
`<script type="text/javascript" src="{$baseurl}system/RoutesModule/Resources/public/js/ZikulaRoutesModule.EditFunctions.js"></script>`

**Comment by Guite** [comment]
point 1 is done in https://github.com/Guite/MostGenerator/commit/731ec6184f8ed2339847616710643a9ba10e2be3
point 2 needs to wait a bit

**Comment by cmfcmf** [comment]
Thanks :+1:

**Comment by craigh** [comment]
something like this would be more appropriate in Smarty

`{pageaddvar name='javascript' value='@ZikulaRoutesModule/Resources/public/js/ZikulaRoutesModule.js'}`

use `{{ pageAddAsset() }}` in Twig.

**Comment by cmfcmf** [comment]
But don't just refactor blindly to `{{pageAddAsset`, because it behaves differently than `{pageaddvar`, as it doesn't preserve the order of the assets if you don't provide different weight parameters.

**Comment by Guite** [comment]
Fixed in https://github.com/Guite/MostGenerator/compare/d876310c7a1494be96c388ed79e30afd73876be3...1f806af0e77fc88f4c7b2fc8ffb87a5419f74db2
