### ISSUE TITLE
HookAreaPrefix wrong

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#690]
Currently `routes.x.x` is generated, but it should be `zikularoutesmodule.x.x` in 1.4.

https://github.com/Guite/MostGenerator/blob/2fbd823b91f4a6bd2f947f738b6389870376f344/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/models/entity/EntityMethods.xtend#L395

**Comment by Guite** [comment]
Fixed in 86f7089afdced8b5831a48a653b7a1c9965e71c1
