### ISSUE TITLE
search function is not working for target ZK1.4

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#696]
I made a very simple pages module (Title and description) by MOST with target ZK1.4. 

I added some data and tried to find them via searching function of zikula. The MOST module is listed in the search site but no result is shown.

**Comment by rallek** [comment]
seams not to be most:
https://github.com/zikula/core/issues/2643

Or now I have found another problem with search

**Comment by Guite** [comment]
Fixed in d876310c7a1494be96c388ed79e30afd73876be3

**Comment by craigh** [comment]
Is the core ticket valid or not?

**Comment by Guite** [comment]
I think it is, but I did not experience that issue. @rallek meant it could be related to Profile being activated. Sorry, don't know exactly.
