### ISSUE TITLE
Util services cannot extend legacy classes

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#701]
Util service cannot extend legacy classes like Zikula_AbstractBase

refs https://github.com/zikula/core/issues/2507

see https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Util/Base/ControllerUtil.php#L22

This is because in the constructor the class requires the `Request` object and this is not available when using CLI (or other means).

IMO, services should be 'clean' and not extend ANY legacy class if at all possible. If certain methods are needed, perhaps write a new base class or inject needed services directly.

cc/ @cmfcmf

**Comment by craigh** [comment]
@Guite can you please look more closely at this asap as it relates to 

https://github.com/zikula/core/pull/2576

That PR can't be finished until this issue is resolved. Thanks

**Comment by Guite** [comment]
One question about this: what to do if the request object is needed in a certain method? This means that it can not used with CLI automatically, right?

**Comment by craigh** [comment]
I imagine it should be delivered to the method as an argument.

```php
class MyClass
{
    public function myMethod(Request $request)
    {
        // do something with Request
    }
}
```

**Comment by craigh** [comment]
A better idea would be to only deliver the properties of the object that you need

```php
class MyClass
{
    public function myMethod($aProperty)
    {
        // do something with $aProperty
    }
}

MyClass::myMethod($request->aProperty);
```
This is a better approach IMO and is more easily testable.

finally, if you *must* have the entire object you could also make your Util class a service and inject it on construction. See other symfony services through the core for examples.

**Comment by cmfcmf** [comment]
You should really try hard to remove as many dependencies to the request and FormUtil as possible.

**Comment by Guite** [comment]
Refactoring done in d8c737d55cc08c10e21b813f9cedb72c49c04df5
