### ISSUE TITLE
Use SortableColumns component

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#706]
https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/SortableColumns.md

**Comment by Guite** [comment]
@craigh is this component used somewhere already?

**Comment by craigh** [comment]
https://github.com/zikula-modules/Pages/blob/master/Controller/AdminController.php#L68-L77

plus a little before and after. look at the whole controller.

**Comment by Guite** [comment]
Added basic implementation in 357c692b93f613f05ce9ff4646333e0d09626efe
