### ISSUE TITLE
Advanced thumbnail cropping options

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#712]
https://github.com/stojg/crop

**Comment by cmfcmf** [comment]
It would be great if the entropy based cropping could somehow be included in the Imagine plugin. Then I could also use it for the MediaModule.

**Comment by Guite** [comment]
refs https://github.com/zikula/core/issues/3388

**Comment by Guite** [comment]
refs https://github.com/zikula/core/issues/3438

**Comment by Guite** [comment]
Closing as "won't fix" in favour of imagine and because the referenced library works only with imagick.
