### ISSUE TITLE
Remove controllers

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#715]
Historically a model contained 1. controllers with actions and 2. entities - both were strictly separated from each other.

When routing was adapted the concept _entity controllers_ was introduced in addition.​ This means that during modeling (and therewith on a more abstract level than implementation) an entity element represents not only the actual entity class, but also a corresponding entity controller class (so a `Person` entity in the model results in both a `PersonEntity` class and a `PersonController` class). So currently you can not only add fields and indexes to an entity element, but also actions.

The default actions (view, display, edit, delete) are now forbidden by validation for admin/user/custom controllers. They are only allowed for ajax controllers and entities. Index and custom actions are allowed for all controllers.
​
When thinking this further: if all module's actions are treated by entity controllers anyway does adding admin and user controllers to a model still makes any sense?
Now that all default actions are handled by entity controllers anyway, do we still need the ability for modeling admin/user/ajax/custom controllers? Do we still want to be able to define additional controllers in a model or not?
The only use case I can imagine for admin/user/ajax/custom controller elements in the model is adding additional custom actions. But the generator can not really create much for these.

Thus I am thinking about whether it would be reasonable to remove controller elements completely from the dsl. There would be no admin/ajax/user/custom controller elements in the model anymore, but action elements could be added only to entities (read entity controllers).

Of course an admin controller or an ajax controller class could still be generated also without having corresponding elements in a model (in case they are needed). In the same way the generator already generates a config controller class handling the configuration page if any variables are contained in a model.

So maybe it is a good idea to remove these additional controller elements from the dsl. When we remove/disallow admin and user controllers from the dsl this leads to another benefit, too: a model can then also contain entities named `admin` or `user` which of course can contain actions.

So I will change validation for 0.7 to disallow admin, user and ajax controllers completely. They will still be part of the dsl for now in order to keep 1.3.x support working. In a later version they will be removed completely.​ This removes much redundancy in the generator I am currently treating, too.

Summary of proposed changes:

- [x] UI
  - [x] Remove tools for creating controller elements
  - [x] Customise initially precreated model when starting a new project
  - [x] Update model migrator
- [x] Validation
  - [x] Controllers are deprecated
  - [x] Remove all other controller-related validation rules
  - [x] Entity may be named `admin` or `user`
  - [x] `config` and `ajax` are still forbidden names for entity elements though
  - [x] A model is allowed to have no controller elements
- [x] Generator
  - [x] Generator still creates a config controller if needed
  - [x] Generator still creates an ajax controller if needed (always)
  - [x] Remove all references to controller elements from model2model transformation
  - [x] Remove all references to controller elements from generator templates
  - [x] Cleanup link container implementation
  - [x] Cleanup item actions implementation
  - [x] Fix todo markers referencing #715

**Comment by rallek** [comment]
I am not shure if I understand right. With ajax and custom I never have had an idea what they are doing. I only know I do need the ajax. Users is responsible for the frontend and admin for backend. If it means we will not have no backend anymore I do not like your proposal. I do like the possibilities to have different views for admin and users.

**Comment by Guite** [comment]
Admin and user controllers are already replaced by entity controllers. This issue is only about whether we could still need them for other things.

**Comment by rallek** [comment]
Ah! Ok I do not understand the differences. But if frontend and backend are still available I am happy with your proposal :-)

**Comment by craigh** [comment]
I am also not sure I understand. 

> entities are consequently acting as controllers only.

entities are not controllers. perhaps you mean something different? Separation of concerns dictates that the entity should be "dumb" and only represent an object (which doctrine can use to persist). The entity shouldn't "do" anything.

**Comment by Guite** [comment]
What I meant is that during modeling (and therwith on a more abstract level than implementation) an entity element represents not only the actual entity, but also the corresponding entity controller. You can not only add fields and indexes to an entity, but also actions. The generator accordingly creates a controller class for each entity element.

**Comment by craigh** [comment]
so the actual entity class doesn't do all that stuff, right? It shouldn't.

when the module is generated it separates the fields, indexes, and **actions** into another class - a controller? maybe a generated example would help me understand...

**Comment by Guite** [comment]
Entity class: https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Entity/Base/AbstractRouteEntity.php
Entity controller class: https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Controller/Base/RouteController.php

**Comment by Guite** [comment]
Basic subject of this issue is now that all default actions are handled by entity controllers anyway, do we still need the ability for modeling admin/user/ajax/custom controllers.

**Comment by craigh** [comment]
IMO, doing things like [this](https://github.com/zikula/core/blob/1.4/src/system/RoutesModule/Entity/Base/AbstractRouteEntity.php#L1318-L1319) in an entity class are a bad idea. Entities should be 'dumb' representations of a persist able object.

I'm still not sure I understand the subject of this ticket. I think @cmfcmf would understand my position and yours better than I am explaining it and maybe his opinion will improve my understanding.

**Comment by Guite** [comment]
This is going off-topic.

The point of this issue is: do we still want to be able to define additional controllers in a model or not?

**Comment by Guite** [comment]
Historically a model contained 1. controllers with actions and 2. entities - both were strictly separated from each other. When routing was adapted entity controllers were introduced in addition.
​
This is basically the same like Craig's new controller in the BlocksApi branch:
https://github.com/zikula/core/blob/BlockApi/src/system/BlocksModule/Controller/BlockController.php

With these entity controllers also the dsl was accordingly enhanced, so in the model you now add actions to entity elements, too. And default actions (view, display, edit, delete) are forbidden by validation for admin/user/custom controllers. They are only allowed for ajax controllers and entities now. Index and custom actions are allowed for all controllers.
​
Now this issue is simply about thinking this consequently further. If all module's actions are treated by entity controllers anyway why adding admin and user controllers to a model? Of course an admin controller can be generated also without having such a model element in the model (for the config page for example). Similarly the ajax controller can also be generated without having to add it to the model. The only use case I can imagine for admin/user/ajax controller elements in the model is adding additional custom actions. But the generator can not really create much for these.

Thus Craig agreed it is a good idea to remove these additional controllers from the dsl. When we remove/disallow admin and user controllers from the dsl this leads to another benefit, too: a model can then also contain entities names admin or user.

So I will change validation for 0.7 to disallow admin, user and ajax controllers completely. They will still be part of the dsl for now in order to keep 1.3.x support working.

In a later version they will be removed completely.​ This removes much redundancy in the generator I am treating currently, too.

**Comment by Guite** [comment]
Summary:

In 0.7.0 validation will show errors for any of these controllers contained in a model.
In 0.7.0 there won't be palette tools for these elements available anymore.
In 0.7.1 (or 0.7.2) they will be removed from the dsl.

**Comment by cmfcmf** [comment]
> IMO, doing things like this in an entity class are a bad idea. Entities should be 'dumb' representations of a persist able object.

Indeed, but I think @guite is well aware that the entity classes are a big mess at the moment.



> So I will change validation for 0.7 to disallow admin, user and ajax controllers completely. They will still be part of the dsl for now in order to keep 1.3.x support working.
> 
> In a later version they will be removed completely.​ This removes much redundancy in the generator I am treating currently, too.

:+1:

**Comment by Guite** [comment]
Note: also remove last occurances of `lct` after #260 is done.
