### ISSUE TITLE
Support new Blocks Api

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#717]
https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/Blocks.md
https://github.com/zikula/SpecModule/tree/master/Block

Relates with #571 and #416

**Comment by craigh** [comment]
please wait until finalized and merged :smile:

**Comment by Guite** [comment]
Sure.

**Comment by Guite** [comment]
Implemented in 20fbc42b407ce06c36c0c5042e976647f7a19416
The moderation block is completely migrated to Twig, too.
The item list block is not using Twig and Sf Forms yet, I'll do this later.

One detail is still missing: accessing the block title as part of the permission checks.
