### ISSUE TITLE
noticed some small issues in MultiSites

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#728]
Several issues seen in phpStorm.

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 6 56 20 pm](https://cloud.githubusercontent.com/assets/350048/13338759/8d64bce2-dbf1-11e5-9106-b16379410bc7.png)

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 6 57 46 pm](https://cloud.githubusercontent.com/assets/350048/13338814/e8b5a3ea-dbf1-11e5-9331-54faf67cf7d9.png)

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 7 00 39 pm](https://cloud.githubusercontent.com/assets/350048/13338854/30394fb4-dbf2-11e5-8e9b-f5849160c7f3.png)

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 7 02 50 pm](https://cloud.githubusercontent.com/assets/350048/13338883/70a48cf8-dbf2-11e5-835d-0831b8299bf2.png)

**Comment by craigh** [comment]
that issue also present in 

\Zikula\MultisitesModule\Controller\Base\TemplateController
\Zikula\MultisitesModule\Controller\Base\SiteExtensionController
\Zikula\MultisitesModule\Controller\Base\SiteController

at the very bottom of each file

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 7 05 17 pm](https://cloud.githubusercontent.com/assets/350048/13338910/bcb5a122-dbf2-11e5-8844-0d66f9d74377.png)

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 7 06 19 pm](https://cloud.githubusercontent.com/assets/350048/13338921/df721bdc-dbf2-11e5-9060-71d006182e0c.png)

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 7 07 02 pm](https://cloud.githubusercontent.com/assets/350048/13338933/f98e5b48-dbf2-11e5-8d4b-628c9c43fe1e.png)

**Comment by craigh** [comment]
![screen shot 2016-02-25 at 7 10 43 pm](https://cloud.githubusercontent.com/assets/350048/13339033/9da73a60-dbf3-11e5-91d1-7a71b43054cc.png)

**Comment by craigh** [comment]
many times in docblock comments, you use a class string like so:

`* @param Doctrine\ORM\QueryBuilder $qb        Query builder to be enhanced.`

but PhpStorm highlights it as an error because it cannot find the class. you need to proceed the class with `\` in this cases:

`* @param \Doctrine\ORM\QueryBuilder $qb        Query builder to be enhanced.`

or import the class at the top and use the alias:

`use Doctrine\ORM\QueryBuilder;`
`* @param QueryBuilder $qb        Query builder to be enhanced.`

**Comment by craigh** [comment]
I guess I am done doing this for now. I only got about one-third of the way of simply scanning the files.

you can do the same and continue - All you need to do is open the files in PhpStorm and it will show you all the errors.

**Comment by Guite** [comment]
Great, thank you! Will care for these asap.

**Comment by Guite** [comment]
Fixed in https://github.com/Guite/MostGenerator/commit/7a951d7813483916f534c04b5bfd1011c28d6ccf and https://github.com/zikula-modules/Multisites/commit/f8d7f62269919460b428c5cc76e8b6959a97dae5
