### ISSUE TITLE
[1.4.x] method not found

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#737]
![undefinierte methode](https://cloud.githubusercontent.com/assets/493707/14913145/23419686-0e01-11e6-93be-63f9b2e897dd.jpg)
I get this if i try to install.

**Comment by Portugao** [comment]
Seems not to be an issue of MOST.
Same with other modules...

**Comment by Guite** [comment]
Going to fix that.

**Comment by Portugao** [comment]
I deleted the module and tried to install the legale module. I get the same error message. Also with the profile module.

**Comment by Guite** [comment]
As said above: I am going to fix that.

**Comment by Portugao** [comment]
143.build 29

**Comment by Portugao** [comment]
Ok.

**Comment by Guite** [comment]
Fixed by this change: https://github.com/zikula/core/pull/2874/files
