### ISSUE TITLE
[1.4.x] Trying to install gives new error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#745]
```
FatalErrorException in AppSettingsType.php line 219:
Parse Error: syntax error, unexpected '''' (T_CONSTANT_ENCAPSED_STRING), expecting ']'

```

**Comment by Portugao** [comment]
The tables get installed.

**Comment by Portugao** [comment]
Have to check again...

**Comment by Guite** [comment]
```
                intVar "fileSize" {
                    value "\'\'"
                },
```
Please change the default value to something reasonable, like an empty string or `0`.

**Comment by Portugao** [comment]
With a list var this solution does not work; equal I enter ('', ""), the code looks like
```
        $this->setVar('groupForCommonAlbums', );
```
and this gives an error.

**Comment by Guite** [comment]
Just enter nothing as default value. The generator cares for quotes automatically.
Also you can mark list items as `default`.

**Comment by Portugao** [comment]
I will see; Thx.
