### ISSUE TITLE
unexpected comma in composer.json

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#762]
This bug prevents modules from showing up in the Extensions page.

"," unexpected

It precedes the "hook subscriber" in

 "capabilities": {
                "user": {"route": "botanyorgconferencemodule_user_index"},
                "admin": {"route": "botanyorgconferencemodule_admin_index"},
                "searchable": {"class": "Botanyorg\\ConferenceModule\\Helper\\SearchHelper"},
                , "hook_subscriber": {"class": "Botanyorg\\ConferenceModule\\Container\\HookContainer"}
            },

**Comment by Guite** [comment]
Fixed in 1faf7a1e381c824193b79ce5232cabe99a1ec704
