### ISSUE TITLE
FatalErrorException in EditHandler.php line 243: Parse Error: syntax error, unexpected '$logger' (T_VARIABLE)

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#763]
Path is /Form/Handler/Event/Base/EditHandler.php

$flashBag->add(\Zikula_Session::MESSAGE_ERROR, $this->__('Sorry, but someone else has already changed this record. Please apply the changes again!'));
            $logArgs = ['app' => 'BotanyorgConferenceModule', 'user' => $this->container->get('zikula_users_module.current_user')->get('uname'), 'entity' => 'event', 'id' => $entity->createCompositeIdentifier()]
            $logger->error('{app}: User {user} tried to edit the {entity} with id {id}, but failed as someone else has already changed it.', $logArgs);
        } catch(\Exception $e) {
            $flashBag->add(\Zikula_Session::MESSAGE_ERROR, $this->__f('Sorry, but an unknown error occured during the %action% action. Please apply the changes again!', ['%action%' => $action]));

**Comment by robbrandt** [comment]
Just noticed the error; there's a missing semicolon closing the line above the $logger line.  Should be:

$logArgs = ['app' => 'BotanyorgConferenceModule', 'user' => $this->container->get('zikula_users_module.current_user')->get('uname'), 'entity' => 'event', 'id' => $entity->createCompositeIdentifier()];

Once I fixed it manually, it occurred in 3 other Forms as well.

**Comment by Guite** [comment]
Fixed in 33ec21d82085c617b3a54ec30fd6212ffc6243e8
