### ISSUE TITLE
Get an error if I try to save the model

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#765]
```
An internal error occurred during: "Saving Models for project MUSound".
Error converting string to value

```
I imported the model, after setting a field to translatable, i get the error when trying to save.

**Comment by Portugao** [comment]
What about this? Did I something wrong?

**Comment by Guite** [comment]
I've no idea yet. Please send me a mail with the imported model attached.

**Comment by Guite** [comment]
The problem is related to the three upload fields in your model:
```
allowedFileSize "1024000"
```
should be:
```
allowedFileSize 1024000
```

**Comment by Portugao** [comment]
Ok, thanks! :+1:

**Comment by Portugao** [comment]
Works, it seems.
