### ISSUE TITLE
[1.3.x] 'en' does not get saved in translation table

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#771]
The entity get saved. The field locale is empty if the entity is for english language.

I think it should contain 'en' for english, right?

**Comment by Guite** [comment]
Which language did you have activated when you created the entity?
I think the strings for this language are saved in the entity fields themselves. Please check that.

**Comment by Portugao** [comment]
German.

At the moment all informations get saved in the translation table.

field **title** and **description**
The 2 english items have an empty field 'locale'.

The table for the entity has no field locale.
![ebene 1](https://cloud.githubusercontent.com/assets/493707/17704914/cc16709e-63d6-11e6-8f68-253efa246d6e.jpg)

**Comment by rallek** [comment]
would be great if the translation will work. I do also have a need for it.

**Comment by Guite** [comment]
> The table for the entity has no field locale.

But does the entity table has `title` and `description` fields? If yes, do they contain the english strings?

**Comment by Portugao** [comment]
Yes. It has title and description, but with german strings.

**Comment by Portugao** [comment]
Maybe I have to set more than 'translatable' for the fields?!

**Comment by Portugao** [comment]
Is there a chance that this issue will be fixed in a few days?

**Comment by Guite** [comment]
Yes.

Which language is set as default language at the general website settings?

**Comment by Portugao** [comment]
German.

**Comment by Guite** [comment]
@Portugao can you send me the latest `MUSound` model by mail?

**Comment by Portugao** [comment]
Thx, Axel. :+1: 
Will check soon.

By the way. The deskop app does not get any updates since 2 weeks.

**Comment by Guite** [comment]
Yeah I know, this is a problem from the new build system. Have it on my list.
