### ISSUE TITLE
SQL error on installation

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#780]
In order to be sure I am not wasting time using an old revision of Zikula, I have started over from scratch with build 115.

On installing my module from scratch, I get this error:

An exception occurred while executing 'UPDATE botanyorg_confer_event SET = '2016-08-18 20:14:22'': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= '2016-08-18 20:14:22'' at line 1

It is missing a column name following "SET".

**Comment by Guite** [comment]
Seems this is related to the standard fields (`createdDate` or `updatedDate`)... are you able to provide a stack trace?

**Comment by robbrandt** [comment]
No stack trace was provided.

**Comment by robbrandt** [comment]
Very odd.  I stepped through execution of the code in a debugger and determined that it happens at 

$this->createDefaultData();

which makes sense.  But when I then stepped into that method to debug it, it worked fine.  Perhaps a timing issue of some sort?  Does Symfony use threading?

Well, at least I now have an installed module to work with.

**Comment by robbrandt** [comment]
This didn't happen in build 155.  If it does happen again, how do I provide a stack trace?  custom_parameters.yml doesn't exist until after installation is complete.

**Comment by Guite** [comment]
When you install the module the core should already be installed, shouldn't it? So custom_parameters.yml should exist. Or am I missing something here?

**Comment by robbrandt** [comment]
No, I'm missing something.  I thought i was replying to the issue I opened for a Zikula installation error :(

**Comment by Guite** [comment]
@robbrandt Can you please try to reproduce it again? I can't provoke it yet. Maybe it is already fixed...

**Comment by Guite** [comment]
Closing as I still can't reproduce this one. If you experience this again please reopen or create a new issue.
