### ISSUE TITLE
Do not generate twig functions intended for global use

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#781]
The routes module has twig functions like `\Zikula\RoutesModule\Twig\Base\TwigExtension::getImageThumb` and `\Zikula\RoutesModule\Twig\Base\TwigExtension::getUserAvatar` and `\Zikula\RoutesModule\Twig\Base\TwigExtension::profileLink` which are obviously intended for global usage.

If two MOST modules are installed on the same site, these methods will conflict likely causing errors (haven't tested it).

First - the functions should be rewritten for Twig and not use the old smarty code in any way (I'm guessing this was only a transitional stop-gap, but this should be discouraged).

Second, only the core should be publishing Twig functions that are "named" in a global sense. Modules should prefix their twig functions with moduleName or something to avoid collisions.

**Comment by craigh** [comment]
perhaps I am misunderstanding this...

maybe these functions are not registered with a global type name? but rather something like `zikularoutesmodule_userAvatar`

**Comment by Guite** [comment]
Yes, they have a module-specific prefix. And of course they are only temporary bridges until a proper replacement is available.
