### ISSUE TITLE
do not use session in installers

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#782]
https://github.com/zikula/core/pull/3036/commits/59d43949c120f54bc295c49a2d6c78aaab2124f9

calling anything related to a user calls the session and this is a problem when running from CLI and is a problem when running on PHP7 apparently. Please note the changes in the commit above for the generator.

**Comment by Guite** [comment]
See also https://github.com/zikula/core/commit/f0a904ac886489fdc3777bd99f5707e714530d19#commitcomment-18780651

**Comment by Guite** [comment]
Fixed in 5b58c13912534634dece16cde8cffaba241430a9
