### ISSUE TITLE
Use extension api method

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#784]
Use `$this->extensionApi->getModuleInstanceOrNull` as a replacement for `ModUtil::available` (see https://github.com/zikula/core/pull/3065 for examples)

**Comment by craigh** [comment]
That method only works for Bundle type modules

**Comment by Guite** [comment]
Thanks. Shouldn't be a problem though, as the 1.4 generator creates 2.0 spec :)

**Comment by craigh** [comment]
I mean - non-bundle modules will return null and so will bundle types that are not available. I don't think it is intended to replace `available` exactly
