### ISSUE TITLE
permalink required?

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#788]
In trying to insert the first record into a simple entity, I field in the 1 field I created for it, and skipped the permalink.  I assumed one would be manually created.  When I submitted, I got " The value you selected is not a valid choice." and the permalink field was colored red.  Including a message "This value should not be blank.".

Bug, or misconfiguration on my part?

**Comment by robbrandt** [comment]
Trying it again from scratch, attempting to get a record submitted I tried to supply the permalink but it appears the field is disabled.  I submit again as above, and once i get the error message above, the field is enabled and I can type something in.  I do so - exactly one word - and I get the following message "The value you selected is not a valid choice." but this time the permalink is not colored red and there are no hints as to what's wrong.  I add ".html" to the end, and get exactly the same "not valid choice" with no other hints.

**Comment by Guite** [comment]
Please open the abstract base class of the entity you tested with. You will find a slug field `protected $slug;` there. In the docblock of this field there is a constraint `* @Assert\NotBlank()`. Please try to remove this and delete the app cache afterwards. (I guess that this constraint is wrong because the slug is computed after validation happened.)

Does this help?

**Comment by robbrandt** [comment]
I guess I need some advice on MOST usage, for this and #794.  I tried to open the .mostapp saved at webgen, but in doing so it overwrote all my latest changes in MOST.  Luckily this was in OSX, and all of the most recent work was done in Linux, so I haven't lost anything important.

So, this module is currently in 2 phases: the first phase was basic schema entities/relationships and evaluation of features in MOST.  That's what I've been trying to get to work in webgen.  No changes to the .mostapp since early August.  Phase 2 is adding actual fields to the entities and adding dropping features based on what I learn from Phase 1.

So, I really have TWO projects of the same name that I want to open in MOST.  Of Phase 1, I only have a .mostapp available (I wasn't planning on continuing to modify this one).  It seems that if I import this .mostapp, it overwrites my Phase 2 project.

I've tried using the "Close All" menu item, but the dashboard still says "ModuleStudio - Your current project: Conference!".  I created a new project, and then tried to import the Phase  1 .mostapp.  That seems to have worked for the Entities, but the Diagram says "Failed to create the part's controls".

What's the best way to do this?

**Comment by Guite** [comment]
Yes, compared to earlier versions MOST 0.7 introduces *projects*. Under the hood this is similar to projects in Eclipse. Best use two different names to avoid project collisions.
Maybe try to rename the application within the .mostapp file before importing it into the Phase 2 project.

**Comment by robbrandt** [comment]
Thanks.  My most (MOST?) immediate problem is the broken diagram.  How do I fix that so that I can edit my project?

**Comment by Guite** [comment]
Create a backup of the domain model (`~/MostWorkspace/<projectname>/<model>.mostapp`). Afterwards delete the whole project using the `File -> Delete project` main menu entry. Then try to import the domain model into a new project again.

**Comment by robbrandt** [comment]
Thanks, that worked, I have a diagram now.  I love that MOST updates itself now.  Does that mean that webgen is no longer required to get the latest changes, or is it just MOST UI updates?

**Comment by Guite** [comment]
The MOST updates include generator changes, too.
But webgen is a bit more convenient when you don't want to do changes, but only want to regenerate. Because it is just pressing a button, while MOST itself needs to be started. Especially when you want to regenerate multiple models webgen is quicker.
But at the end we are talking about saving a few minutes... they don't hurt if you save weeks or months of manual coding ;)

**Comment by Guite** [comment]
@robbrandt could you elaborate on the state of this issue?

**Comment by robbrandt** [comment]
Unfortunately, I haven't retested this. I will get it done before the sprint.

**Comment by Guite** [comment]
Removing the slug input, refs https://github.com/Atlantic18/DoctrineExtensions/issues/140

**Comment by Guite** [comment]
Going to introduce an extension method named `supportsSlugInputFields` (returning a boolean) so this can be centrally managed.

**Comment by Guite** [comment]
FYI: reactivated the slug in put in https://github.com/Guite/MostGenerator/commit/c3aefc905748a8d651f2cef63d208a235b64d43a again
