### ISSUE TITLE
[1.3.x] Creating example entries gives new error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#793]
```
Exception during example data creation: Error! Field value must not contain space chars (title).
```
Sorry; get no stack trace.

**Comment by Guite** [comment]
Not required here, but you should get one. Do you have development mode activated?

**Comment by Portugao** [comment]
Yes. Only get the error by LogUtil.

**Comment by Portugao** [comment]
Sorry...have to check.

**Comment by Portugao** [comment]
Yes, is enabled now and no stack trace.

**Comment by Portugao** [comment]
Thx for fixing.
