### ISSUE TITLE
[1.3.x] Further translation does not work correctly

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#795]
I have checked now and there is something wrong.

I have standard language german. 
The entity has a field 'title' and a field 'description', both translatable.

Now, if I create an entry, the german info get saved into the entity table and the translation table.
And I have 2 more entries in the translation table, that are for the english translation, but in the field locale is 'de' saved and not 'en'.

Multilanguage is deactived.

**Comment by Guite** [comment]
Activate multilanguage and see what happens.

**Comment by Portugao** [comment]
With multilanguage activated it seems to work.

**Comment by Guite** [comment]
I've commited a change in acc6d489a841d8a6e2cce8b03856da0f855ea835

Now if the multilanguage setting is disabled it should only process the current language. Please check if this works and fixes the problem.

**Comment by Guite** [comment]
Complete changes: https://github.com/Guite/MostGenerator/compare/3d225ba6ccb16543e847e8f64efb7f5267740f57...4e8b76a5722794c5d74ddde986efdd45cb53e99d

**Comment by Portugao** [comment]
Hmhmm....

are these changes in webgen revision  e53d749?

**Comment by Guite** [comment]
Yes.

**Comment by Portugao** [comment]
Complictated....

It does not work like expected.

Multilanguage disabled gives 2 entries in the translation table for the fields 'title' and 'description' with locale 'de' and an entry in the entity table with german informations for 'title' and 'description'.

Multilanguage enabled is working.

**Comment by Guite** [comment]
> It does not work like expected.

Please describe what you expect :smile:

**Comment by Portugao** [comment]
I expect, if I have standard language german, that i get shown the title and the description in the view and display template.
I get only the description.

**Comment by Guite** [comment]
@Portugao please remind me at the camp; we will check and fix it together!
