### ISSUE TITLE
Improve support for exporting PDF files

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#798]
- [x] Make Pdf support configurable (new DSL property for generator settings)
- [x] Require DomPdf using composer (instead of relying on obsolete system plugin)

**Comment by Guite** [comment]
Depends on https://github.com/zikula/core/issues/3438

**Comment by craigh** [comment]
> Depends on zikula/core#3438

all vendor libs don't have to depend on the core and composer - if that is the case, it may be a long wait.

simply using composer in your own module and installing the libs in your own vendor dir will work too 👍

**Comment by Guite** [comment]
Of course this is possible, but with some limitations:

1. We can not determine any possible conflicts with core vendors.

2. Dependencies will redundantly exist several times. For the generator this relates to a PDF library (#798), a map library (leaflet, #340) and an advanced image cropper (#712). So if you have ten generated modules, you have the same PDF library ten times.

:thinking:

**Comment by craigh** [comment]
of course you are correct.

but IMO it is a better choice than waiting for the core to implement this idea. It will be at least a year if not longer.

**Comment by Guite** [comment]
Going to think about it later today...
