### ISSUE TITLE
upload handling should consider file size

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#800]
as discussed during camp zikula 2016 we propose to add a possibility to define the file size reduction during the upload. This should be configurable in the created module like simple media.

**Comment by Guite** [comment]
This is about shrinking images exceeding a predefined maximum size.

**Comment by Guite** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Function for shrinking images to max size](https://trello.com/c/D6deVxlE/45-function-for-shrinking-images-to-max-size)

**Comment by Guite** [comment]
This feature has been implemented:

https://github.com/Guite/MostHelp/commit/e10fc1f1ba621488ccf8b48e8259b2c2561bcbfd
9e0d19f34b1f3238da1c730d36c971700598b817
