### ISSUE TITLE
Cannot start ModuleStudio 0.7-dev on Windows 10

### ISSUE THREAD

**Issue by cmfcmf** [Guite/MostGenerator#801]
![image](https://cloud.githubusercontent.com/assets/2145092/18808438/085e5db4-8263-11e6-9b12-669b0aafcb21.png)

**Comment by Guite** [comment]
Seems like windows executable need to be signed.

https://github.com/openscad/openscad/issues/1818
https://blogs.msdn.microsoft.com/vsnetsetup/2013/01/09/windows-smartscreen-prevented-an-unrecognized-app-from-running-running-this-app-might-put-your-pc-at-risk/
http://praxistipps.chip.de/von-windows-smartscreen-wurde-der-start-einer-unbekannten-app-verhindert-das-sollten-sie-beachten_42876
https://forum.jtl-software.de/threads/windows-8-und-die-0-99884-keine-installation-moeglich-viruswarnung.53831/

**Comment by Guite** [comment]
For now I am going to add some documentation about this. The signing process won't be added for 0.7 though.

**Comment by Guite** [comment]
https://github.com/Guite/MostHelp/commit/a8bfbf0da14737d9a0cde50f97544de6cc402600

**Comment by Portugao** [comment]
You can start it, if you click on more informations....

**Comment by Guite** [comment]
Quite cheap code signing certs are available from http://codesigning.ksoftware.net/

**Comment by Portugao** [comment]
If you click on 'Weitere Informationen' you should get another icon or link to install.

**Comment by Guite** [comment]
Just purchased a code signing certificate :-)

**Comment by Guite** [comment]
Note to myself: for signing executables (exe files) in Jenkins (running on Linux) signcode from Mono project tools can be used.

http://manpages.ubuntu.com/manpages/trusty/en/man1/signcode.1.html
http://manpages.ubuntu.com/manpages/zesty/en/man1/signcode.1.html

**Comment by Guite** [comment]
Also use the new cert for signing the created P2 repositories used for installation and self update:

http://stackoverflow.com/questions/16244182/need-help-converting-p12-certificate-into-jks

**Comment by Guite** [comment]
Windows executable files (.exe) are now signed. Thus Windows can read the application's name as well as the publisher information.

The intermediate results are as follows:

1. There won't occur any warning about "unknown publisher" anymore.

2. The blue SmartScreen dialog still appears, because SmartScreen is based on reputation. It won't appear anymore after some users have downloaded and run MOST 0.7.4 and newer.

Fixed.

**Comment by Guite** [comment]
See also http://certhelp.ksoftware.net/support/solutions/articles/17236-will-a-code-signing-certificate-get-rid-of-the-this-file-may-harm-your-computer-warning-my-users-ar

**Comment by Guite** [comment]
Quite detailed description how the reputation process works: https://trustedwindows.wordpress.com/hauptseite/trusted-computing-in-windows/smartscreen-app-reputation/

**Comment by Guite** [comment]
Just asked a quite new Windows 10 user about this: the SmartScreen warning does not appear anymore :smile:
