### ISSUE TITLE
[1.3.x] Wrong name for base classes

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#803]
```
Fatal error: Class 'MUVideo_AbstractVersion' not found in /domain/modules/MUVideo/lib/MUVideo/Version.php on line 18
```

**Comment by Portugao** [comment]
Sorry, this issue is for all base classes.
Did you change the naming of classes? All files should have the same name like the sub classes.
for example:
Version.php
Base/Version.php

**Comment by Portugao** [comment]
Maybe my words were missunderstandable?!

**Comment by Guite** [comment]
Base classes are abstract now. To make this clear their name has also an `Abstract` prefix now. So the `Version` base class is named `AbstractVersion` for example.

**Comment by Guite** [comment]
This was the change: 94f8294485de3b20c23240b92bbfc86ada6cbb88

**Comment by Guite** [comment]
(Feel free to mail or slack me if you want to talk about the details in German)

**Comment by Portugao** [comment]
Ok. 👍
