### ISSUE TITLE
Searching on two category registries with an AND

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#812]
I have a MOST app I am using (MUVIdeo) where I have created several different category registries for the movie entities.  I need to do searches where TWO different categories meet selection criteria.  For example where the Sport category = Football AND the School category = Faber College.  However the DQL generated includes this WHERE:

WHERE (((tblCategories.category IN (:propNameSchools) AND tblCategories.categoryRegistryId = :propIdSchools) OR (tblCategories.category IN (:propNameSports) AND tblCategories.categoryRegistryId = :propIdSports)))

Which is an "OR".  Changing that to an AND reveals another problem, in that the column names for both categories are identical, which makes it basically requiring a single variable to have two values at the same time.  So I get no results.

Seems like each category should be aliased to different names.  Suggestions on how/where to do this?

I note that my own modules have this same code, although I haven't needed this feature (yet), so it's definitely a MOST issue.

**Comment by Guite** [comment]
> that the column names for both categories are identical

To change that the join would need to be changed from one central join for all categories to a dedicated join for each registry. Take a look into the repository class, there is something like:

```
protected function addJoinsToSelection()
{
...
$selection = ', tblCategories';
...
}

```

and

```
protected function addJoinsToFrom(QueryBuilder $qb)
{
...
$qb->leftJoin('tbl.categories', 'tblCategories');
...
}
```

Here is an example from the Doctrine manual showing how to add a specific condition to a join call:

```
$qb->leftJoin('u.Phonenumbers', 'p', 'WITH', 'p.area_code = 55')
```

I guess this could be adapted to add a join for each category registry property.

**Comment by Guite** [comment]
@robbrandt could be I was wrong above and no custom joins are needed. You might look at `CategoryApi#buildFilterClauses` and override it to build a custom filter condition.

**Comment by Guite** [comment]
The column names can be identical, but you need to work with `tblCategories.categoryRegistryId` to target a specific registry.

**Comment by Guite** [comment]
Any news?

**Comment by Guite** [comment]
Closing as "won't fix", as the default behaviour is fine for most common use cases.
As written above you can customise it by overriding `CategoryApi#buildFilterClauses`.
