### ISSUE TITLE
[1.3.x] wrong names in the form/plugin base class files

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#817]
```
class MUSound_Form_Plugin_Base_RelationSelectorAutoComplete extends MUSound_Form_Plugin_AbstractObjectSelector
```
Should be:
```
class MUSound_Form_Plugin_Base_AbstractRelationSelectorAutoComplete extends MUSound_Form_Plugin_Base_AbstractObjectSelector
```

**Comment by Guite** [comment]
Nope.
The hierarchy is:
MUSound_Form_Plugin_AbstractRelationSelectorAutoComplete
extends MUSound_Form_Plugin_Base_AbstractRelationSelectorAutoComplete
extends MUSound_Form_Plugin_AbstractObjectSelector
extends MUSound_Form_Plugin_Base_AbstractObjectSelector

**Comment by Portugao** [comment]
Hmmhmm...I will check
