### ISSUE TITLE
change Zikula_ServiceManager typehint

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#821]
change `Zikula_ServiceManager` typehint to `Zikula\Bridge\DependencyInjection\ContainerBuilder` ASAP the former extends the latter, so there should be no issues.

**Comment by craigh** [comment]
you can replace `use Symfony\Component\DependencyInjection\ContainerBuilder;` import

**Comment by Guite** [comment]
Additionally I need to check if any methods of `Zikula_ServiceManager` are used which need to be refactored then.

**Comment by Guite** [comment]
Out of interest: why do we need `Zikula\Bridge\DependencyInjection\ContainerBuilder ` at all?

**Comment by craigh** [comment]
> Out of interest: why do we need Zikula\Bridge\DependencyInjection\ContainerBuilder at all?

that was drak's. I don't know. the decision was made before me.
