### ISSUE TITLE
[1.3.x] Seems, pending content support does not get generated depending on settings

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#822]
I enabled the generating of pending content support.
But it does not get generated. Seems it depends on the other setting in this setting part?!

For MUVideo ist does not get, for MUSound it does get generated. Actual models on webgen.

**Comment by Guite** [comment]
From the manual:

> generatePendingContentSupport - A boolean specifying whether support for pending content should be generated or not. Requires at least one entity with a workflow including approval.

MUSound has a `STANDARD` workflow, so it is generated. MUVideo has no special workflow, so no pending content is supported here.

Closing. Feel free to reopen if you see still any issue.

**Comment by Portugao** [comment]
Ah ok; did not think about that. Thx.
