### ISSUE TITLE
generation errors

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#824]
`$currentUrlObject` is undefined here: https://github.com/zikula/core/blob/4b8a4b51c5b0e4863b57672dbf18124bd65a0c02/src/system/RoutesModule/Controller/Base/RouteController.php#L268

`$controllerHelper` is defined and unused here: https://github.com/zikula/core/blob/4b8a4b51c5b0e4863b57672dbf18124bd65a0c02/src/system/RoutesModule/Controller/Base/RouteController.php#L143

**Comment by Guite** [comment]
The first one is already fixed in https://github.com/zikula/core/commit/9011896bebd23609e31fbca9aa0dcbe71d3bf63d and https://github.com/Guite/MostGenerator/commit/725e00b3d00c1cea0ddf74a46299bc9e02916972

Looking into the second one now.

**Comment by Guite** [comment]
Second one fixed in https://github.com/zikula/core/commit/e7cccd5eca7967e625b9af955d7e74b0bf60938c and 51688af55e8c21416991e7aaa9e8318e6c491814
