### ISSUE TITLE
Cannot generate module, get error

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#827]
I get a M2T Exception error message.
Only a folder named 'model_export' is there with some files.

**Comment by Portugao** [comment]
Maybe it depends on missing bundles, that were not loaded by starting MOST. I talked about these problems some days ago in Slack.

**Comment by Guite** [comment]
Is this a new installation or did you update an earlier one?

**Comment by Portugao** [comment]
I downloaded the BETA version just published; have I to delete something in the workspace?

**Comment by Guite** [comment]
Just tested generating using the beta version. It works in Kubuntu without problems. So it is either related to the Windows version (you are using Windows 8, right?) or to your model.
Is the model processed in the webgen? Could you send it to me by mail?

**Comment by Portugao** [comment]
Yes; win 8.1.
Webgen works with the uploaded model 'Products'. You can get the model there.

**Comment by Guite** [comment]
I can replicate it using Windows 8 in a VM.

**Comment by Portugao** [comment]
Hmmhmmm...so I did not make a mistake. Hope you can fix it.

**Comment by Guite** [comment]
The fix should now be available as a staging update.

**Comment by Portugao** [comment]
Super. I have just checked and it works.
Thx a lot, Axel.
