### ISSUE TITLE
Remove XML import feature?

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#829]
The `pntablesToXML.php` script has been removed from the core's master branch. Thus, somewhen either remove the XML import functionality completely or change documentation by explictly pointing to another branch.

cc @craigh

**Comment by craigh** [comment]
I removed it because it seems old - isn't it a transition tool from Core-1.2 -> Core-1.3? Anyway - it is still included with Core-1.x always.

I'm not opposed to providing it somewhere else if it is needed.

**Comment by Guite** [comment]
Yes, it is old. Indeed the XML import feature is only there to create a model for an existing old module having a (pn)tables.php file. We don't need to keep that forever of course :-)

**Comment by craigh** [comment]
if we need something like this it would be better to recreate it as a Symfony console command I think.

**Comment by Guite** [comment]
@robbrandt @rallek @gfr @espaan @cmfcmf does anybody need the xml import? If not I could remove it for 0.7 already.

**Comment by Guite** [comment]
@portugao ?

**Comment by robbrandt** [comment]
I've never used it but always considered it an asset.  So consider my vote a very weak yes.  I won't be upset if it goes.  Does it require frequent maintenance? I guess if need arises pntablesToXML.php could be refactored as a standalone script utility.

**Comment by Guite** [comment]
pnTablesToXML.php is a standalone tool. But if support in MOST is removed (which is what this issue is about) you won't be able anymore to import the xml file into a modeling project. Then you need to create the model manually instead.

**Comment by rallek** [comment]
What is it?

**Comment by Guite** [comment]
See http://modulestudio.de/documentation/c/40-Migration#migrating-old-modules

**Comment by robbrandt** [comment]
Ah.  Well, I have a list of "someday" module upgrades.  Maybe I should just do quickie conversions of them into a model while the tool is available.  There is a finite list of 1.2 module to convert; if they were all done, there would be no debate would there. ;)

**Comment by Guite** [comment]
Well, it doesn't take you days to create a model by hand, does it? :smile: 

Of course I can postpone the removal to 0.7.1 or 0.7.2. My point for asking was just that 0.7.0 has the slogan *less is more* as it significantly reduced the tooling to a rather minimal UI focusing only on what is actually needed and reasonable instead of almost everything which is made possible by Eclipse. This raises the question about whether this legacy functionality makes still sense ;-)

**Comment by robbrandt** [comment]
I have one 1.2 module where rebuilding the model would take a lot of time.  The project is dormant though, so nothing has been scheduled.

I will spend some time over the holidays in a location with poor internet connectivity.  This sounds like a good project for that time period.  Can you wait until after Jan 1?

**Comment by rallek** [comment]
@robbrandt You may want to save the current 0.7.0 beta somwhere to be able to do the job later as well ;-)

**Comment by Guite** [comment]
Sure. Will move this issue to 0.7.1 again. I don't think that 0.7.0 final will arrive this year, but I won't do any tooling changes after the 1st RC though.

**Comment by Portugao** [comment]
I think you can delete it.

**Comment by Guite** [comment]
@robbrandt about next week the beta3 will be released. As @rallek suggested you can save a copy of it to use it later for the xml import stuff. I am going to remove the function after beta3 so in RC1 it won't be available anymore.

**Comment by Guite** [comment]
The function has now been removed. So if you want to utilise it use the beta3 and click on _No_ when asked for whether you want to install a found update.

**Comment by robbrandt** [comment]
Ah!  I was just getting to this!  Too late??

**Comment by Guite** [comment]
No no, it is still contained in the beta3. But when you start it choose _No_ if it asks you for whether it should install available updates.

So you could have two folders with two installations: one which is kept up to date and one which ignores updates for using the xml import stuff.

**Comment by robbrandt** [comment]
I just tried it (made a copy of MOST first) and I wasn't given the opportunity to refuse the update.  Just an "OK".  It did an update but I don't see an indication in MOST as to what beta or commit was just installed. In my MOST preferences, I don't have either the "Use staging updates" or "Ignore Updates" checked.  It appears that I still have an option for "Import XML table definition", which I think is the option you have removed.

**Comment by Guite** [comment]
The change that it asks for the update was introduced a few days ago together with the "ignore updates" function. If it did not ask you, then enable this option in the preferences better to avoid another update (which just not has passed the build server yet ;)).

**Comment by robbrandt** [comment]
The preferences don't look any different than before(?) but I have checked the "ignore updates" option in my XML Import copy.

**Comment by Guite** [comment]
For information: you did not get the newest update (removing the feature) yet because staging updates are not activated.

**Comment by robbrandt** [comment]
I now have a selection of xml files from old modules generated by the pntablesToXML.php file.  I have tried to run them through the "import XML table definition" option.  It displays a message that a converted file has been saved to a MOST_ouput directory, but I cannot find that directory anywhere in my Mac.  Suggestions?

**Comment by robbrandt** [comment]
Found it!  It saves it into the Module Studio app bundle at Contents:MacOS:MOST_output.
