### ISSUE TITLE
make ~/MostWorkspace configurable

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#832]
It would be nice to make the path configurable. At least the path for the folder where the models should go.

**Comment by Guite** [comment]
When you create a new project you can choose another location by unsetting the `Use default location` option.

![screenshot_20161031_164159](https://cloud.githubusercontent.com/assets/277531/19860438/f413149c-9f88-11e6-848e-d52bec60d7c9.png)

Is that what you need?

**Comment by Guite** [comment]
Unfortunately this setting is currently ignored. The project is still saved at the default location.

**Comment by rallek** [comment]
It would be nice but the meaning is to define the default somewhere

**Comment by Guite** [comment]
What you can already now: open the file `modulestudio.ini` in a text editor. There you find:
```
-data
@user.home/MostWorkspace
```
You can replace this by another path and this will then be used instead.

**Comment by rallek** [comment]
I tried it already :-)

Can not say what was wrong but I remember some trouble. Will try next year :-)

**Comment by Guite** [comment]
Added instructions to docs in https://github.com/Guite/MostHelp/commit/6784c8510181d337366fe61e7b65b62379b8f90e
