### ISSUE TITLE
Use tabs for translatable fields

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#834]
Instead of fieldsets translatable fields should be arranged in a tabbar having one tab for each locale.

**Comment by Guite** [comment]
This won't be done in the near future, because when translatable fields are contained in tabs one could possibly miss mandatory fields.

**Comment by Guite** [comment]
Just did a brief test for this: the problem here is that if a field is not valid the user does not see this. So some JavaScript is required to automatically activate the corresponding tab in which the validation error occurs.

**Comment by rallek** [comment]
I am testing currently translating feature. Is it really wise to have a tab view? If I have to translate sonething I should have the original text visible.

Might be an accordeon can make the form view more simple.

**Comment by Guite** [comment]
The question is also whether it really makes sense to have translated edited together with the original content in the same step. Another possible workflow could use a dedicated translate action like Content uses.

**Comment by Guite** [comment]
Closed as this will be done as part of #177 (description already updated).
