### ISSUE TITLE
Cannot generate because of getting an error message

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#836]
Fehler beim beobachten des Generierungsfortschritts.

Tested with new beta version of today.

**Comment by Guite** [comment]
The fix is now available in staging updates. After MOST has updated generation works again.

**Comment by Portugao** [comment]
Nice, try to update now. Thx. 👍

**Comment by Portugao** [comment]
Sorry; MOST does not get the update. tried to start again or to get it with the way over the help section.

**Comment by Guite** [comment]
@Portugao I've updated the beta download archives. So you can just download it again to get the latest build.

**Comment by Portugao** [comment]
Thx a lot, Axel.
It works fine now.
Thx for new MOST.
