### ISSUE TITLE
Let form handler redirect to referer by default

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#844]
If no `returnTo` parameter is specified redirect to the page where the editing was started.

cc @robbrandt

**Comment by Guite** [comment]
In addition it should be possible to specify arbitrary urls, for example to return to a "Thank you" page.

**Comment by robbrandt** [comment]
👍

**Comment by Guite** [comment]
Need to add another fix for this: the referer needs to be skipped if it is the display or edit page of the edited object and if this object is deleted.
