### ISSUE TITLE
Review homepath usages

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#846]
The 1.4 target uses the `pagevars.homepath` variable in some locations where the base url is needed. This needs to be corrected.

@craigh any idea how to get the base url in a Twig template?

**Comment by craigh** [comment]
from `{{ app.request.baseUrl }}` or similar

**Comment by Guite** [comment]
The correct one is `{{ app.request.getSchemeAndHttpHost() }}` (without trailing slash).
