### ISSUE TITLE
Valid Geographical data fails validation

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#852]
My current location, Carpinteria CA, USA, has the following long/lat

Latitude: 34.4054738
Longitude: -119.5281600

However when submitting a form, the validation fails, saying the longitude is too long a number. "Longitude: Error! Input text must be no longer than 11 characters." Removing a zero works.  Probably a combination of the negative and 3 digits to the left of the decimal?

**Comment by Guite** [comment]
@gfr can you elaborate and propose a fix?
