### ISSUE TITLE
Option for "geographical" to NOT get browser's location

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#853]
I have a need for geographical data, but 99% of the time, the user won't be in the location that needs to be entered.  It will be confusing when the browser asks for this, they may not realize why it's asking.

**Comment by Guite** [comment]
A DSL option would be too much for this specific feature. Thus, the geolocation code is still generated, but commented out by default. If one needs it, he can just activate it in the template.

**Comment by robbrandt** [comment]
👍

**Comment by robbrandt** [comment]
Where is this commented out?

I am finding that, while it does not ask for my location any longer, the mapping doesn't work at all once the GPS coordinates are manually entered in.

MOST 0.70 Final zk1.36 target

**Comment by Guite** [comment]
Depending on the version/revision of the generator either in the edit template or in a dedicated _geo_ JS file.
What do you mean with mapping?

**Comment by robbrandt** [comment]
MOST 0.70 Final zk1.36 target

By mapping, I mean the feature where the map shifts to your location as you type in the coordinates.  In the Edit view.

**Comment by Guite** [comment]
Can you check whether any JavaScript errors are visible in the console?

**Comment by robbrandt** [comment]
NoApiKeys. Adding one fixed the problem.  Is this normal?  I don't remember doing this before, but I definitely remember seeing the maps function.  Maybe I was previously be low a usage limit?

**Comment by Guite** [comment]
http://stackoverflow.com/questions/2769148/whats-the-api-key-for-in-google-maps-api-v3/37994162#37994162

**Comment by robbrandt** [comment]
Thanks.  It would be a nice feature in MOST to have a preconfigured setting for entering the API when geographical attributes are selected.  Maybe there should be an "API" tab in Settings?

**Comment by Guite** [comment]
Please create a separate issue for that.

**Comment by Guite** [comment]
Maybe a tab named "Geo" containing an "API key" field as well as a boolean for enabling/disabling the geolocation ;-)
