### ISSUE TITLE
please add the feature to switch the contributor

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#857]
On my sites we do have users helping other users to create content. But the content should look like it is from the helped user.

News do have the possibility to change the contributor of the news. I would like to see the option at properties of an entity to switch on this feature as well.

**Comment by robbrandt** [comment]
I have a similar issue but considered it too much of a corner case to raise as a feature request.  Perhaps not.

My issue is the ability to "assign" a record to an owner.  The specific case is one where an application is made but submitting a form, and there are child records called evaluations.  A moderator needs to create an evaluation and assign it to a reviewer.  If this was done via the creator_id then the already existing "own record" features could be used for the reviewers to find the evaluations that have been assigned to them so they can complete the evaluation.  Essentially, the creator_id fields need to act like the user fields a developer might place in the model.

**Comment by Guite** [comment]
Should be done after #910 which adds new properties to the DSL: https://github.com/Guite/MostGenerator/issues/910#issuecomment-270976842

**Comment by rallek** [comment]
Just an idea how to implement:
In the string field you added some options e.g. locale. Similar you cann add in the users field an option for ``creating user id``. This field should only appear if you have admin permissions. The default is the current user while adding. If someone is changing the item the stored user should remain.
Same you can do for the creation date.

**Comment by Guite** [comment]
Going to do that as follows:

- if the current user has at least moderation
- add a fieldset like "moderation options" to the edit form (in both create and edit mode)
- this fieldset contains two optional fields
  - specific creator
  - specific creation date
- the fieldset is hidden by default and can be shown/expanded on demand

**Comment by rallek** [comment]
Fine for me. Thanks for implementation.
