### ISSUE TITLE
New options for list/detail display and sorting

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#858]
Add new properties for controlling whether a field should be visible in the list and detail pages and whether it may be used for sorting. All these criteria should be activated by default.

**Comment by Guite** [comment]
Both flags should be `true` by default.

**Comment by Guite** [comment]
Maybe visibility on display pages would be interesting as well.

**Comment by rallek** [comment]
perfect!

**Comment by Guite** [comment]
https://github.com/Guite/MostLocales/commit/c340aff5969d5e74fca746dc7107e389eb0f17a5
https://github.com/Guite/MostHelp/commit/052d9d66c68252b8f168d6539c26befdf4271588

**Comment by Guite** [comment]
http://modulestudio.de/documentation/c/87-GeneratorReference#entity-field-display-type
