### ISSUE TITLE
extend namingScheme for uploads

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#862]
It would be great to have the possibility to upload e.g. a picture and change the filename. E.g. a picture is named DSC4356.jpg it should be able to rename it to userdefined.jpg during upload.

The user can change the file name before uploading, clear. But allow to change the filename would be a great feature (I have seen that at sharepoint, there you can even edit the filename afterwards). You may want to name this EDITBYUSERWITHCOUNTER. The counter is needed to avoid overwriting an already existing file.

This feature request is not for 0.7.0

**Comment by Guite** [comment]
refs #97

**Comment by Guite** [comment]
DSL tasks:
- [ ] Introduce new enumeration value

Tooling tasks:
- [ ] update property mappings

Generator tasks:
- [ ] add additional input field with help text about invalid/stripped characters
- [ ] update upload processing with fallback in case no or invalid custom name was entered
- [ ] update docs (generator reference)
