### ISSUE TITLE
[1.4.x] Calling backend from extensions module leads to frontend template and not to admin template

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#863]
Actual model in webgen.....

**Comment by Portugao** [comment]
Have to exlpalin better.
I get the backend, but not with admin template but user template.

I changed the title of issue

**Comment by Guite** [comment]
What do you mean with *user template*? Both admin and user area use the same template. Do you see the *With selected entries* select element at the bottom of the entry view page? Then this is the admin area.

**Comment by Portugao** [comment]
There is admin and master template in the bootstrap theme.
If i call the admin area, for example extensions module backend, I have one column. If i call the backend of Eternizer I have 2 columns and the search block on the left side.

Maybe its a core bug?

**Comment by Portugao** [comment]
If i call the hooks of the module I'm back on the admin template....

**Comment by Guite** [comment]
@craigh could this be a core bug? The generated modules definitely use the `Theme` annotation. Also the admin panel is shown. But there is also the left column displayed, which should only be done for the user area.

**Comment by Portugao** [comment]
By the way. I like, that I'm able to install and work with the module; so I can start to make the module 1.4.x compatible. 👍

**Comment by craigh** [comment]
As long as Theme("admin") then should work like core. Also the annotation class must be imported. See docs

**Comment by Portugao** [comment]
If I change to using the theme Andreas08 in backend, the module only use it, if I call the hooks.

**Comment by Guite** [comment]
Found it.

**Comment by Guite** [comment]
WebGen is updated.

**Comment by Guite** [comment]
MOST update also available now.

**Comment by Portugao** [comment]
Sorry. No updates on win 8 computer. Also with 'About' function.....

**Comment by Guite** [comment]
Did you enable staging updates?

**Comment by Portugao** [comment]
Sorry. It was disabled.

**Comment by Portugao** [comment]
It works. Thx.

**Comment by Portugao** [comment]
Sorry. This issue is back.

**Comment by Portugao** [comment]
Oh, wait. I have to check again.

**Comment by Portugao** [comment]
It depends on these rows:
```
        // temporary workaround
        // let repository know if we are in admin or user area
        $request->query->set('lct', $isAdmin ? 'admin' : 'user');
```

**Comment by Guite** [comment]
What is the url where the problem occurs?

**Comment by Portugao** [comment]
For example:
http://official144.homepages-mit-zikula.de/eternizer/entries/view

**Comment by Guite** [comment]
This is correct. For the admin view you should call:
http://official144.homepages-mit-zikula.de/eternizer/admin/entries/view

**Comment by Guite** [comment]
Please check and reply afterwards.

**Comment by Portugao** [comment]
It is not, because this call is one for the master template in the theme and that have 2 cols.

Like calling site search in the frontend.

**Comment by Guite** [comment]
I guess I don't understand correctly.
If this is an issue it is a different one than #863, because this was about admin templates. And `/entries/view` is a frontend url, not a backend one.

**Comment by Portugao** [comment]
Puh. You're right.
I'm a little bit confused, it seems.
Sorry for that.
So I close this and make a new issue.
