### ISSUE TITLE
extend image settings

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#864]
The new image settings are great. I would like to see the possibility to make a similar setting for the thumbnails in display and list view.

Also add the chance to edit the quality for the images less than 100%. That might speed up some pages by reducing image file size.

**Comment by Guite** [comment]
Proposal:

generate modvars for:

- thumb quality
- for each upload field:
 - thumb mode (inset or outset)
 - thumb size (width x height) for view/display/edit actions (those which are available for the entity in the model)

**Comment by Guite** [comment]
Removed thumb quality modvar again, since this does not work as part of thumb runtime options.
