### ISSUE TITLE
Hide fields with empty data in display template by default?

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#865]
In my Parkhaus module I do have tons of optional fields. If the are empty I do not want to show them on Display page.

No problem to do this in the template. But it would be nice to manage this alredy inside MOST.

**Comment by Guite** [comment]
The `visible` setting is for edit pages only. For display and view pages the `displayType` property is used.

Please elaborate in detail what you expect from this feature request.

**Comment by rallek** [comment]
For example in my Parkhaus module I do have tons of optional fields. If the are empty I do not want to show them on Display page.

No problem to do this in the template. But it would be nice to manage this alredy inside MOST.

**Comment by Guite** [comment]
The question is whether empty values should be shown at all. Maybe we can just hide them by default without introducing a setting for that.

**Comment by rallek** [comment]
fine for me, but fine for all?

**Comment by Portugao** [comment]
👍

**Comment by Guite** [comment]
@robbrandt @gfr your opinion about that?

**Comment by Guite** [comment]
One possible concern is that this increases the template size... there are pro's and con's for the change...

**Comment by rallek** [comment]
It is just an idea. Place it in far future or close it if it will not be implemented
