### ISSUE TITLE
the readme file in resources/translate should get better content

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#868]
Please add some usefull content inside the readme file e.g.:
````
to get a new translation you should use the following at the comand line in your Zikula root:

    php app/console translation:extract en --bundle=VendorModulenameModule --output-format=pot

afterwards you may want to use the pot file for your translation
````

It would be perfect if ``VendorModulenameModule`` would be the correct Name for the generated module.

**Comment by Guite** [comment]
@cmfcmf can you please tell us how to create the routes.pot? Then this instruction could be added, too.

**Comment by craigh** [comment]
the flag: `--enable-extractor=jms_i18n_routing` is the important part

but I recommend `.po` and not `.pot`

`php app/console translation:extract en --bundle=AcmeDemoModule --enable-extractor=jms_i18n_routing --output-format=po`

**Comment by rallek** [comment]
``--enable-extractor=jms_i18n_routing`` is working great.
Until #867 is not fixed there I have in my module a problem with *.po files But *.pot is fine. So I will work with that so far. but for routes the *.po is way better because with *.pot you would miss the routes itself.

**Comment by rallek** [comment]
This is not working anymore. The only text I can find in the readme.md:
````
This file is a placeholder.
````

**Comment by Guite** [comment]
There should be a `translations.md`.

**Comment by Portugao** [comment]
There is one.

**Comment by rallek** [comment]
Now I found it :-) 
So either the readme inside the translation folder should be deleted or a hint towards the docs folder would be nice.
