### ISSUE TITLE
[1.4.x] Included template in frontend to show waiting entries does not work correctly

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#872]
It shows one waiting entry, but I have only entries approved.

**Comment by Guite** [comment]
Which template do you refer to? Moderation panel?

**Comment by Portugao** [comment]
Sorry. In the view template above the main content.

**Comment by Portugao** [comment]
In backend and frontend.

**Comment by Portugao** [comment]
You can see here for example:
http://official144.homepages-mit-zikula.de/eternizer/entries/view

**Comment by Guite** [comment]
Currently on it...
