### ISSUE TITLE
[1.4.x] Missing action for selected items in backend

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#879]
I miss the action 'approve' to handle several items in the dropdown below the items.

Workflow standard.

**Comment by Guite** [comment]
With the newest revision I can see the _approve_ action and it also worked without problems. Please try regenerating after webgen has been updated (in about 5 minutes).

**Comment by Guite** [comment]
Sorry, please wait for another fix for the new item actions menu I just introduced.
