### ISSUE TITLE
viewQuickNav/list view frontend shound not contain State column

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#882]
Normally the frontend list view should not contain the column of the state of an entry. I would prefere only to see this column if you have the right to change the status e.g. only in the backend.

**Comment by Guite** [comment]
quick navigation is only visible for moderators anyway by default...

**Comment by Guite** [comment]
moderators is not entirely true. you need `edit` permissions

**Comment by rallek** [comment]
you are right

**Comment by rallek** [comment]
Purpose is not the quick navigation. It is the table column at the frontend. So I have to make that manual in the template.
![grafik](https://cloud.githubusercontent.com/assets/935250/21424183/62ab3f7a-c841-11e6-8661-473910305175.png)
