### ISSUE TITLE
Strange effect with forms and fields

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#884]
The return control field is getting under the action buttons by editing an item.
The tag <fieldset> is away.

So this code in the template does not work like expected:
```
{# include return control #}
{% if mode == 'create' %}
    <fieldset>
        <legend>{{ __('Return control') }}</legend>
        {{ form_row(form.repeatCreation) }}
    </fieldset>
{% endif %}
```

Maybe it's a core bug?!

**Comment by Guite** [comment]
No core bug, I know the reason.

**Comment by Portugao** [comment]
Ok. That's fine.

**Comment by Portugao** [comment]
👍
