### ISSUE TITLE
Trying to edit an item gives red feedback about additional fields

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#885]
```
 This form should not contain extra fields.
```
The feedback contains that I cannot save the changed datas...

**Comment by Portugao** [comment]
Maybe it depends on remark field?

**Comment by Portugao** [comment]
It seems, I'm right, because it appears only in frontend....

**Comment by Guite** [comment]
Seems this is not a generator problem.
After a fresh generation without any customisations I can submit new entries in both the backend and the frontend.
Please check.

**Comment by Portugao** [comment]
What does it mean 'without' customisations'?

**Comment by Portugao** [comment]
Ok. I will check.

**Comment by Guite** [comment]
Without customisations = just freshly generated, not changed any file.

**Comment by Portugao** [comment]
It depends on this extended code in the edit.html.twig template:
```
{% set returnUrl = path('mueternizermodule_entry_view') %}
{{ form_start(form, {attr: {id: 'entryEditForm'}, action: path('mueternizermodule_entry_edit', { returnTo: returnUrl }) }) }}

```

**Comment by Guite** [comment]
Could you please try this:

1. Edit the model @ webgen, removing all `skipFiles` and `markFiles` entries.
2. Regenerate and install the module on a fresh 1.4.4 installation.
3. Test editing in backend and frontend (should work, as this is what I did 10 minutes ago).
4. Readd this extended code in the edit template.
5. Try again. If it does not work any longer we know that this extension is responsible.

**Comment by Portugao** [comment]
I expanded the code again and it seems to work:
```
{% set returnUrl = path('mueternizermodule_entry_view') %}
{% if routeArea != 'admin' and mode == 'create' %}
{{ form_start(form, {attr: {id: 'entryEditForm'}, action: path('mueternizermodule_entry_edit', { returnTo: returnUrl }) }) }}
{% else %}
{{ form_start(form, {attr: {id: 'entryEditForm'} }) }}
{% endif %}
```
Seems also nessecary to delete the cache for new code....although I I set the setting to 'debug = true'.

**Comment by Portugao** [comment]
Will have some attention on that....for this moment you can close, I think.
Could be reopended if necessary.
