### ISSUE TITLE
Remove remaining Util usages

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#886]
There are a few usages of legacy Util classes left. These need to be removed.

- [x] Use `Kernel#isBundle()` instead of `ModUtil::available`
- [x] Eliminate usage of `System`
- [x] Generate only one factory class (`createFoo(), createBar(), getRepository($objectType)`)
- [x] injections of `service_container` should be removed
- [ ] Eliminate all occurences of `Util::` and `Util;`
- [x] Instead of `{{ localeApi.language_direction }}` use `auto`.
- [x] Only for `ZK14DEV` target: eliminate usage of `ZLanguage`
  - [x] Instead of `ZLanguage::getInstalledLanguages()` use `$container->get('zikula_settings_module.locale_api')->getSupportedLocales()`
  - [x] Update usage of `LocaleType` (assign `choices`)

**Comment by Guite** [comment]
Afterwards update https://github.com/zikula/core/pull/3363

cc @craigh

**Comment by craigh** [comment]
Should also check for System:: calls if you didn't already

**Comment by Guite** [comment]
This is the second point in the task list above.

**Comment by craigh** [comment]
;-) I can't read 🙄

**Comment by Guite** [comment]
currently resolving some circular deps
