### ISSUE TITLE
scribite plugin for CKeditor is not working

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#888]
e.g. my download module do have scribite plugin enabled in settings.

Now I setup Scribite CKEditor to "full" mode. There is space available in the toolbar but no image (left to MediaModule) and no function (you can not click it)

![grafik](https://cloud.githubusercontent.com/assets/935250/21466091/967f3b2c-c9bc-11e6-97a6-d68c8aab67b3.png)

Most updated today

**Comment by Guite** [comment]
There is also a problem with TinyMCE, as the plugin files seem to be blocked (forbidden).

**Comment by rallek** [comment]
Now the content is not stored anymore if I use Scribite with CKEditor

**Comment by Guite** [comment]
Was caused by another JS function. Fixed in 3079b613a70963f8f0036b473ce5e04372d729ba
