### ISSUE TITLE
rethink about "project"

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#892]
Currently a project is just the model, the ``.project`` and ``representations.aird``. If I do have only the model I am able to import it and I do have the same. The project do not give a really benefit currently. But I am shure you do have more ideas for its roadmap.

I am working currently at several modules. There I generate some ideas what I want to share with you. Might be it will give you some additional ideas as well. Thanks for the great modulestudio!

Here my ideas:
* save the model with his version. If the model version is changed please do not overwrite the old version and save the new version in another file or in a history-mostapp file where you have all former models collected in one file. If the version is not changed it should overwrite the currend master version.
* if we do have now more than one version of the mostapp, there would be a chance to create the upgrade instruction with a workflow (depending on the changes we do have to add some informations what should happen with what). The changes could be handeled in a table like the var containers. This idea is for a later version of modulestudio but it might be necessary to have this prepared somehow in the DSL and so on.
* save the place where the generated module should be placed
* have a separate changelog.md and read.me for the complete project which are merged into the generated module. An integrated text editor for those files would be great.
* Add an option to clone the project. The clone should not contain any history. It should get a totaly new name like a new project.

An additional idea where I do not know if that is to risky:
* Similar to the merging of the changelog.md and the readme.md you can also have a separate folder for merging own files e.g. some filter templates or images. The folder might be named ``postmerging`` and will merge the complete structure under this folder. It is the responsibility of the developer to take care the files are in the right subfolders and if they overwrite a template that they are not doing bad things.
* The maximum validation which can be made: If the "postmerging" process is overwriting existing files throw a warning with the recommendation to mark or skip these files in the model.

The complete project can be stored in a github repository. Ideally the developer is able to download the repository, open the project in modulestudio, give the model a new subversion and generate the model again. Within a minor modulestudio version (e.g. 0.7.x) the module should be updated and the upgrade of the module is done. With a higher subversion (e.g. 0.8.0) some adjustments might be necessary.

If I do have more ideas during my currently work I let you know :-)

**Comment by Guite** [comment]
Closing because project handling has been significantly simplified for the next version. Now you simply have a folder with your models in it:

![image](https://github.com/Guite/MostGenerator/assets/277531/65f796b0-49a0-48bc-9c83-fca0caec0c79)
