### ISSUE TITLE
Title in frontend templates like set in extensions module

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#893]
It would be fine, if the templates in the frontend would show the title like set in the extensions module.

Maybe the additional possibility to choose this for backend, frontend or both were helpful?!

**Comment by Guite** [comment]
Yes, this can be done. But I don't think that an option for this makes much sense. It should always use the display name instead of the original one.

**Comment by Portugao** [comment]
Fine for me.
Thx, Axel. 😃
