### ISSUE TITLE
scribite plugin enhancement if more than one entity

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#894]
- [x] Currently there are some links on top if there are different entities to choose in the scribite plugin. Might be it is more nice to have them tab looking.
- [ ] Is it possible to exclude some entities from the scribite plugin via MOST configuration? E.g. move the scribite plugin setting from the setting container into the entity propperties. Might be other settings are also better in the entity located e.g. tag and needle support. (Most 0.7.1) 
- [x] ``Paste as:`` should also contain the selection for just the image. You should handle it with the same settings than the display width and hight incl lightbox function. If some want to have it differen he can edit the raw html. (Most 0.7.1) [done in #938]

**Comment by Guite** [comment]
> Might be it is more nice to have them tab looking.

At the moment they are using pills:

http://getbootstrap.com/components/#nav-pills
https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/view/additions/ExternalView.xtend#L387

You propose to change that to what?

**Comment by Guite** [comment]
I will add the current one, too (class active) which makes the "menu" character more visible.

**Comment by Guite** [comment]
See 637c3d049a8e110536aca9074c98c593da059ff3

**Comment by rallek** [comment]
yesterday there have neen no pills :-). Pills are ok, tabs I would prefere, but that is cosmetic.

The second point with excluding is already ther particular. If I do not have a display action thex are not shown there as well. That is fine for the moment.

**Comment by Guite** [comment]
There are tabs now.

**Comment by Guite** [comment]
> Is it possible to exclude some entities from the scribite plugin via MOST configuration?
Maybe generating a modvar for this would be appropriate (checkbox list)...
