### ISSUE TITLE
Messaging system - does not work?

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#897]
I'm not sure, when the system should send a message.
If an user submit an entry?
If someone do approve a waiting entry and enter additional remarks?

At the moment there is no message coming?!

**Comment by Guite** [comment]
Does sending a test mail work on your system?

**Comment by Portugao** [comment]
Yes.

**Comment by Guite** [comment]
Please apply the fix for #896 and try again.

**Comment by Portugao** [comment]
Maybe depends on #896 ?!

**Comment by Portugao** [comment]
Ok.

**Comment by Guite** [comment]
Added some template fixes in 1abc148695e221af42ba1148031a50f3601f9b31

**Comment by Guite** [comment]
To see when which email should be sent look at the workflow xml file. There is a *notify* operation contained in the workflow actions.
