### ISSUE TITLE
Unclear naming of modvar

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#901]
In the database I find:
```
entryEntriesPerPage`
```
Inj the code of controller:
```
EntriesPerPage
```

**Comment by Portugao** [comment]
Sorry. I had not the correct look.
Have to check again.

**Comment by Guite** [comment]
it should be both `entryEntriesPerPage`

**Comment by Guite** [comment]
The controller code does this:
`$resultsPerPage = $this->getVar($objectType . 'EntriesPerPage', 10);`
with `$objectType` being `entry`.

**Comment by Portugao** [comment]
Yes, I saw....maybe it is may overriding...
