### ISSUE TITLE
More reasonable usage of diagram export

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#903]
Currently the generator workflow exports the diagram in all possible file formats. Instead it should only export a JPG image and place it right next to the model file (location depending on `writeModelToDocs` setting). For example `foo_diagram.jpg` beside `foo.mostapp`.

**Comment by rallek** [comment]
good idea!

**Comment by Guite** [comment]
refs #866

**Comment by Guite** [comment]
Generator workflow now exports the diagram only as JPG and only if `writeToModelDocs` is `true`. The JPEG file is placed in the same directory as the model file itself.
As a nice side-effect the generation has become even faster with that.
