### ISSUE TITLE
Path to scribite plugin?

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#908]
I have put the module into the folder modules/mu/image-module/.....

In the path to the plugins there is modules/MU/ImageModule....

So the plugin will not get be loaded....

**Comment by rallek** [comment]
I always placing my modules into ``modules/RK/myIdeaModule``

You must currently add ``Modules`` at the end of the module folder name

**Comment by Guite** [comment]
Yes, at the moment `Vendor/FooModule/` is required.

**Comment by Guite** [comment]
Maybe this is changed to `vendor/foo-module` later.

**Comment by Portugao** [comment]
Changing that gives an error:
```
Fatal error: Class 'MU\ImageModule\Listener\CoreListener' not found in domain/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php on line 152
```

**Comment by Portugao** [comment]
In the composer.json I have this
"name": "mu/image-module",

**Comment by Portugao** [comment]
I named the folder modules/MU/ImageModule...

**Comment by Portugao** [comment]
...and get the error...

**Comment by Guite** [comment]
I bet this error is caused because your database now expects the bundle in the old path. Check the `bundles` and `modules` tables in your database.

**Comment by Portugao** [comment]
There I find mu/image-module

**Comment by Portugao** [comment]
So i have to change the line in the composer and reinstall?

**Comment by Guite** [comment]
No need to change composer. Either reinstall or change the database (and clear cache afterwards).

**Comment by Portugao** [comment]
All clear. Works. I'm happy again.
