### ISSUE TITLE
Remove FilterUtil support

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#911]
It was a nice with you but it's time to say bye.

**Comment by craigh** [comment]
https://github.com/zikula/core/tree/1.4/src/lib/Zikula/Component/FilterUtil ?

**Comment by Guite** [comment]
Oh it is still there, thought it was deprecated. How about moving the docs from https://github.com/zikula/core/tree/1.4/src/lib/legacy/util/FilterUtil/docs into that folder?

**Comment by craigh** [comment]
feel free to move docs. They may need updating...

**Comment by Guite** [comment]
Moved docs to new folder in https://github.com/zikula/core/commit/90bd0f2fff8b6d539765d339d74aa21df9fc00f9

Closing this as "won't fix".
