### ISSUE TITLE
Find better solution for quick view modals

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#912]
Currently the modal windows containing quick views (display action) use the printer theme which is not optimal. First it contains a link list at the bottom and second it causes many conditions in the display template. Thus a better solution is needed. Maybe using PlainResponse.

**Comment by Guite** [comment]
@craigh 

1. I did a small test with `PlainResponse` and it seems that this is wrapped in the theme, too. What is the preferred way to get an output without any theme?
2. A printer theme is a legacy concept, isn't it? Today print views are done using `@media print { ... }` in css. Maybe we should remove the printer theme from the `master` branch of the core?

**Comment by rallek** [comment]
The current concept is so easy to use...

**Comment by Guite** [comment]
okay... it doesn't hurt us to keep the printer theme :p

**Comment by craigh** [comment]
`PlainResponse` is the correct way. Printer Theme is very not right. If it isn't working, then that would be a core bug

**Comment by craigh** [comment]
it sounds a little like https://github.com/zikula/core/issues/3087

**Comment by Guite** [comment]
I will do a more thorough test.

**Comment by Guite** [comment]
PlainResponse works at `/search/opensearch` so it seems to work in general.
