### ISSUE TITLE
Function get not working calling the user account

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#915]
```
Fatal error: Call to a member function get() on null in /domain/modules/MU/ImageModule/Container/LinkContainer.php on line 68
```

**Comment by Guite** [comment]
Please provide a stack trace.

**Comment by Portugao** [comment]
It seems I have big problems with overriding the link container. I close this. Sorry for my message.
It seems for me the overriding is not so easy for me like in Zikula 1.3.x.
