### ISSUE TITLE
Beneath dropdown for parent album 2 other select menues, one for albums, one for pictures

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#918]
Under the category select field, I have a second for albums and one for pictures.

I need only the first dropdown menue for albums.

Does it depend on the setting bidirectional?

**Comment by Guite** [comment]
Yes this is related to the `bidirectional` setting.
1. dropdown: chooses the parent (incoming)
2. dropdown: chooses the children (outgoing)
3. dropdown: chooses the pictures (outgoing)

For unidirectional relationships only the outgoing side would be included.
That outgoing relationships are included in editing is new (related to #10).

**Comment by Guite** [comment]
If you do not need the outgoing relationships override `addOutgoingRelationshipFields` in the `AlbumType` class and simply `return;` so it does nothing.

**Comment by Portugao** [comment]
Ok. Thx. That works.
