### ISSUE TITLE
List Element Button is missing

### ISSUE THREAD

**Issue by DirkThiele** [Guite/MostGenerator#937]
It is not possible to create elemts for a list because the button on the left hand side is missing for some reason.

In Version 0.6.2 the List-Element Button was right below the List-Button

**Comment by Guite** [comment]
Double-click the list.
See http://modulestudio.de/documentation/c/32-DiagramEditor#manage-list-entries

**Comment by DirkThiele** [comment]
Great!

I was searching for "list element" instead of "list entries". ;-)
