### ISSUE TITLE
White screen when submitting form with upload fields

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#942]
This is with MOST 0.70 with a ZK136 target. Can't seem to get a stack trace, sorry.

I do get a white screen when submitting the data.  I have traced the code in a debugger to the include file for /Base/AbstractUploadHandler.php.  I also have a similar module done with 0.70 beta that does NOT have this issue, for comparison.

PhpStorm reports that in the failing version, there is this:

$preset = new \SystemPlugin_Imagine_Preset('GSRA_Shrinker', [
                        'width' => $maxWidth,
                        'height' => $maxHeight,
                        'mode' => 'inset'
                    ]);

with the error "Short array syntax is allowed in php 5.4 only"

In the module that does work, there is no code dealing with $preset here.

Yeah, I know.  This site is going to get upgraded this year but it is still on 5.3.  Recommendations?  Go back to the beta version of 0.70?

**Comment by craigh** [comment]
change the code to

```
$preset = new \SystemPlugin_Imagine_Preset('GSRA_Shrinker', array(
'width' => $maxWidth,
'height' => $maxHeight,
'mode' => 'inset'
));

```

**Comment by Guite** [comment]
Yes, @craigh is right.

**Comment by robbrandt** [comment]
Thanks.  Might be a good idea to have a wiki page where workarounds for 1.3 targets can be found?  Since development for that target has ended.

**Comment by Guite** [comment]
Yes, this would probably bei helpful. Can you create it in this project? (I think MostGenerator is better for that than MostHelp)

**Comment by robbrandt** [comment]
here:

https://github.com/Guite/MostGenerator/wiki/MOST-0.70--zk136-workarounds

**Comment by Guite** [comment]
Thanks!
