### ISSUE TITLE
Incorrect defaults

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#945]
Using MOST 0.70 Final.

I have a number of mandatory integer fields that all have the default value set to zero in MOST.  However when the form is rendered, the values default to 1.

In the generated code, for the field "yearOfStudy", it has
/**
     * @ORM\Column(type="integer")
     * @var integer $yearOfStudy
     */
    protected $yearOfStudy = 0;

and then later on in the __construct it has:

$this->yearOfStudy = 1;

It seems the value used in the construct is the "mandatory" value; all my mandatory ints set their default value to 1, the non-mandatory ones set it to zero.

**Comment by Guite** [comment]
The 1 is a fallback value used for all mandatory fields lacking a default value. A value of 0 would not count for satisfying the requirement for a mandatory value. Open for suggestions.

**Comment by robbrandt** [comment]
Since reading up on defaults since last night I have a better appreciation for the problem now :)

In terms of filling out a form, there shouldn't be a default unless it's specified in the model.  The form shouldn't pass validation until all mandatory fields are filled out.

But that won't solve the problem for data inserted procedurally. Thus the need for a fallback.  Not sure what to advise.

Can the _display_ of the default value be automatically removed from the form template?

**Comment by Guite** [comment]
I need to rethink about this thorougly. Going to reply afterwards.

**Comment by Guite** [comment]
note for myself: this refs #724 because the current workaround is for helping to ensure an entity is always valid.

**Comment by Guite** [comment]
Also an optional datetime field gets the current date set in the entity constructor. If an empty field is submitted in the edit form the current date is saved.

**Comment by Guite** [comment]
-> https://github.com/Portugao/Blogging/blob/master/MU/BloggingModule/Form/Type/Base/AbstractPostType.php#L385
