### ISSUE TITLE
Incorrect path for email notification templates

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#946]
This is in MOST 0.70 targeting zk 1.36

I am using an enterprise workflow.  When I submit a form that sends a notification, the following error is generated:

Error! The template [email/notifyProposalModerator.tpl] is not available in the [modulename] module.

Looking at the files, there is NOT an "email" directory in the templates directory, and the needed file is named and located at "templates/emailnotifyProposalModerator.tpl"

Seems like the path to save is missing a / between "email" and "notifyProposalModerator"?

**Comment by Guite** [comment]
Yes, you are right. Please add this to the new workaround page for 1.3 targets.
(In 1.4 it works correctly; for example @portugao uses this functionality for Eternizer).
