### ISSUE TITLE
gettext variable substitution not working in email notifications

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#947]
This is in MOST 0.70 targetting zk1.36.

My received email notifications look like this:

--------
Hello %s,

A user changed his proposal "%s".

It's new state is: %s

Additional remarks:
Remarks

Link to the proposal: http://localhost/domain/index.php?module=gsra&type=admin&func=display&ot=proposal&id=2&slug=test-notification

Edit the proposal: http://localhost/domain/index.php?module=gsra&type=admin&func=edit&ot=proposal&id=2&slug=test-notification

This mail has been sent automatically by %s.

--------
Template variables are working except where gettext is supposed to be doing variable substitution.

**Comment by Guite** [comment]
Yes, you are right.

I don't remember the exact template code, but the differences are like this:

1.3 / Smarty:
```
{gt text='Hello %s' tag1='robbrandt'}
```
(iirc!)

1.4 / Twig:
```
{{ __f('Hello %userName%', { '%userName%': 'robbrandt' }) }}
```

So my guess is that the email templates used parts of the new syntax also for 1.3.

Please add this to the new workaround page for 1.3 targets.
(In 1.4 it works correctly; for example @portugao uses this functionality for Eternizer).

**Comment by Guite** [comment]
Just saw the old template in Git. It looks like this:
```
 <p>{gt text='Hello %s' tag=$recipient.name},</p>
```

I almost forgot all of this stuff... maybe try using `tag1` instead of `tag`?
