### ISSUE TITLE
Improve usage of home path

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#953]
There are `pagevars.homepath` and `path('home')`.

1. `path('home')` is preferred.
2. Never use homepath in a filepath.

So things like `{{ pageAddAsset('javascript', pagevars.homepath ~ 'vendor/twitter/typeahead.js/dist/typeahead.bundle.min.js') }}` need to be replaced.

Instead of using a vendor file directly from the vendor directory copy the files to web using https://github.com/zikula/core/commit/45b6f91aba75aceefd7343f50abb16babd7d3513 
Then use `asset()`.

**Comment by craigh** [comment]
I've not designed the tool to allow usage outside the core. It may need improvement in order to do that.

**Comment by craigh** [comment]
a third party module should keep its assets in its own `Resources` directory anyway right? then you can use `zasset()`?

**Comment by Guite** [comment]
The example above refers to `typeahead.js` which is included in the core, but not copied to `web`.

**Comment by craigh** [comment]
if typeahead is in the core, then please add it to the tool in quest and reference it accordingly

**Comment by craigh** [comment]
fyi - this relates to https://github.com/zikula/core/issues/3388 in some ways. composer would copy a third party module's assets to `web`

**Comment by craigh** [comment]
another thought we be to use `app.request.basepath` (or something like that, I can't remember).

the reason `pagevars.homepath` and `path('home')` don't work is because they could (optionally) include the `locale` parameter (e.g. `http://www.mywebsite.com/de`)

**Comment by craigh** [comment]
also `/vendor` is not guaranteed to be at the http root
