### ISSUE TITLE
Incorrect case usage when selecting moderator groups for notification

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#954]
using MOST 0.70 Final for zk1.36 target

This works correctly in one of my current projects but not in another.  Not sure what the difference is.

For the one that doesn't work:

The installer creates the modvar: $this->setVar('moderationGroupForApplications', 2);

When sending a notification at collectRecipients(), it does:
     $objectType = $this->entity['_objectType'];
     $moderatorGroupId = $this->getVar('moderationGroupFor' . $objectType, 2);

This results in a getVar for "moderationGroupForapplications", with default value as 2.

Setting the groups in module configuration does work correctly, but upon sending, the recipients are always the Administration group.

**Comment by robbrandt** [comment]
Actually it's not just case, it's also plurality.  The variable is moderationGroupForApplications, but the search is for moderationGroupForapplication.

**Comment by robbrandt** [comment]
I am inclined to fix this by changing the variable to singular "moderationGroupForApplication" because plurality in entities might have some linguistic issues I don't know very well.  Handling case using ucfirst seems simple enough though.

**Comment by Guite** [comment]
Interesting point. I was tempted to add some code to determine the plural form in the notification helper (1.4), but changing the modvar to the singular version could be easier. Will think about this before fixing this in the generator codebase :thinking:  ;-)

**Comment by robbrandt** [comment]
Well, in the generator you know the plural value because it's specified in the model.  Maybe for 1.4 you should leave everything as-is, except use the actual plural value instead of $objectType here:
$this->getVar('moderationGroupFor' . $objectType, 2);

**Comment by robbrandt** [comment]
The disadvantage of changing to singular is having to change all the other references to those vars elsewhere, like in the Settings panel.

**Comment by robbrandt** [comment]
Yeah I've changed my mind, at least for the purposes of target zk1.36.  It's fewer changes to document and execute after generation.  I'll just say "make the getVar match the actual variable name.  Hard code if you like."
