### ISSUE TITLE
implement Zikula\SearchModule\SearchableInterface

### ISSUE THREAD

**Issue by craigh** [Guite/MostGenerator#956]
implement Zikula\SearchModule\SearchableInterface

https://github.com/zikula/core/blob/1.4/src/docs/Core-2.0/Searchable.md

AbstractSearchable is `@deprecated`

**Comment by craigh** [comment]
example: https://github.com/zikula/core/blob/1.4/src/system/UsersModule/Helper/SearchHelper.php

**Comment by Guite** [comment]
Has already been done in https://github.com/Guite/MostGenerator/commit/1e4e40deb42d468acf50e07f9d73306780fbb589

**Comment by craigh** [comment]
👍
