### ISSUE TITLE
Fatal when uploading image with scale down options enabled

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#957]
MOST 0.70 Final target z1.36

Sorry I don't have a stack trace, I can't seem to get that working on zk1.3x.

However I have stepped through the debugger until it crashes trying to do

// resize to allowed maximum size
                    $thumbManager = $serviceManager->get('systemplugin.imagine.manager');

in AbstractUploadHandler.php

Maybe my installation is missing something from Imagine?  How do I test it?  Are there dependencies for it my dev machine might be missing?

**Comment by Guite** [comment]
The imagine should be included in the 1.3 core:
https://github.com/zikula/core/tree/1.3/src/plugins/Imagine

Maybe try to compare with the current 1.4 code:
https://github.com/Guite/MostGenerator/blob/master/bundles/org.zikula.modulestudio.generator/src/org/zikula/modulestudio/generator/cartridges/zclassic/controller/helper/UploadHelper.xtend#L216
