### ISSUE TITLE
Permission issues with Create (related item) in ActionItemList

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#963]
MOST 0.70 targetting zk1.36.  I have two entities related One (Proposals) to Many (Evaluations). Different users have different permissions on each record.  I want a manager group to create Evaluations but not edit Proposals.  However when permissioned to read Proposals and Add Evaluations, and presented with a list of Proposals, there is no action item for "Create Evaluation".  It seems that in AbstractProposal.php, there is this:
// more actions for adding new related items
           $authAdmin = SecurityUtil::checkPermission($component, $instance, ACCESS_ADMIN);

Would probably need to be ACCESS_ADD

As well, in the Proposal display template, where "mayManage" is set for the Action Item list, we have:

{assign var='permLevel' value='ACCESS_COMMENT'}
            {if $lct eq 'admin'}
                {assign var='permLevel' value='ACCESS_ADMIN'}
            {/if}
            {checkpermission component='modulename:Proposal:' instance='`$application.id`::' level=$permLevel assign='mayManage'}

ACCESS_COMMENT seems too low for a user lct threshold, I would think it would also be ACCESS_ADD.

And, checkpermission tests the permissions of the entity being viewed, not that permissions of the entity to be created.  Should be:
{checkpermission component='modulename:Evaluation:' instance='`$application.id`::' level=$permLevel assign='mayManage'}
?

**Comment by robbrandt** [comment]
Another one...

In /Entity/Proposal.php, prepareItemActions(), where 

// more actions for adding new related items
            $authAdmin = SecurityUtil::checkPermission($component, $instance, ACCESS_ADMIN);
            
            $uid = UserUtil::getVar('uid');
            if ($authAdmin || (isset($uid) && $this->getCreatedUserId() != '' && $this->getCreatedUserId() == $uid)) {
            
                $title = __('Create evaluation', $dom);
                $urlArgs = array(
                    'ot' => 'evaluation',
                    'evaluation' => $this['id']
                );
                $this->_actions[] = array(
                  'url' => array(
                    'type' => 'user',
                    'func' => 'edit',
                    'arguments' => $urlArgs
                  ),
                  'icon' => 'add',
                  'linkTitle' => $title,
                  'linkText' => $title
                );
            }

$authAdmin = SecurityUtil::checkPermission($component, $instance, ACCESS_ADMIN);

also has the access level too high, I changed mine to ACCESS_ADD, and renamed the variable for clarity since it's no longer checking an admin:

// more actions for adding new related items
            $authUser = SecurityUtil::checkPermission('RosemaryGrantApplication:Evaluation:', $instance, ACCESS_ADD);

            $uid = UserUtil::getVar('uid');
            if ($authUser || (isset($uid) && $this->getCreatedUserId() != '' && $this->getCreatedUserId() == $uid)) {

                $title = __('Create evaluation', $dom);
                $urlArgs = array(
                  'ot' => 'evaluation',
                  'evaluation' => $this['id']
                );
                $this->_actions[] = array(
                  'url' => array(
                    'type' => 'user',
                    'func' => 'edit',
                    'arguments' => $urlArgs
                  ),
                  'icon' => 'add',
                  'linkTitle' => $title,
                  'linkText' => $title
                );
            }

**Comment by Guite** [comment]
> ACCESS_COMMENT seems too low... I would think it would also be ACCESS_ADD

Actually this depends on the workflow.
