### ISSUE TITLE
Action Item List placement

### ISSUE THREAD

**Issue by robbrandt** [Guite/MostGenerator#964]
This is a low priority enhancement request.

Many of my entities have a lot of fields, and in view mode there are too many columns to see them all on the screen.  Seems like I am constantly scrolling right to get to the action item list.

It's pretty simple to edit the template to move it to one of the first columns, so there's  a simple workaround.  But if I want my UI to be consistent I have to do this to ALL view templates.

It seems to me that putting it in the first columns always would work in all circumstances.

**Comment by rallek** [comment]
+1

**Comment by Guite** [comment]
Additionally I made the columns for mass selection and item actions fixed, like in this example: http://jsfiddle.net/nt7fd965/148/
