### ISSUE TITLE
Scribite Plugin Paths should be relative

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#966]
I am using the plugin for scribite in some modules. Now I discovered the path which is added to the text using the wisiwyg editor is a full path

![grafik](https://cloud.githubusercontent.com/assets/935250/22927020/71964064-f2af-11e6-97cd-90ed34d02f07.png)
The first path is added via databse input (that is how I want to have it). The second one is generadted by the plugin.

The full path will make me trouble when switching the site into live mode (the 2017. will disappear).

**Comment by Guite** [comment]
One problem with that is that both ways are sometimes needed: if you for example prepare a newsletter you need absolute urls. Maybe an option for controling this would be the best way here.

**Comment by rallek** [comment]
I never thought about newsletter. But that is true. Is it possible to mark the indirekt links somehow and let a potential newsletter grab the text via an interface where the indirect link will exchanged by a direct one?

For me at the moment a configuration e.g. ``[ ] switch on direct links`` would be ok.

**Comment by Guite** [comment]
Well, I've got a proposal:

We already have the `paste as` field with entries like _Link to the person_, _ID of person_ and some more for images. We could replace _Link to the person_ by _Relative link to the person_ and add _Absolute link to the person (including domain)_

**Comment by rallek** [comment]
I like this idea!

**Comment by rallek** [comment]
I can now see the selection. But if I click on any item, nothing happens. Also the cancel button did not close the window.

The function seems to be broken.

I will add a new ticket for this
