### ISSUE TITLE
[1.4.6]Thumbnails not shown in view and display templates

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#983]
I get no thumbnails shown in view and display templates...don't know if I make a mistake.

```
domain/media/cache/resolve/zkroot/rc/26s62GGt/userdata/MUSlideshowModule/shows/imageofslideshow/Akustische-Gitarre-Licht-und-Schatten3.jpg?filters%5Bthumbnail%5D%5Bsize%5D%5B0%5D=240&filters%5Bthumbnail%5D%5Bsize%5D%5B1%5D=180&filters%5Bthumbnail%5D%5Bmode%5D=inset
```
is the path to the thumbnail

Target in MOST ZK14

**Comment by Guite** [comment]
This seems to be a vendor problem.
As a workaround you can try to replace `vendor/liip/imagine-bundle/Binary/Locator/FileSystemLocator.php` by the attached version.

[FileSystemLocator.php.txt](https://github.com/Guite/MostGenerator/files/912346/FileSystemLocator.php.txt)

**Comment by Portugao** [comment]
Thx, I will try.
So I should open a ticket in the core?

**Comment by Guite** [comment]
No, it's not part of the core. I will open a ticket at https://github.com/liip/LiipImagineBundle/

**Comment by Guite** [comment]
It is already existing there (probably it is the same issue): https://github.com/liip/LiipImagineBundle/issues/869

**Comment by Portugao** [comment]
Ah Ok; you said vendor, sorry and thx.

**Comment by Guite** [comment]
Please check if the attached version works or not. As I copied it from a 1.5 installation it could be different than in 1.4.6. But if there are problems I can also provide one based on 1.4.6.

**Comment by Portugao** [comment]
Seems to work. Thx a lot.
