### ISSUE TITLE
[1.4.6] Configuration of several images template does not work like expected

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#985]
I have several upload fields for pictures.

In the config template there is a dropdown named images. I get the needed menue points, but only the first one is working and showing all options for each upload field.

Should only get the fields for the relevant menue point....

**Comment by Guite** [comment]
Would you please mail me the model for reproduction?

**Comment by Portugao** [comment]
Done!

**Comment by Guite** [comment]
The problem is related to that the name of your first image field is contained in the name of further image fields. Fix coming.

**Comment by Portugao** [comment]
Thx, maybe it generates also #983 .
