### ISSUE TITLE
[1.4.6] Field Additional remarks appears in each tab

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#988]
It is only a cosmetic issue, that I have this field in each tab in the backend, when I want to create an entry.

**Comment by Guite** [comment]
Actually it is not contained in any tab, but placed below the tabs. I did this on purpose to have it always visible.
What do you suggest? A dedicated tab named _Communication_?

**Comment by Portugao** [comment]
Hmmhmm....good question...

**Comment by Portugao** [comment]
I think we can close it. It's fine like you did.

**Comment by Guite** [comment]
Okay. If it turns out that many users find it confusing we can still invent another solution.
