### ISSUE TITLE
[1.4.6] Workflow standard - no entry into the workflow table

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#989]
I have an entity with:
workflow = standard
timestamp as startdate
timestamp as enddate
Has Archive = true
Has Tray = true

I get this error message:
```
Sorry, but an error occured during the approve action. Please apply the changes again! Warning: escapeshellcmd() has been disabled for security reasons
```
and there is no entry in the workflow table.

**Comment by Guite** [comment]
Which core version do you use? Which target core version is set in the model?

**Comment by Portugao** [comment]
Oh, forgot to create a settings container....
I will recheck; sorry.

**Comment by Portugao** [comment]
Checked again, same issue.
Core 1.4.6, target ZK14

**Comment by Guite** [comment]
Please mail me the model and instructions for how to reproduce the issue. Thanks in advance!

**Comment by Portugao** [comment]
Done.

**Comment by Guite** [comment]
Just generated your module and installed it on a fresh 1.4.6 installation.

I can both `submit` and `submit and approve` a post without problem.
So I could not reproduce the issue :thinking:

**Comment by Portugao** [comment]
Hmmhmm...which php version do you use?

**Comment by Guite** [comment]
PHP 7.something

**Comment by Portugao** [comment]
Ok, thx for having a look

**Comment by Portugao** [comment]
Changed php to 5.6.bla and it works. With 5.5.bla not

**Comment by Portugao** [comment]
Seems not to be there anymore. So I close.
