### ISSUE TITLE
Would be fine, text fields get truncated in the view templates

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#990]
If we have many fields, the text areas are small and get expanded to the footer in the view template.

**Comment by Guite** [comment]
How many characters do you suggest?

Also: do you know that you can control which fields appear on view pages, display pages and sorting list using the `displayType` property (see docs)? Using this you could also hide the text field on view pages completely.

**Comment by Portugao** [comment]
Yes I know. Thx.
I suggest about 100.

**Comment by Portugao** [comment]
Better 50, if possible.
