### ISSUE TITLE
Site does not get found after editing title.

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#993]
I have an entity with translatable fields.

If I edit the relevant field 'title' (sluggable position = 1), the slug field in the entity table does not get changed.
So the entry is not available with this message:
```
MU\BloggingModule\Entity\PostEntity object not found.
```
```
       }
        if (null === $object && false === $configuration->isOptional()) {
            throw new NotFoundHttpException(sprintf('%s object not found.', $class));
        }
        $request->attributes->set($name, $object);
```

`slugUnique` and `slugUpdatable` both are set to `true`.

**Comment by Guite** [comment]
`slugUpdatable` has the default value `true`?
Is the slug contained in the translation table?
Is it's value changed there?

**Comment by Portugao** [comment]
1. Yes
2. Yes
3. Yes

**Comment by Guite** [comment]
If the entity table contains `my-slug` and the translation table contains `my-updated-slug`, which one is used for creating the display url?

**Comment by Portugao** [comment]
Will have a look

**Comment by Portugao** [comment]
my-updated-slug in the translation table.
Slug editable is active in the model.

**Comment by Guite** [comment]
So when the translated slug is used and also changed during update, what is the issue? :smile:

**Comment by Portugao** [comment]
If I call the the diplay template from view I get the error above. The site called with the slug from translatable table does not get found.
I see, the title of this issue is missunderstandable; I will change it.

**Comment by Guite** [comment]
Okay I see! Please tell me the value of `slugUnique`, too.

**Comment by Portugao** [comment]
Slug unique is active.

**Comment by Portugao** [comment]
Also relevant in modules for Zikula 1.5.
