### ISSUE TITLE
Disable some special features by default?

### ISSUE THREAD

**Issue by Guite** [Guite/MostGenerator#994]
Maybe it would be good to disable some features by default which are rather rarely needed:

- Multihook needles
- Tag support
- Newsletter plugin
- Mailz plugin
- Others?

http://modulestudio.de/documentation/c/87-GeneratorReference#settings-container

Pending content support, moderation block and moderation panel are only generated if a workflow with approval exists. So their default value can still be `true` I think.

What do you think? @rallek @gfr @portugao @craigh

**Comment by gfr** [comment]
+1

**Comment by rallek** [comment]
Why not remembering the last configuration. So everybody do have his own set.

**Comment by Guite** [comment]
Because it does not make sense to see this per user, but per module. What is good for one module, isn't necessarily also reasonable for another one.

**Comment by craigh** [comment]
since none of those modules/services are currently compatible with 2.0 it makes sense to disable them. When and if they do become compatible it still makes sense to have them be optional to the module.
