### ISSUE TITLE
[1.4.6] Timestamp field as end date - Validation gives value not valid

### ISSUE THREAD

**Issue by Portugao** [Guite/MostGenerator#996]
In memory of talk on slack.com, there is an new situation with the end date field now.

I have a timestamp field, that is activated as end date.

This field is not mandotory and not nullable. 
If I try to save (the field shows the format for date and time), I get the validation error, the value is not valid.

**Comment by Guite** [comment]
Can you add a screenshot of the form field values before submit?

**Comment by Portugao** [comment]
![enddate and startdate](https://cloud.githubusercontent.com/assets/493707/25274243/6d509d42-268f-11e7-813b-f63d3e4c8bcc.png)

Screeshot with Firefox. In Chrome I have in the date field: tt.mm.jjjj and in the time field --:--:--

**Comment by Portugao** [comment]
For the startdate I get no error.

**Comment by Guite** [comment]
Please try this:

1. Edit https://github.com/Portugao/Blogging/blob/master/MU/BloggingModule/Entity/Base/AbstractPostEntity.php#L286
2. Change `"value > this.getStartDate()"` to `"value == null or value > this.getStartDate()"`
3. Empty the cache
4. Check if it works then

**Comment by Portugao** [comment]
Does not work.

**Comment by Guite** [comment]
Maybe `!value or value > this.getStartDate()`?

**Comment by Portugao** [comment]
Hmhmm...does not help....very strange thing with this field.

**Comment by Guite** [comment]
Does it work if you remove this expression constraint completely? Maybe it isn't the cause of the problem at all...

**Comment by Portugao** [comment]
Saving works with actual time in the DB.

**Comment by Guite** [comment]
To confirm: as soon as you remove the expression assert, submitting the form with an empty value? So this assert is causing the validation error?

**Comment by Portugao** [comment]
Yes. No expression assert, I can save with an empty value in the field. But it get saved with actual date and time in the DB.
