### ISSUE TITLE
how should the generator use locale configuration?

### ISSUE THREAD

**Issue by rallek** [Guite/MostGenerator#998]
I would love to see an other usage of the locale configuration.

here my use case:
I do have a text field configured in MOST with locale and not mandatory. This leads currently to a generated dropdown field with the possible selection of the installed languages plus all (if not mandatory). But the code is not using it for locale filtering, so I have to implement the code (or Axel is doing it for me ;-) )

My proposal:
In frontend views and in blocks only items of the current language should be shown by default (filtering). If someone do need this field in another way he should do the customization himself (delete the filter from the code).

If I look around in Zikula this behavior can be seen at several places (e.g. in blocks module). For me the new behavior would be the expected way how Zikula is using locale dropdown fields.

What are you thinking about this proposal?

**Comment by Guite** [comment]
@gfr @portugao @craigh @robbrandt opinions please

Should the generator automatically filter data in the frontend?

1. for locale fields?
2. for language fields?
3. how to handle multiple locale and/or language fields in one entity?

**Comment by rallek** [comment]
I think only one locale field should be allowed per entity than but translate should be available as well in parallel

**Comment by Portugao** [comment]
What does a locale field in MOST at the moment?

**Comment by rallek** [comment]
creating a dropdown with the installed languages

**Comment by Guite** [comment]
it provides a locale selector during editing - similar to language fields providing a language selector. But there is no additional logic applied to data selection based on it at the moment.

**Comment by Portugao** [comment]
Language fields have a logic behind. a german field is only shown if the actual language is german, right?

So a locale field makes only sense, if I have no language fields. And If I have language fields, a locale field makes no sense.

**Comment by rallek** [comment]
Think about another usecase. 
In my module you have the situation you want to have an item only shown at one language not at any other. In this case you do need a locale with filter.
My module do have a configuration if you want to have the items translatable or not. If I switch on the translatable option I hide the field for the locale and have the default ``all``. But If you want to have a different set of items in one entity for each locale the translation makes no sence.

I am using this in my helper module that way. Same module for three different sites.

**Comment by Portugao** [comment]
I see.

**Comment by Guite** [comment]
There should be an explicit setting for the filter functionality rather than doing it automatically.

**Comment by Guite** [comment]
https://github.com/Guite/MostHelp/commit/ce6185d0c932c92ae0bec18f57b09324c169e4e1
